### ISSUE TITLE
OpenStreetMap Copyright and License

### ISSUE THREAD

**Issue by willherr** [liodali/osm_flutter#101]
According to their Copyright and License page (https://www.openstreetmap.org/copyright), I think by default the copyright should be added to this widget according to their specification "For a browsable electronic map, the credit should appear in the corner of the map". I'm no lawyer, but I think this repo may be breaking their copyright and license rules at least when it comes to the demo and snippets.

In case something changes with their copyright and licensing, it may be a good idea to add an option to opt-out of the credit.

**Comment by liodali** [comment]
I used https://github.com/osmdroid/osmdroid in Android  and tangrams for swift  
so if i break that rules that means that library break rules not me 
this library just used native libraries for android/iOS

**Comment by willherr** [comment]
Gotcha. Well either way, anyone that uses this package will have to add a copyright by hand. Could be nice in any case for it to be part of the package. More of a good Samaritan feature than anything, but maybe you're right that those libraries should be adding the copyright instead. Gotta pass the buck somewhere:
- at the source (those libraries)
- at the distributor (this package)
- at developer (everyone that uses the libraries / package)

Like I said, Im not lawyer but I'm sure everywhere in this chain should have proper credits, but I added it in my project so we are good should OSM want to open a suit. Just thought I would share here in case you felt the same. But like I said, doesn't matter to me since I am covered.

**Comment by liodali** [comment]
ok i understand your point now.
i will add it that if the library built in the production mode
thanks you for this information

**Comment by bestofman** [comment]
I just found this package and wanna use it in my application. Should I add any copyright regarding codes somewhere within the application or it has been already included? 

Please let me know more. Thank you!

**Comment by liodali** [comment]
licence is MIT your can used freely
