### ISSUE TITLE
Ugly world map displayed during map initialization

### ISSUE THREAD

**Issue by cbopp-art** [liodali/osm_flutter#102]
During the initialization of OSMFlutter, a strange empty world map is represented before the final map and current location/position is beeing displayed to the user. Would be great if there could be a callback method or similar called if the map is completely loaded, that would help to implement a progress loading bar.

<img width="358" alt="Screenshot 2021-06-22 at 21 34 43" src="https://user-images.githubusercontent.com/2764787/122988196-c1d3a300-d3a1-11eb-8c97-d13f24bd7df8.png">

**Comment by liodali** [comment]
you want to customize loading or listener if map is ready ?

**Comment by liodali** [comment]
do you prefer to  be one single map that not repeat it like this ?
![device-2021-06-23-004440](https://user-images.githubusercontent.com/16631886/123013532-51864b00-d3bc-11eb-8803-a6f53a7f39e9.png)

**Comment by cbopp-art** [comment]
Yes, the possibility to display a customized loading with a listener until the map is finally loaded. The world map that is temporarily appeared until the map is loaded is not very useful I think so it would be great to get rid of it.

**Comment by liodali** [comment]
ok i will add this feature, but lot of thing will change in the map maybe it will took me sometime to implement

**Comment by liodali** [comment]
added widget attribute `mapIsLoading`  for now it will be available only for android 
until i will add that to ios  and  web
i will publish new version later feel free to test it

**Comment by liodali** [comment]
you can check `0.8.0`

**Comment by cbopp-art** [comment]
Great, will check it! Thank you.

**Comment by cbopp-art** [comment]
This works like a charm! The issue can be closed.

**Comment by liodali** [comment]
good, i will add also init listener in mapController and OSMFlutter if you want to add some logic to after map init 
that's will be available next week,
i will close it when  i add the init listener

**Comment by liodali** [comment]
i added `onMapIsReady` as attribute to OSMFlutter to get notifier when map is initialized 
and alo you can use `listenerMapIsReady` in controller to listener when map is initialized
