### ISSUE TITLE
Null pointer Exception while drawing a road between two points

### ISSUE THREAD

**Issue by jesussmile** [liodali/osm_flutter#107]
I am trying to draw roads between two `GeoPoint` without using `interestPoints`, I keep running into this error

`E/MethodChannel#plugins.dali.hamza/osmview_0(20152): java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.List<kotlin.collections.HashMap<kotlin.String, kotlin.Double> /* = java.util.HashMap<kotlin.String, kotlin.Double> */>`

The way I am trying to implement is by removing the `interestPoints` totally, I suppose it is a required field how can I get past it ?

`
 IconButton(
            onPressed: () async {
              try {
                await controller.removeLastRoad();

                //selection geoPoint
                GeoPoint point = await controller.selectPosition(
                    icon: MarkerIcon(
                  icon: Icon(
                    Icons.location_history,
                    color: Colors.amber,
                    size: 48,
                  ),
                ));
               // GeoPoint pointM1 = await controller.selectPosition();
               // GeoPoint pointM2 = await controller.selectPosition(
                   // imageURL:
                     //   "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/1.png");
                GeoPoint point2 = await controller.selectPosition();
                
                RoadInfo roadInformation = await controller.drawRoad(
                    point, point2,
                   // interestPoints: [pointM1, pointM2],
                    roadOption: RoadOption(
                        roadWidth: 10.0,
                        roadColor: Colors.blue,
                        showMarkerOfPOI: false));
                print(
                    "duration:${Duration(seconds: roadInformation.duration!.toInt()).inMinutes}");
                print("distance:${roadInformation.distance}Km");
              } on RoadException catch (e) {
                print (e);
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(
                    content: Text(
                      "${e.errorMessage()}",
                    ),
                  ),
                );
              }
            },
            icon: Icon(Icons.map),
          ),
`
     

It would be nice if you could rename `interestPoint` to `intersectPoint` ? Makes more sense but it's up to you.

**Comment by liodali** [comment]
the problem is in android side i will check i will fix soon 
yeah interestPoint is not required field in dart side

**Comment by liodali** [comment]
when i check for  `interestPoint` in android side i check on wrong key
oh so i will publish a new version to night

**Comment by jesussmile** [comment]
That would be great! Thank.

**Comment by liodali** [comment]
check 0.7.8+3

**Comment by jesussmile** [comment]
Perfect! Thank you so much.
