### ISSUE TITLE
OSRMRoadManager::getRoad: error code=InvalidUrl

### ISSUE THREAD

**Issue by jesussmile** [liodali/osm_flutter#109]
Hey! sorry to bother you again, I think there is an error with the URL after I updated my plugin to the recent one `flutter_osm_plugin: ^0.7.8+3` .  However it works correctly with the example project I download from Github .
The output in Debug console

`OSRMRoadManager::getRoad: error code=InvalidUrl
`

`OSRMRoadManager.getRoads:https://router.project-osrm.org/route/v1/driving/routed-car/route/v1/driving/85.3481299537,27.7013308999;85.3459259442,27.7013987508?alternatives=false&overview=full&steps=true`

**Comment by liodali** [comment]
ok i will check it

**Comment by liodali** [comment]
the error was in osmpackbonux they start using https so no need for secureURL from now 
i will removed and i will publish new version

**Comment by liodali** [comment]
new version was shipped `0.7.8+4`
