### ISSUE TITLE
Can't save the state of the map after searching for address

### ISSUE THREAD

**Issue by jesussmile** [liodali/osm_flutter#112]
I am trying to use `AutomaticKeepAliveClientMixin` to save the state of the Map when I draw features like road etc . For the most part it seems to be working but as soon as  I go to the search place and search for a location, the map will reload.  Can you explain this behaviour and how can I get around it? I tried with just populating the search result and not selecting it, still the map reloads.

`class _MainExampleState extends State<MainExample> with AutomaticKeepAliveClientMixin<MainExample> {`

 ``` 
bool get wantKeepAlive => true;
  @override
  
  Widget build(BuildContext context) {
    super.build(context);
    return Scaffold( 
```

**Comment by liodali** [comment]
try put key inside scaffold of  the main
