### ISSUE TITLE
Minor issue with naming convention

### ISSUE THREAD

**Issue by jesussmile** [liodali/osm_flutter#121]
HI! Nothing major but as your class `GeoPoint` calls out for `GeoPoint =GeoPoint(latitude: latitude, longitude: longitude)` but the return string in your GeoPoint class gives longitude first than latitude which is a little confusing `return 'GeoPoint{longitude: $longitude, latitude: $latitude}';`  Perhaps we could keep it to similar naming convention as in navigation it will give 0km and 0 sec.

**Comment by liodali** [comment]
ok i will change that
