### ISSUE TITLE
Resize the map to fit the road selected

### ISSUE THREAD

**Issue by jesussmile** [liodali/osm_flutter#122]
Is there a way currently to animate or resize  the screen such that it fits the road selected by the user?

**Comment by jesussmile** [comment]
> Is there a way currently to animate or resize the screen such that it fits the road selected by the user?

**Comment by liodali** [comment]
i will see if  thatis  possible but the  only thing that you can do is just to zoom in to first position of road

**Comment by jesussmile** [comment]
https://github.com/liodali/osm_flutter/discussions/137
