### ISSUE TITLE
Using changeLocation resets the zoom

### ISSUE THREAD

**Issue by arboss** [liodali/osm_flutter#123]
I'm using 0.7.9+3. Whenever i call changeLocation the zoom of the map gets reset to maximally zoomed out. Also it seems that the markers from previous changeLocation calls don't get removed, is that intended behaviour?

**Comment by liodali** [comment]
i will fix that

**Comment by liodali** [comment]
i fixed the problem and i will publish new version to night

**Comment by liodali** [comment]
check the new version `0.7.10`

**Comment by arboss** [comment]
Thank you for the fix!

However when using 0.7.10 I'm getting the following build error:

`
/home/me/snap/flutter/common/flutter/.pub-cache/git/osm_flutter-74d2329f884f9fb4315a9ea94c4ce51215ebf72b/android/src/main/kotlin/hamza/dali/flutter_osm_plugin/FlutterOsmView.kt: (72, 1):
Conflicting overloads: public fun GeoPoint.toHashMap(): kotlin.collections.HashMap<String, Double> /* = java.util.HashMap<String, Double> */ defined in hamza.dali.flutter_osm_plugin in file FlutterOsmView.kt,
public fun GeoPoint.toHashMap(): kotlin.collections.HashMap<String, Double> /* = java.util.HashMap<String, Double> */ defined in hamza.dali.flutter_osm_plugin in file FlutterOsmView.kt
`

**Comment by liodali** [comment]
try to run `flutter clean & flutter pub get`

**Comment by arboss** [comment]
Thanks. The clean did it :)
Now working as expected :+1:
