### ISSUE TITLE
Feature request to change the orientation of marker

### ISSUE THREAD

**Issue by jesussmile** [liodali/osm_flutter#133]
With the current option to add marker I can't find a way to change the orientation of `MarkerIcon`, So, all objects on the map will face the same direction, With the `Location` plugin it is possible to get the heading of the object, is it possible to change the rotation based on heading? Something like this?

```ruby
 markerIcon: MarkerIcon(
            rotation: currentLocation.heading
            image: AssetImage(
              "images/images/jogger.png",
            ),
          ));
```

**Comment by liodali** [comment]
you wanto markers follow the rotation of user orientation or rotate by their own values !

**Comment by jesussmile** [comment]
The markers will change according according to orientation of users. Like if 4 users on map facing east west north south then the markers will so the same.  I think I should be able to get the orientation of the user from the server.

**Comment by liodali** [comment]
ok i understand you point , i will add this to list of feature
i will add angle attribute for static point that you can change their orientation in real time

**Comment by jesussmile** [comment]
Thank you ! It will be sweet!

**Comment by liodali** [comment]
but i will make that attribute when we set the new values
because in that method i can change the orientation of the marker

**Comment by jesussmile** [comment]
Oh sure!  You mean like the condition we discussed in previous post about using custom markers after receiving live locations?  In `  await controller.setMarkerOfStaticPoint(String id,MarkerIcon markerIcon );`

**Comment by liodali** [comment]
oh also i can do that in that method also because i already create bitmap of the marker
so also i think i can do that in both of the method setMarker or setStaticPosition
i will add it to `setMarkerOfStaticPoint` will be better

**Comment by jesussmile** [comment]
Yes! Thats what I thought so. Would be happy to test it out.

**Comment by jesussmile** [comment]
As we load the map there is an arrow icon that already does this, can we not use it ?
![Screenshot_20210722-082717_Gallery](https://user-images.githubusercontent.com/11044978/126583289-3d7ba568-1f26-411e-ba4d-152f2266027a.jpg)

**Comment by liodali** [comment]
i will see when i will start add this feature.

**Comment by liodali** [comment]
the problem that i faced now if static point have mulitple geopointshould i make angle for each geopoint or the same angle will apply for all geopoint in the same id

**Comment by liodali** [comment]
i think if we want to make each geopoint has specific oritentation that should be implemented in `setStaticPosition`

**Comment by jesussmile** [comment]
If you could, it would be best if we could use multiple angles, The static point should rotate based on their bearing, for example, I calculate the bearing of a moving vehicle like this
```ruby
double bearing(final GeoPoint p1, final GeoPoint p2) {
    double diffLongitude =
        degToRadian(p2.longitude) - degToRadian(p1.longitude);

    final y = Math.sin(diffLongitude);
    final x = Math.cos(degToRadian(p1.latitude)) *
            Math.tan(degToRadian(p2.latitude)) -
        Math.sin(degToRadian(p1.latitude)) * Math.cos(diffLongitude);

    return radianToDeg(Math.atan2(y, x));
  }

  /// Converts degree to radian
  double degToRadian(final double deg) => deg * (pi / 180.0);

  /// Radian to degree
  double radianToDeg(final double rad) => rad * (180.0 / pi);

```
then I can apply it to the Marker Icon sth like this
```ruby
MarkerIcon.rotation(bearing)
```

**Comment by liodali** [comment]
so that should be as i told in `setStaticPosition` 
i will add GeoPointWithOrientation that will contain angle attribute (rad) in that case we can apply orientation for each geoPoint

**Comment by liodali** [comment]
so now i will remove the previous implementation and i will try with the new method

**Comment by jesussmile** [comment]
Yes please do, The only way I could find right now is to rotate the whole map to make the navigation look believable but if we are watching multiple objects on the screen moving then we need it as you have said above.
https://user-images.githubusercontent.com/11044978/127737845-81be0f4f-85c9-4c61-b6fa-7dfa61c2a090.mp4

**Comment by liodali** [comment]
check the new version `0.8.3+1`

**Comment by liodali** [comment]
instead of using GeoPoint use `GeoPointWithOrientation` and angle accept rad value

**Comment by jesussmile** [comment]
Great! Let me try it out.

**Comment by jesussmile** [comment]
can you explain why you are doing this ? in `GeoPointWithOrientation` 
Earlier I was able to rotate the map as per the heading and it was pretty accurate now the object is spinning 😄 , I will adjust my code as per your plugin if you tell me why you have this here, specially the `180/pi`
```ruby
Map<String, double> toMap() {
    return super.toMap()
      ..putIfAbsent(
        "angle",
        () => angle * (180 / pi),
      );
  }
```

**Comment by liodali** [comment]
the value accepted is should be in radian for example pi/2 or X * pi  between 3.14 and -3.14
and before i send tothe  native view to rotate the marker i transformet to  degree for android because bitmap accept degree values but for ios i will keep it en radian because transformation should be done with radian value

**Comment by liodali** [comment]
for your code if you transform the value to degree just leave without transformation to degree

**Comment by jesussmile** [comment]
okay! spent 5 hours only to realize I was sending degrees to `GeoPointWithOrientation`. I correct it, it looks so beautiful. You are absolutely brilliant. I have used google maps too but I could never achieve this level of customization. Thank you so very much for your hard work and patience.

**Comment by liodali** [comment]
but i already told  you in comment that should be rad (radian) 
I'm sorry 
I will add it also in the documentation to be clear
