### ISSUE TITLE
How can I remove the default Yellow person icon?

### ISSUE THREAD

**Issue by jesussmile** [liodali/osm_flutter#134]
I couldn't find a way to change the yellow default icon of a man,  so, I set up a `StreamSubscription` to change the icon, 
```ruby
void getRunnerLocationUpdates() {
    runnerStreamSubscription =
        Geolocator.getPositionStream().listen((Position position) async {
      StaticPositionGeoPoint(
          currentFirebaseUser.uid,
          MarkerIcon(
         
            ),
          ),
          [
            GeoPoint(latitude: position.latitude, longitude: position.longitude)
          ]);
      await osmRideController.setMarkerOfStaticPoint(
          id: currentFirebaseUser.uid,
          markerIcon: MarkerIcon(
            // rotation: currentLocation.heading
            image: AssetImage(
              "images/images/runner.png",
            ),
          ));
      await osmRideController.setStaticPosition([
        GeoPoint(latitude: position.latitude, longitude: position.longitude)
      ], currentFirebaseUser.uid);
    });
  }
```
I call the above function in `initState` then use `StaticPositionGeoPoint` to show the icon
but now my problem is that I have two icons that are being tracked at the same time,  my question is how do I remove the default Yellow Man icon (osm default for tracking) or is it better to change the default icon itself, if so how?

**Comment by liodali** [comment]
that's not available , you should waiting little bit until i will make it available

**Comment by liodali** [comment]
I created new type `UserLocationMaker` that will contain `personMarker` and `directionArrowMarker`
to change marker when enabledTracking is activated
for ios side the implementation will be manually so i will do my best to shipped this weekend

**Comment by liodali** [comment]
check the new version `0.11.0`

**Comment by liodali** [comment]
i added like i told new attribute `userLocationMaker` to change personIcon or arrowDirection 
difference between them that personIcon shows only when user is no moving you can make them the same icon 
or change them if  you want it's depend on your use case

**Comment by jesussmile** [comment]
Thank you.. sure no issues I will use the same icon
 Not a problem

**Comment by liodali** [comment]
did you find any problem ! or everything works fine

**Comment by jesussmile** [comment]
> did you find any problem ! or everything works fine

Hey hi! I am really sorry for not replying. I am stuck on background location services since months so forgot about this.. It worked from the day you published it. I have no problems with it. It works like a charm!. Thank you and its so wonderful you've brought this project so far.

**Comment by liodali** [comment]
cool! what's you problem with background location ,it that problem related to plugin,
if you want describe the problem, i will help you to find a solution for it

**Comment by jesussmile** [comment]
It's not related to your plugin,  Well it's actually funny now! As I was cleaning up my codes so I could ask you the question, For some reason I now got it to work.  Now, I regret not asking for your help earlier.  Anyways, I am using the `GeoFire` and `BackgroundLocation` plugins in my `firebase database` to stream my location in foreground and background thru this line of code.
```ruby
 void getLocationLiveUpdates() async {
    await BackgroundLocation.startLocationService();
    backgroundSubscription = BackgroundLocation.getLocationUpdates((location) {
      print(location.latitude);
      print(location.longitude);
      Geofire.setLocation(
            currentFirebaseUser.uid, location.latitude, location.longitude);
      BackgroundLocation.setAndroidNotification(
        title: "Background Location",
        message:
            location.latitude.toString() + " " + location.longitude.toString(),
        icon: "@mipmap/ic_launcher",
      );
    });
  }
```

**Comment by liodali** [comment]
my advice to you, add attribute `distanceFilter` in `startLocationService` to manage update more accurate and put  value > 5 because  gps has measurement error

**Comment by jesussmile** [comment]
> my advice to you, add attribute `distanceFilter` in `startLocationService` to manage update more accurate and put value > 5 because gps has measurement error

Ok. I will do as you say. I dont knw why I removed it. But thanx.
