### ISSUE TITLE
Error with gradle while compiling with version 0.20.0+2

### ISSUE THREAD

**Issue by cbopp-art** [liodali/osm_flutter#159]
When using version 0.20.0+2 of osm_flutter I get an error while compiling.

```
Launching lib/main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...
../../.pub-cache/hosted/pub.dartlang.org/flutter_osm_plugin-0.20.0+2/lib/src/controller/osm/osm_controller.dart:37:22: Error: Too few positional arguments: 1 required, 0 given.
    osmPlatform.close();
```

**Comment by liodali** [comment]
i will make fix for that now

**Comment by liodali** [comment]
did you try `flutter clean && flutter pub get `

**Comment by liodali** [comment]
try to clean the cache because previous version `0.20.0` was pointed on last version of flutter_osm_interface 
and  i fixed in 0.20.0+2 that  point on the version  0.1.0 and not 0.1.1 that will be used in the next version 0.21.0

**Comment by liodali** [comment]
to overcome the problem in pubspec add this line 
```dart
dependency_overrides:
  flutter_osm_interface: ^0.1.0
```
and next the version will be solved

**Comment by liodali** [comment]
try in pubspec.lock to force the version from 0.1.1 to 0.1.0
and add this in pubspec.yaml
```dart
dependency_overrides:
  flutter_osm_interface: ^0.1.0
```
in the next version will point on the right version

**Comment by cbopp-art** [comment]
Hmm, i still get the same error:

```
Warning: You are using these overridden dependencies:
! flutter_osm_interface 0.1.1 (0.2.0 available)
Launching lib/main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...
../../.pub-cache/hosted/pub.dartlang.org/flutter_osm_plugin-0.20.0+2/lib/src/controller/osm/osm_controller.dart:37:22: Error: Too few positional arguments: 1 required, 0 given.
    osmPlatform.close();
                     ^

```

**Comment by liodali** [comment]
try to delete flutter_osm_interface in the folder .pub-cache/hosted/pub.dartlang.org 
and after that run `flutter clean && flutter pub get `

**Comment by liodali** [comment]
try the new version `0.21.0-rc.1`

**Comment by cbopp-art** [comment]
Thank you! The errors are gone.

However, now I have troubles with initializing the map. I used my own map controller that unifies the MapController and the PickerMapController class and it was possible to pass the controller via init() method.

```
 @override
  void init(OSMController osmController) {
    this.osmController = osmController;
    super.init(this.osmController);
  }
```

This is no longer possible because the init() method does not provide an agrument for the controller anymore.
The result is, that I cannot draw positions on the map using my own controller.

Thank you for any advice.

**Comment by cbopp-art** [comment]
Maybe the two controllers MapController and PickerMapController could be unified together since there is only one method missing out in the MapController which is:

```
void setSearchableText(String value) {
    _searchableText.value = value;
}
```

**Comment by liodali** [comment]
can you share with me you custom controller 
and did you try to extend from `PickerMapController` and from now no need to create instance of OsmController 
because it's already initialized by the parent and in `OSMFlutter` widget ,just you use `osmBaseController` directly to acess to  drawRoad or any other method
so you can do this 
```dart
class MyCustomController extends PickerMapController {

Future<RoadInfo> draw(List geoPoints){
 /// this just example
  await osmBaseController.drawRoad(geoPoints.first,geoPoints.last)
}

}
```
if you want to initialize some data 
override init
```dart
@override
  void init() {
    super.init();
    /// put your code here
  }

```

**Comment by cbopp-art** [comment]
This is my custom controller

```
class OSMMapController extends MapController {
  late ValueNotifier<String> _searchableText = ValueNotifier('');

  ValueNotifier<String> get searchableText => _searchableText;

  OSMMapController({
    bool initMapWithUserPosition = true,
    GeoPoint? initPosition,
    BoundingBox? areaLimit = const BoundingBox.world(),
  }) : assert(
    initMapWithUserPosition || initPosition != null,
  ),
  super(
    initMapWithUserPosition: initMapWithUserPosition,
    initPosition: initPosition,
    areaLimit: areaLimit,
  );

  @override
  void init() {
    super.init();
  }

  void dispose() {
    super.dispose();
  }

  void setSearchableText(String value) {
    _searchableText.value = value;
  }
}
```

**Comment by liodali** [comment]
you can try extend directly from `PickerMapController` and add create you own methods and use `osmBaseController` 
to access to the inner method 
but i f want to keep your implementation use as i told you attribute `osmBaseController`

**Comment by cbopp-art** [comment]
Thank you for your advice. But what do you exactly mean with `but if you want to keep your implementation use as i told you attribute osmBaseController`, where should I use this instead?

The error comes after calling:

```
waypoint = await osmMapController.selectPosition(
      icon: MarkerIcon(
        icon: Icon(
          Icons.person_pin_circle,
          color: colorPrimary,
          size: 100
        )
      )
    );
```

Error:
E/flutter ( 8986): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 8986): #0      MethodChannelOSM._capturePng (package:flutter_osm_interface/src/channel/osm_method_channel.dart:366:33)
E/flutter ( 8986): #1      MethodChannelOSM.pickLocation (package:flutter_osm_interface/src/channel/osm_method_channel.dart:277:22)
E/flutter ( 8986): #2      MobileOSMController.selectPosition.<anonymous closure> (package:flutter_osm_plugin/src/controller/osm/osm_controller.dart:430:40)
E/flutter ( 8986): #3      MobileOSMController.selectPosition.<anonymous closure> (package:flutter_osm_plugin/src/controller/osm/osm_controller.dart:429:14)
E/flutter ( 8986): #4      new Future.delayed.<anonymous closure> (dart:async/future.dart:315:39)
...

**Comment by liodali** [comment]
i mean that `osmBaseController`  will give you access to the inner controller if you want to make custom behaviour
for error, it always happen or not ?

**Comment by cbopp-art** [comment]
I tried to call the methods `selectPosition()` and `drawRoad()` by using the osmBaseController e.g.  like `OSMMapController.osmBaseController.selectPosition()`, But the error is always the same. Could it be that due to my custom controller which is applied to OSMFlutter instance the context is missing?

```
OSMFlutter(
      controller: osmMapController,
      ...
)
```

**Comment by liodali** [comment]
that problem is relate dto the widget that responsible to get draw icon or image before send it to platforview 
i will make more test to fix it soon

**Comment by cbopp-art** [comment]
ok, thanks a lot! I really appreciate your great support.

**Comment by cbopp-art** [comment]
I just tried without my custom controller and used only the MapController from the osm_flutter plugin. Same error.

**Comment by liodali** [comment]
:cry: 
can you provide me small example

**Comment by cbopp-art** [comment]
Hmm, hard to provide such. I try to give you my context as best as possible.



1. In my stateful widget, I create an instance of `OSMFlutter` while on initState I create an instance of that controller which is then passed to `OSMFlutter inside method `_getMap()`.

```
@override
void initState() {
    super.initState();
    osmMapController = OSMMapController(
      initMapWithUserPosition: true,
      initPosition: GeoPoint(
        latitude: defaultMapPosition[0],
        longitude: defaultMapPosition[1]
      )
    );
  }
...
getMap() {
  return OSMFlutter(
      controller: osmMapController,
      initZoom: 12,
      mapIsLoading: Center(child: CircularProgressIndicator()),
      trackMyPosition: true,
      markerOption: MarkerOption(
        defaultMarker: MarkerIcon(icon: Icon(null)),
      ) // Default no icon
   );
}
```

2. In another method called `_addWayPoint()` I call the method `osmMapController.selectPosition(icon: markerIcon)`, here is where the error is thrown. It doesn't matter if `osmMapController` is an instance of my custom controller if I use the original MapController of the plugin.

```
_addWayPoint([GeoPoint? geoPoint]) async {
    late GeoPoint waypoint;

    if (geoPoint != null) {
      waypoint = geoPoint;
    }
    else waypoint = await osmMapController.selectPosition(
      icon: MarkerIcon(
        icon: Icon(
          Icons.person_pin_circle,
          color: colorPrimary,
          size: 100
        )
      )
    );
    waypoints.add(waypoint);
    _drawRoad();
    _enableRemoveLastTrackButton();
  }
```

**Comment by liodali** [comment]
try the new version `0.21.0-rc.2` 
run flutter clean && flutter pub get before you build

**Comment by cbopp-art** [comment]
The error is now different:
```
E/flutter (26109): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: Error to draw you custom icon
E/flutter (26109): #0      MethodChannelOSM._capturePng (package:flutter_osm_interface/src/channel/osm_method_channel.dart:366:7)
E/flutter (26109): #1      MethodChannelOSM.pickLocation (package:flutter_osm_interface/src/channel/osm_method_channel.dart:277:22)
E/flutter (26109): #2      MobileOSMController.selectPosition.<anonymous closure> (package:flutter_osm_plugin/src/controller/osm/osm_controller.dart:427:40)
E/flutter (26109): #3      MobileOSMController.selectPosition.<anonymous closure> (package:flutter_osm_plugin/src/controller/osm/osm_controller.dart:426:64)
E/flutter (26109): #4      new Future.delayed.<anonymous closure> (dart:async/future.dart:315:39)
E/flutter (26109): #5      _rootRun (dart:async/zone.dart:1420:47)
E/flutter (26109): #6      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (26109): #7      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (26109): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (26109): #9      _rootRun (dart:async/zone.dart:1428:13)
E/flutter (26109): #10     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (26109): #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260:23)
E/flutter (26109): #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (26109): #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter (26109): #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter (26109): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:187:12)
E/flutter (26109): 
```

**Comment by liodali** [comment]
is still the same i just added test if the context of globalkey of the widget that responsible of drawing the icon is null or not 
but it's weird
when you call this medthod `_addWayPoint` ?

**Comment by cbopp-art** [comment]
Yes, it is strange. Yes, error occurs when I call `_addWayPoint` on line `else waypoint = await osmMapController.selectPosition()`

**Comment by liodali** [comment]
if you want can we collaborate in meeting with zoom or google meet to see with you the problem
if you accept that we can arrange that with email

**Comment by cbopp-art** [comment]
Hi liodali
It seems to be even more strange. If I do a complete restart the app with hot restart, the error is thrown. After a hot reload of the application, the map is loaded again, the error does not occur anymore and `osmMapController.selectPosition()` works fine. However, only after a hot reload it works properly :(
`globalKey.currentContext` is null:
`MethodChannelOSM._capturePng (package:flutter_osm_interface/src/channel/osm_method_channel.dart:366:7)`

I also tested with the latest stable branch of flutter also.

Are you able to reproduce the same error if you...?
1. create a simple instance of OSMFlutter
2. create a simple controller like below
```
@override
  void initState() {
    super.initState();
    osmMapController = OSMMapController();
  }
```
3. then call `osmMapController.selectPosition(icon: <your icon>)` when map is ready (onMapIsReady)

**Comment by liodali** [comment]
make the create the same context as yours but error doesn't want to appear 
if you want we can see it more together in the same time as last meeting, i have small idea maybe it will help

**Comment by cbopp-art** [comment]
Hi
Yes, let’s do that. Just ping me when you’ll be available.
