### ISSUE TITLE
[Feature request] add pop up on marker icon

### ISSUE THREAD

**Issue by jesussmile** [liodali/osm_flutter#160]
Is it possible to add pop up on marker icons . I have marker icons as cars, bike or runners. Can we add a pop up icon where I can show the speed, time etc..?
![Screenshot_20210918-063509_Chrome](https://user-images.githubusercontent.com/11044978/133866520-04c821f8-1f17-438b-97b7-0c1a1a62a524.jpg)

**Comment by liodali** [comment]
yeah, we can add pop up it's previously implement with showen location address, and after that i removed 
i will returned back with your request

**Comment by liodali** [comment]
for this feature it will be available for static point for now because it's easy to implement 
and after that i will add it to all markers

**Comment by jesussmile** [comment]
Okay! Thanx. I’ll wait.

**Comment by jesussmile** [comment]
hi liodali! How have you been?  any update on this?

**Comment by liodali** [comment]
Hi,
I'm sorry i was trying to fix rebuild issue in android side, I will start look at it after this weekend, 
But bad news maybe this feature will be only available on android/web
And i'm looking for solution that will give the developers posibility to make customisable popup not just text
but i will start with giving the minimum, sorry for the late but after 0.26.0 will be available

**Comment by jesussmile** [comment]
any update on this ?

**Comment by liodali** [comment]
I'm trying to show popup widget but i'm facing problem in iOS side 
I will back to this feature when I will release the web sorry for all this wait
