### ISSUE TITLE
Error: Too few positional arguments: 1 required, 0 given.

### ISSUE THREAD

**Issue by HamiidrezaRamezani** [liodali/osm_flutter#164]
Invalid depfile: C:\code\mylab724\.dart_tool\flutter_build\b4cfad511dd1c26d78503a84dbd95e78\kernel_snapshot.d
Invalid depfile: C:\code\mylab724\.dart_tool\flutter_build\b4cfad511dd1c26d78503a84dbd95e78\kernel_snapshot.d
/C:/src/flutter_windows_2.5.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_osm_plugin-0.20.0+2/lib/src/controller/osm/osm_controller.dart:37:22: Error: Too few positional arguments: 1 required, 0 given.
    osmPlatform.close();
                     ^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter_windows_2.5.1-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1005

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter_windows_2.5.1-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 37s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by liodali** [comment]
use `0.21.0-rc.2` i will publish stable version later

**Comment by liodali** [comment]
i published new version `0.21.0`
