### ISSUE TITLE
Error: No named parameter with the name 'stepZoom'.

### ISSUE THREAD

**Issue by HamiidrezaRamezani** [liodali/osm_flutter#168]
/C:/src/flutter_windows_2.5.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_osm_plugin-0.21.0/lib/src/interface_osm/base_osm_platform.dart:47:7: Error: No named parameter with the name 'stepZoom'.
      stepZoom: stepZoom,
      ^^^^^^^^
/C:/src/flutter_windows_2.5.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_osm_plugin-0.21.0/lib/src/widgets/platform/web_osm_widget.dart:4:8: Context: Found this candidate, but the arguments don't match.
Widget getWidget({
       ^^^^^^^^^
Failed to compile application.

**Comment by liodali** [comment]
the version `0.21.0` doesn't support the web 
the web support for now is under-dev

**Comment by mnn-softjoy** [comment]
Now I have the same problem on 0.30.0 on Web on MAC

**Comment by liodali** [comment]
the web version for now is not support,it's still on dev, i will try to publish alpha version next month

**Comment by Charlie-23** [comment]
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_osm_plugin-0.34.1+1/lib/src/interface_osm/base_osm_platform.dart:47:9: Error: No named parameter with the name 'stepZoom'.
        stepZoom: stepZoom,
        ^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_osm_plugin-0.34.1+1/lib/src/widgets/platform/web_osm_widget.dart:4:8: Context: Found this candidate, but the arguments don't match.
Widget getWidget({
       ^^^^^^^^^

**Comment by Charlie-23** [comment]
How do I resolve this?

**Comment by liodali** [comment]
you need to wait until i publish version that support web or use web branch

**Comment by PawelSzymanski89** [comment]
what about web?

**Comment by liodali** [comment]
check our last version `0.50.0` now supporting web
