### ISSUE TITLE
Cannot use library on Flutter 2.5.3

### ISSUE THREAD

**Issue by gcsaba2** [liodali/osm_flutter#183]
Using latest Flutter SDK version 2.5.3.

I copy-pasted the example from readme.md and created an OSMFlutter.

It failed with the following error:

   > non-abstract class MobileOSMController is missing implementations for these members

Using 0.22.3

When I tried the latest version 0.25.0-rc.3 I got the following error:

   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
     The number of method references in a .dex file cannot exceed 64K.

**Comment by liodali** [comment]
in the file build.gralde inside android/app 
add
```gradle 
defaultConfig {
 ...
 /// add this line 
 multiDexEnabled true
 ...
}

dependencies {
    ....
    /// add those lines also
    def multidex_version = "2.0.1"
    implementation "androidx.multidex:multidex:$multidex_version"
}

```
add run 
`flutter clean && flutter pub get`

**Comment by gcsaba2** [comment]
Thank you, this solved the issue for me.
