### ISSUE TITLE
Map rebuild issue

### ISSUE THREAD

**Issue by jesussmile** [liodali/osm_flutter#188]
Hi! There is already an issue open regarding this but I would like to present the issue with an example here,
After the latest release, there is in fact a reload issue that causes a lot of other plugins like geofire, background location, etc to fail.
I have will try to recreate the issue with your source code.
In your `home_example.dart` file I added a Positioned widget that will just change the color of the button. If I click it once the whole `osmplugin` will restart causing other plugins to detach as well.  Could you suggest what to do in this case? I do need to call `setState`.
```ruby
class _MainExampleState extends State<MainExample> {
  Color buttonColor = Colors.black;
..........
 body: OrientationBuilder(
        builder: (ctx, orientation) {
          return Container(
            child: Stack(
              children: [
                OSMFlutter(...)
               Positioned(
                    top: 180,
                    left: 0,
                    right: 0,
                    child: RaisedButton(
                      color: buttonColor,
                      onPressed: () {
                        setState(() {
                          buttonColor = Colors.red;
                        });
                      },
                    )),
```

**Comment by liodali** [comment]
avoid using setState and in last rc that problem solved by saving map state before it restart 
i make that solution for android because context in native android view dispear
use notifiervalue that will cause rebuild on the tree
i will try to improve that
