### ISSUE TITLE
The name 'GeoPoint' is defined in the libraries

### ISSUE THREAD

**Issue by Isaac37** [liodali/osm_flutter#194]
The name 'GeoPoint' is defined in the libraries 'package:cloud_firestore_platform_interface/src/geo_point.dart' and 'package:flutter_osm_interface/src/types/geo_point.dart'.

**Comment by Isaac37** [comment]
how do i solve this issues

**Comment by Isaac37** [comment]
found a solution 
 i imported: import 'package:flutter_osm_plugin/flutter_osm_plugin.dart' as ph(or any word);
so whenever i use Geopoint i use it like ph.Geopoint

**Comment by liodali** [comment]
you can use keyword  `as` when you import `flutter_osm_plugin` for example  

```dart
 import 'package:flutter_osm_plugin/flutter_osm_plugin.dart'  as osm
```
