### ISSUE TITLE
Limitations of requests

### ISSUE THREAD

**Issue by renehw** [liodali/osm_flutter#198]
Hi, your package is very good, was very helped me, congratulations!

I have an question, whats the limitations of requests your package does have?
How many requests I can will do per day and houer? Exist an limit for this?

**Comment by liodali** [comment]
the limitation only for routing api, try to not make lot of request in sec ( max 10/sec )
because it's open source server

**Comment by renehw** [comment]
Shure, I undestand you, but I can will do 50 thousand requests per day in API for routing, for example ?
I don't will  have an limitation in this situation?

**Comment by liodali** [comment]
i don't recommand you to do that
if you want you can make your own server ( https://github.com/Project-OSRM/osrm-backend )
or using other existing api like mapbox routing  or mapquest api
but i think that number only reach if you tring to do turn by turn navigation except that 
you can try

**Comment by renehw** [comment]
Thanks man, you helped me a lot!
