### ISSUE TITLE
ClickListener on Marker

### ISSUE THREAD

**Issue by gcsaba2** [liodali/osm_flutter#199]
The readme.md lists that the following feature is supported:

* ClickListener on Marker (Android/iOS)

I didn't actually find a way how to add a listener to a marker. The best I could find was:

```dart
_mapController.listenerMapSingleTapping.addListener(() async {
      if (_mapController.listenerMapSingleTapping.value != null) {
        final GeoPoint lastTap = _mapController.listenerMapSingleTapping.value!;

        Marker? tappedMarker;
        for (var marker in _visibleMarkers.value) {
          var distanceKm = _calculateDistance(lastTap.latitude, lastTap.longitude, marker.lat, marker.lon);
          if (distanceKm <= 0.01) { // less than 10 meters
            tappedMarker = marker;
            break;
          }
        }
```

Unfortunately this doesn't work well. If I zoom out, then it's difficult to tap on the marker because the distance between the marker and the tap can be 100 meters or more.

Is there a better way to support a click listener on a tap?

**Comment by gcsaba2** [comment]
I also think that there is "something" going on here. When I click on a marker, sometimes this is printed in the logs:

```
W/.nyomtass_te_i( 7875): Accessing hidden method Ljava/lang/invoke/MethodHandles$Lookup;-><init>(Ljava/lang/Class;I)V (greylist, reflection, allowed)
W/.nyomtass_te_i( 7875): Accessing hidden field Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe; (greylist, reflection, allowed)
W/.nyomtass_te_i( 7875): Accessing hidden method Lsun/misc/Unsafe;->allocateInstance(Ljava/lang/Class;)Ljava/lang/Object; (greylist, reflection, allowed)
```

**Comment by liodali** [comment]
that listener not for marker click marker , it used to get map click
if you want to get marker click you need to add 
in OSMFlutter `onGeoPointClicked` you will receive geopoint of that marker

**Comment by gcsaba2** [comment]
Thank you, that worked!
