### ISSUE TITLE
 getting an array of route points

### ISSUE THREAD

**Issue by holyboom1** [liodali/osm_flutter#200]
is it possible somehow on the flutter side to get the points of which the route consists?

**Comment by liodali** [comment]
for now, draw road is just show the road with get road information like distance and duration 
but i will add that if you need it

**Comment by holyboom1** [comment]
> for now, draw road is just show the road with get road information like distance and duration but i will add that if you need it

yes, it would be cool to add this feature. thanks!

**Comment by liodali** [comment]
check the new version, now you can get routes point when you call drawRoad
just you need to check if `route` is empty or not
or you facing any problemon that ,reopen this issue
