### ISSUE TITLE
How the marker changes when click

### ISSUE THREAD

**Issue by mor7348** [liodali/osm_flutter#202]
I want to change the marker when I click on it.
Change color, change size, etc.
Do you have any good ideas?

**Comment by liodali** [comment]
you should remove it and re-insert with addMarker 
maybe i will add in the future changeMarker that will add marker if not exist and if exist it will change the icon

**Comment by gcsaba2** [comment]
When I remove and re-insert a marker, sometimes on the map I see it disappear for 1 second. Probably the map takes time to repaint. It would look nicer if there was a `changeMarker` method. Thanks

**Comment by liodali** [comment]
can you provide small sample ?
did you put that logic inside setState ?

**Comment by mor7348** [comment]
@gcsaba2 
thank you.
I tried to remove the marker and add a static marker, but there was a time difference.
It would be nice if the markers switch smoothly :)

**Comment by mor7348** [comment]
@liodali 
I wrote it simply as follows.

---
onGeoPointClicked: (geoPoint) async {
	await controller.removeMarker(GeoPoint(latitude: ~~~["latitude"]!, longitude: ~~~["longitude"]!));
	await controller.setMarkerOfStaticPoint(~~~
---
![marker_switch_sample](https://user-images.githubusercontent.com/38882637/147053446-89f1ac83-cb4a-487b-a267-305db368315a.gif)

thank you.

**Comment by liodali** [comment]
it will be available in next version

**Comment by mor7348** [comment]
thank you.
 I'm looking forward.

**Comment by liodali** [comment]
i will start working on this,
i have question do you prefer to add new method called `changeIconMarker` that take geoPoint and new Icon
or 
changeMarker that will get geoPoint (current that you want to change ) and  new geoPoint or new icon marker

**Comment by mor7348** [comment]
I want you to change the icon (size, color) without changing geoPoint.
This is because we want to visualize that the marker is selected.

**Comment by liodali** [comment]
this feature will ready in this weekend inshallah , I will publish new version

**Comment by mor7348** [comment]
thank you! I will try using it.
