### ISSUE TITLE
zoom map to bounding box

### ISSUE THREAD

**Issue by liodali** [liodali/osm_flutter#203]
- [x] Add capability to change the zoom (In/Out) of the map by entering bounding box 
- [x] Add new attribute `zoomInto` in drawRoad and drawRoadManually  to fit the zoomlevel in the map with length of the road (In/Out) (default : true)

**Comment by liodali** [comment]
i'm planned to be released in 0.28

**Comment by renehw** [comment]
Fine, in January?

**Comment by liodali** [comment]
i will start working on this feature tomorrow,
maybe it will be ready next week

**Comment by renehw** [comment]
Thanks dude! I'm very happy with your package, this one will go help me in next year, good job and happy new year!

**Comment by liodali** [comment]
- [x] Add capability to change the zoom (In/Out) of the map by entering bounding box 
- [ ] Add new attribute `zoomInto` in drawRoad and drawRoadManually  to fit the zoomlevel in the map with length of the road (In/Out) (default : true)

**Comment by liodali** [comment]
- [x] create new method in map_controller `zoomToBoundingBox`  to adjust the zoom (In/Out) of the map by entering bounding box and paddingInPixel
- [x] Add new attribute `zoomInto` in drawRoad and drawRoadManually  to fit the zoomlevel in the map with length of the road (In/Out) (default : true)

**Comment by liodali** [comment]
i published new version `0.28.0+1`
don't use 0.28.0 because i forget to update osm_interface package

**Comment by renehw** [comment]
What's up dude, I implemented this new attribute and it's working very well, thanks for your job, this helped me very. And congratulations for the package, it is evolving very well.
