### ISSUE TITLE
GeoPoint needs an equals() method

### ISSUE THREAD

**Issue by gcsaba2** [liodali/osm_flutter#207]
Test case:
```
print(GeoPoint(latitude: 15.031, longitude: 44.12073) == GeoPoint(latitude: 15.031, longitude: 44.12073));
```

This returns `false` even though they''re the same coordinate.

**Comment by gcsaba2** [comment]
[ISSUE_207.patch.txt](https://github.com/liodali/osm_flutter/files/7780114/ISSUE_207.patch.txt)

**Comment by liodali** [comment]
for now you can compare their string for now,
i will add == operation, i will make new release for that

**Comment by liodali** [comment]
check the new version 0.27.0+1

**Comment by gcsaba2** [comment]
Thank you
