### ISSUE TITLE
How to add loading to'CustomPickerLocation'.

### ISSUE THREAD

**Issue by mor7348** [liodali/osm_flutter#218]
Hi,

"/example/lib/src/simple_example.dart"

Refer to this example
I'm thinking of using'CustomPickerLocation'.

I'd like to add loading until  zoom in to init zoom. Is there a good way?

Thank you.

**Comment by liodali** [comment]
I will add loading widget for it, it will be ready tomorrow if you want to wait.
 if you want workaround , you can use mapIsReady callback in OSMFlutter to get notified when map is ready 
and for example add widget on top of map and hide that widget when value is true

**Comment by mor7348** [comment]
Thank you. 
Im waiting for loading widget:)

**Comment by mor7348** [comment]
Hi,
After searching using CustomPickerLocation,
if I move the map, the pin also moves. Is there a way to fix it?

**Comment by liodali** [comment]
can you provide me small demo to understand more the problem ?

**Comment by liodali** [comment]
I make small modification on `CustomPickerLocation` 
I put all config attribute for OSMFlutter inside `CustomPickerLocationConfig`
i will publish new version in minutes

**Comment by liodali** [comment]
check the new version `0.29.1`

**Comment by mor7348** [comment]
Thank you.
I have updated from version 0.28.2 to 0.29.1.

I now get the following error when using version 0.29.0 & 0.29.1. (iOS simulator)

Please let me know if there are any points that need to be changed, such as permissions, when upgrading the version.

[VERBOSE-2: ui_dart_state.cc (209)] Unhandled Exception: Exception: we cannot continue showing the map without grant gps permission
# 0 MobileOSMController.initMap (package: flutter_osm_plugin / src / controller / osm / osm_controller.dart: 219: 9)
<asynchronous suspension>
# 1 BaseMapController.init. <anonymous closure> (package: flutter_osm_interface / src / map_controller / base_map_controller.dart: 50: 7)
<asynchronous suspension>

I am using'CustomController' and setting 'initMapWithUserPosition' to true.

At the same time, I received the GeoPoint of'CustomController.myLocation'.

**Comment by liodali** [comment]
i will make quick fix  for it , after 0.29+ I removed location package and i started managing permission inside the library 
I forget to put that code inside if condition to check platform because request permission in iOS not like Android 
I will make quick fix for it ,Sorry

**Comment by mor7348** [comment]
Thank you.
I am very grateful for your work.

**Comment by liodali** [comment]
check the new version `0.29.1+1`

**Comment by mor7348** [comment]
The error has been resolved.
thank you.

**Comment by liodali** [comment]
yeah,I will make quick fix for it

**Comment by liodali** [comment]
check the new version `0.29.1+2`

**Comment by mor7348** [comment]
Thank you so match
