### ISSUE TITLE
Map tilt or 3D view

### ISSUE THREAD

**Issue by Farrukh1198** [liodali/osm_flutter#220]
Is there any parameter to set tilt in degrees or enable 3D view like Google Maps Navigation system or any other navigation system?

**Comment by liodali** [comment]
when i will add vector tile , it will be add it but not like google map
but for now the map only support raster tile based on osm data

**Comment by Farrukh1198** [comment]
Got it. Thank you.

вс, 30 янв. 2022 г., 11:25 PM hamza mohamed ali ***@***.***>:
