### ISSUE TITLE
Get LatLong with street address and number

### ISSUE THREAD

**Issue by renehw** [liodali/osm_flutter#225]
How to get Latitude and Longitude using street address and house number?

i.g.: Address: Rua Doutor Aluízio França - 709 - Bigorrilho, Curitiba - PR

return LatLong(-25.4254644, -49.3083217)

**Comment by suvindran3** [comment]
You can use this api for that <link>https://nominatim.org/release-docs/develop/api/Search/</link>

**Comment by liodali** [comment]
use can use this library :
https://pub.dev/packages/osm_nominatim
to convert adr to LatLng

**Comment by renehw** [comment]
Thanks @suvindran3 and @liodali , I will verify this options.
