### ISSUE TITLE
Map is always loading when controller is initialized with initMapWithUserPosition as true 

### ISSUE THREAD

**Issue by praveen-gm** [liodali/osm_flutter#232]
Hi,
When the controller is initialized with initMapWithUserPosition as true, the map keeps loading

```
 final MapController _mapController = MapController(
    initMapWithUserPosition: true,
  );
```

Steps to reproduce on the latest  `flutter_osm_plugin: ^0.30.1+2`

on the example app, change controller initialization initMapWithUserPosition to true.

Tested on Samsung A10s (Android 11) and iPhone SE (iOS 14.7.1),
Although it worked on the Android Emulator on the second launch, the first launch gave these errors while the permission dialog popped up

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(PermissionHandler.PermissionManager, A request for permissions is already running, please wait for it to finish before doing another request (note that you can request multiple permissions at the same time)., null, null)
E/flutter (32151): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (32151): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter (32151): <asynchronous suspension>
E/flutter (32151): #2      MethodChannelPermissionHandler.requestPermissions (package:permission_handler_platform_interface/src/method_channel/method_channel_permission_handler.dart:71:9)
E/flutter (32151): <asynchronous suspension>
E/flutter (32151): #3      PermissionActions.request (package:permission_handler/permission_handler.dart:44:31)
E/flutter (32151): <asynchronous suspension>
E/flutter (32151): #4      MobileOsmFlutterState.requestPermission (package:flutter_osm_plugin/src/widgets/mobile_osm_flutter.dart:220:30)
E/flutter (32151): <asynchronous suspension>
E/flutter (32151): #5      MobileOSMController.initMap (package:flutter_osm_plugin/src/controller/osm/osm_controller.dart:209:24)
E/flutter (32151): <asynchronous suspension>
E/flutter (32151): #6      BaseMapController.init.<anonymous closure> (package:flutter_osm_interface/src/map_controller/base_map_controller.dart:50:7)
E/flutter (32151): <asynchronous suspension>

Many thanks for creating this wonderful package, Please do let me know if you want me to share any further info/logs.

**Comment by liodali** [comment]
in iOS doesn't show you popup for permission ? or it shows and even if you grant the permission the map doesn't show
because for android , yes i confirm that their is a problem and already fixed i will make commit and it will available with new release 0.31.0

**Comment by praveen-gm** [comment]
I had it just verified, iOS didn't show the permission popup

**Comment by liodali** [comment]
for iOS, did you check that location is on ?

**Comment by praveen-gm** [comment]
yes, location services enabled

**Comment by praveen-gm** [comment]
iOS permission was already granted, my bad
restarted iPhone and the map worked on the iPhone

I got it working on Android, Now I can be more precise on reproducing this bug on Android.
There's this Google's [FusedLocationProviderClient](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderClient) that I've used in a different native app. When you try to get the `lastLocation` sometimes it doesn't return any result due to various reasons such as no `lastLocation` available or turning off/on the GPS clears cache etc, but the `currentLocation` works.

So, I opened to google maps so it would cache the `lastLocation` and then opened the sample app, then the maps loaded, other wise it kept loading

**Comment by liodali** [comment]
for android like i told you i fix that bug, i will publish new version this weekend 
that contain this fix and other feature

**Comment by praveen-gm** [comment]
Thank you for the quick fix.

**Comment by liodali** [comment]
check the new version `0.31.0`

**Comment by praveen-gm** [comment]
Thank you very much, this bug has been resolved. I'll close this issue
