### ISSUE TITLE
Permissions broken for iOS

### ISSUE THREAD

**Issue by KatrinaAS** [liodali/osm_flutter#245]
It seems currentLocation and anything based on needing location is currently broken in iOS, as the function requestPermission() only functions if current platform is an android, otherwise it just returns false. Is there any time frame on this being fixed?

**Comment by liodali** [comment]
are you using emulator or real device for iOS ?

**Comment by liodali** [comment]
did you have those in your info.plist ( ios folder )
 <key>NSLocationWhenInUseUsageDescription</key>
	<string>any text you want</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>any text you want</string>

**Comment by KatrinaAS** [comment]
I do have them yes, and I have tried both emulator and real device. Neither should matter as the problem seems to be here

https://github.com/liodali/osm_flutter/blob/bb4dd7af211f699c3a66c9ba76a7612adf7cc910/lib/src/widgets/mobile_osm_flutter.dart#L201

If platform is not android, it returns false, which means https://github.com/liodali/osm_flutter/blob/1cc591faa575900cc3b3ed609cc21720b8c158ba/lib/src/controller/osm/osm_controller.dart#L390

will ALWAYS return the exception no matter what on ios

**Comment by liodali** [comment]
yes requestPermission not working in iOS, because i manage the permission internally
so i will fix that problem, i will make hotfix for it tomorrow sorry
