### ISSUE TITLE
How disable the loading in MarkerIcon

### ISSUE THREAD

**Issue by renehw** [liodali/osm_flutter#248]
How disable the loading when I tap in the MarkerIcon in RoadConfiguration? 

![image](https://user-images.githubusercontent.com/58603535/162067463-7f721360-217f-47f5-8b03-6601045abb8e.png)

**Comment by liodali** [comment]
you don't to show the popup at all or you want to make custom behaviour ?

**Comment by renehw** [comment]
I tried to put this, but it still continues.

**Comment by liodali** [comment]
i will fix that error i will publish hotfix for it

**Comment by liodali** [comment]
check the new version `0.33.0+2`
