### ISSUE TITLE
App close in release mode

### ISSUE THREAD

**Issue by h1amza** [liodali/osm_flutter#255]
when we search for address with the search bar to pick an address in CustomPickerLocation and go back to main home map the application crash (map freeze 1s) and close (only in release mode)

**Comment by liodali** [comment]
do you have any log error for that ?

**Comment by h1amza** [comment]
E/AndroidRuntime(13804): FATAL EXCEPTION: DefaultDispatcher-worker-1
E/AndroidRuntime(13804): Process: com.jolitaxi.jolitaxi_client, PID: 13804
E/AndroidRuntime(13804): java.lang.NullPointerException: folderMarkers.items must not be null
E/AndroidRuntime(13804):        at hamza.dali.flutter_osm_plugin.FlutterOsmView$j$a.invokeSuspend(Unknown Source:22)
E/AndroidRuntime(13804):        at kotlin.coroutines.jvm.internal.a.resumeWith(Unknown Source:11)
E/AndroidRuntime(13804):        at d8.x0.run(Unknown Source:129)
E/AndroidRuntime(13804):        at android.os.Handler.handleCallback(Handler.java:790)
E/AndroidRuntime(13804):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(13804):        at android.os.Looper.loop(Looper.java:166)
E/AndroidRuntime(13804):        at android.app.ActivityThread.main(ActivityThread.java:6518)
E/AndroidRuntime(13804):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13804):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime(13804):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by liodali** [comment]
can you show me part of the code that responsible for the back button

**Comment by h1amza** [comment]
![Capture](https://user-images.githubusercontent.com/32615603/166164716-4cdd02b5-a90f-4d22-b0c7-bd1dbd61c987.PNG)

**Comment by h1amza** [comment]
i don't have a problem in the back button.

**Comment by h1amza** [comment]
i have a home screen with OSMFlutter widget and an icon to go to search screen(just like your example) when i have a text widget to see address picked and an icon to go to CustomPickerLocation (same code in your example repos) and when i go back(to search page) i can see the address but when i go back more to the home the application close (only in the release mode)

**Comment by liodali** [comment]
and when you back to the home page did you make any action related to the search address ?

**Comment by h1amza** [comment]
no but when i use search the app crash in back and when i only pick an address without search it's work

**Comment by liodali** [comment]
when you search for specific location, you show list and when you click on one of items 
you back to home or you have other behaviour ?

**Comment by h1amza** [comment]
i go back to search screen to see latitude and longitude then i go back to home screen (OSMFlutter widget)

**Comment by liodali** [comment]
can you show me the peace of code that responsible from search page to home page ?

**Comment by h1amza** [comment]
![Capture](https://user-images.githubusercontent.com/32615603/166231096-8f123a05-db29-40bf-a91d-80e788ab4300.PNG)

**Comment by h1amza** [comment]
i think when i search for an address,
map controller in home page is disposed or resumed,
so when i try to draw road the app crash

**Comment by liodali** [comment]
yeah, do that when you already in that widget after returning to the home page 
I mean when you have searched address return it to home page and after that make the draw

**Comment by liodali** [comment]
pass the controlle of the  OSMFlutter only to nested widget (exist with map )

**Comment by liodali** [comment]
you can make the search part in the same map, you don't need to make it in another widget

**Comment by h1amza** [comment]
the problem still happen however i do that and i don't pick an address i only try to search to see the suggestion list and go back (without draw line) the map is freeze (only in release mode)
![68844d35-5748-4b02-a6d2-e10c9728e151](https://user-images.githubusercontent.com/32615603/166238655-b5fecf6d-6982-406f-b476-cbc52b0a604f.jpg)
d

**Comment by liodali** [comment]
that problem related to map context in native view 
if you have setState in your widget try to avoid calling that to prevent rebuild of the widget

**Comment by h1amza** [comment]
![Capture](https://user-images.githubusercontent.com/32615603/166240319-df294f25-fccf-4d89-8516-cb4474d8f17f.PNG)
i only have this setState (and it's your code in example repo)

**Comment by h1amza** [comment]
when i press in TextField a bunch of error throw but still the application work in debug mode

![Capture](https://user-images.githubusercontent.com/32615603/166243843-d264822a-ca0d-492f-8d70-8de9d7b8594f.PNG)
![Capture1](https://user-images.githubusercontent.com/32615603/166243845-4d1821cc-8876-4d4c-b964-150aa43867fa.PNG)
![Capture2](https://user-images.githubusercontent.com/32615603/166243847-a9b3e3d5-bd25-4789-acb2-7b46eb0790ef.PNG)

**Comment by h1amza** [comment]
press in TextField cause this error and when i go back to home screen (without any search only pressing to see keyboard) the map is freezed
![Capture](https://user-images.githubusercontent.com/32615603/166312691-6daae16a-3d01-4ffd-98d2-e32bb9c7226a.PNG)

**Comment by liodali** [comment]
in the scaffold of Home page put 
  ```
      resizeToAvoidBottomInset: false,

**Comment by h1amza** [comment]
so my error is forgetting a simple line of code.
I really thank you for the helpful and quick response
