### ISSUE TITLE
error with the new version of flutter (3.0.0) 

### ISSUE THREAD

**Issue by h1amza** [liodali/osm_flutter#259]
we cannot run the app with the latest version of flutter 3.0.0

error :
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.32.2\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\FlutterOsmPlugin.kt: (59, 63): Smart cast to 'Activity' is impossible, because 'register.activity()' is a complex expression
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.32.2\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\FlutterOsmPlugin.kt: (76, 13): Smart cast to 'OsmFactory' is impossible, because 'factory' is a mutable property that could have been changed by this time
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.32.2\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\OsmFactory.kt: (14, 6): Class 'OsmFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.32.2\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\OsmFactory.kt: (21, 5): 'create' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_osm_plugin:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

**Comment by liodali** [comment]
you updated to Flutter 3 ?

**Comment by h1amza** [comment]
yes i just updated to flutter 3, but many packages does not support the upgrade

**Comment by liodali** [comment]
i will publish new version today

**Comment by noahvelasco** [comment]
how has the new version been coming? I tried to run example but I still get error

**Comment by liodali** [comment]
i will publish new version in 2h hours 
sorry for being late

**Comment by liodali** [comment]
check the new version `0.34.0`

**Comment by ignace-shoeib** [comment]
i cant build with the new version

**Comment by liodali** [comment]
what error you have ?

**Comment by ignace-shoeib** [comment]
the one from issue #261
