### ISSUE TITLE
Problem on iOS with controller.currentLocation()

### ISSUE THREAD

**Issue by Alisofin** [liodali/osm_flutter#274]
Hello,
controller.currentLocation() throws an exception on iOS (location permission not granted) although I have put the right key in Info.plist ( <key>NSLocationWhenInUseUsageDescription</key> <string>App needs access to location</string>). Could you please help ?
thanks.

**Comment by liodali** [comment]
try to add this also
``` NSLocationAlwaysUsageDescription ``

**Comment by Alisofin** [comment]
Thanks but it doesn't work either.

**Comment by liodali** [comment]
are you using simulator and real device ?

**Comment by Alisofin** [comment]
on both of them, same problem.

**Comment by liodali** [comment]
try to delete the app and retry again

**Comment by Alisofin** [comment]
same story again. I get the following trace with iOS real device: 
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: Exception: Location permission not granted
#0      MobileOSMController.currentLocation (package:flutter_osm_plugin/src/controller/osm/osm_controller.dart:399:7)
<asynchronous suspension>
#1      MapController.currentLocation (package:flutter_osm_plugin/src/controller/map_controller.dart:153:5)
<asynchronous suspension>

**Comment by liodali** [comment]
which version are you using ?

**Comment by Alisofin** [comment]
ooups ! switched to latest version and now it works fine ! Many thanks !
