### ISSUE TITLE
Because flutter_osm_plugin >=0.29.0 depends on permission_handler ^8.3.0 and biopower depends on permission_handler ^10.0.0, 

### ISSUE THREAD

**Issue by Mark1944** [liodali/osm_flutter#277]
Because flutter_osm_plugin >=0.29.0 depends on permission_handler ^8.3.0 and biopower depends on permission_handler ^10.0.0, flutter_osm_plugin >=0.29.0 is forbidden.
So, because biopower depends on flutter_osm_plugin ^0.34.1+2, version solving failed.
pub get failed (1; So, because biopower depends on flutter_osm_plugin ^0.34.1+2, version solving failed.)

**Comment by liodali** [comment]
add this to pubspec 
```yaml 
dependency_overrides : 
   permission_handler:  ^10.0.0
```
