### ISSUE TITLE
User Location Marker disappear

### ISSUE THREAD

**Issue by h1amza** [liodali/osm_flutter#278]
After the map release(6s) user Location Marker(For trackMyPosition) disappear.

**Comment by liodali** [comment]
can you provide me morr information

**Comment by h1amza** [comment]
how can i give you more information about this part

**Comment by liodali** [comment]
more explanation i didn't understand your problem

**Comment by h1amza** [comment]
https://user-images.githubusercontent.com/32615603/176033171-e6a40d3f-4ea3-46fb-9be0-5dcab64e9a1d.mp4

**Comment by liodali** [comment]
in OSMFlutter , can you show the config of `userLocationMarker`

**Comment by liodali** [comment]
i will check it  and i will make fix for that

**Comment by Eimji** [comment]
Hello,

I don't know if this is related to a bug I have just found. Add a new marker on a map, and rotate the screen, the marker definitively disappears !
Here is my code for the map
```
        OSMFlutter(
          controller: mapController,
          trackMyPosition: true,
          showZoomController: true,
          initZoom: 17,
          minZoomLevel: 3,
          maxZoomLevel: 19,
          onMapIsReady: (bool isReady) {
            if (isReady) {
              _showFab.value = true;
            }
          },
          markerOption: MarkerOption(
            defaultMarker: MarkerIcon(
              assetMarker: AssetMarker(
                image: const AssetImage('assets/img/tower.png'),
              ),
            ),
          ),
        ),
```
And I add a marker with
```
      mapController.addMarker(GeoPoint(
        latitude: cellLocation['lat']!,
        longitude: cellLocation['lon']!,
      ));
```

Could you check this issue ? Thanks

**Comment by liodali** [comment]
it not rzlated bug but i will check why that happen  i already made save state  for rotation screen i

**Comment by Eimji** [comment]
Sorry, forget my message, my issue is due to my marker added too early, before the map is ready.

**Comment by liodali** [comment]
@h1amza  change the `scaleAssetImage` to number less than 1 and if you want to make it bigger make the number less than 0.5

**Comment by h1amza** [comment]
i don't have a problem with the size of marker.

i find the problem in my code when the map is Ready i call a myLocation function that reload the map :

@override
  Future<void> mapIsReady(bool isReady) async {
    if (isReady) {
      mapIsReadyRx.value = true;
      myLocation();
    }
  }

  Future<void> myLocation() async {
    GeoPoint geoPoint = await mapController.myLocation();
    currentPosition = geoPoint;
    debugPrint("geoPoint: ${geoPoint.latitude} || ${geoPoint.longitude}");
  }

**Comment by liodali** [comment]
because of that line 
```
currentPosition = geoPoint;
```
will rebuild the widget 
use ValueNotifier<GeoPoint> 
and changed to this
```
currentPosition.value = geoPoint;
```

**Comment by h1amza** [comment]
thank you so much for your quick response
