### ISSUE TITLE
How to fit all markers on the screen?

### ISSUE THREAD

**Issue by Eimji** [liodali/osm_flutter#279]
Hello,

I'm looking for setting the zoom automatically to fit all markers on the map, is it possible? Could you help me?

Thanks

**Comment by liodali** [comment]
that feature available on for roads 
i will add that for groupd of markers

**Comment by liodali** [comment]
until then you can make calculation between markers and get zoom level

**Comment by Eimji** [comment]
It would be great to have an option to set zoom automatically to fit markers !! Thanks

**Comment by liodali** [comment]
dont do that 
i will share with you later how to calculate it

**Comment by liodali** [comment]
check this link 
https://stackoverflow.com/questions/6048975/google-maps-v3-how-to-calculate-the-zoom-level-for-a-given-bounds
and use bounds to calculate right zoom level
i will add new api to fitbounds or list of geopoint will be available in 0.37+

**Comment by liodali** [comment]
ah man i forget i already added that feature 
use this method `zoomToBoundingBox`
and use `BoundingBox.fromGeoPoints` to transform list of geopoint to bound and you can zoom to that bound
sorry i forget about it 
i will add that information to readme sorry

**Comment by Eimji** [comment]
Thanks a lot ! zoomToBoundingBox works great !! You rock !
