### ISSUE TITLE
Crash on IOS when init the map on a point

### ISSUE THREAD

**Issue by YFrendo** [liodali/osm_flutter#282]
Hy everyone! 

I have an issue when I run my app on IOS (no issue on android).

Got this issue: 

["lon": 2.3483915, "lat": 48.8534951]
advanced#selection
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file flutter_osm_plugin/MyMapView.swift, line 451
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file flutter_osm_plugin/MyMapView.swift, line 451
* thread #1, queue = 'com.apple.main-thread', stop reason = Fatal error: Unexpectedly found nil while unwrapping an Optional value

Versions of packages: 

cupertino_icons: 1.0.2
  image_picker: 0.8.4
  image_crop: 0.4.0
  custom_radio_grouped_button: 2.1.1
  flutter_datetime_picker: 1.5.1
  path_provider: 2.0.4
  uuid: 3.0.4
  intl: 0.17.0
  responsive_framework: 0.1.4
  flutter_osm_plugin: 0.21.2
  osm_nominatim: 2.0.1
  flutter_osm_interface: 0.1.3
  http: 0.13.4
  tflite_flutter_helper: 0.3.0
  tflite_flutter: 0.9.0
  loading_gifs: 0.3.0
  url_launcher: 6.0.17
  flutter_pdfview: 1.2.1
  mailto: 2.0.0
  flutter_launcher_icons: 0.9.2
  flutter_native_splash: 1.3.2
  connectivity_plus: 2.2.0
  package_info_plus: 1.3.0
  device_info_plus: 3.2.1
  permission_handler: 8.1.6
  pdf: 3.7.1
  flutter_email_sender: 5.0.2

It's hard to upgrade to a new version due to  conflict with other package...

Thanks !

**Comment by YFrendo** [comment]
The error appear when the map launch.

I will try to upgrade but I have conflict with other packages on dependencies.

**Comment by liodali** [comment]
updgrade them also or use dependency_overrides

**Comment by YFrendo** [comment]
Ok fix when upgrade!
Thanks
