### ISSUE TITLE
Error Failed assertion: line 18 pos 16: 'north <= 85.0': is not true.

### ISSUE THREAD

**Issue by blablabla123-cell** [liodali/osm_flutter#286]
So, I'm getting the current bounding box and store it in shared preferences. When I move in the bounding box to the top left corner at the minimum zoom and press the button to store it, after reload it supposed to zoomIntoBoundingBox but, there is restriction: 

Failed assertion: line 18 pos 16: 'north <= 85.0': is not true.

which means the north of the bounding box is limited by 85, BUT when I store the top left corner , max zoom, the north is over than 85.05 etc. This is why it throws an error.

Please fix this issue, I suppose its gonna be the same mistake for south

**Comment by liodali** [comment]
can you provide the code to see what you did ?

**Comment by blablabla123-cell** [comment]
> can you provide the code to see what you did ?

import 'package:flutter/material.dart';
import 'package:flutter_osm_plugin/flutter_osm_plugin.dart';
import 'package:location/location.dart';
import 'package:app_settings/app_settings.dart';
import 'package:shared_preferences/shared_preferences.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> with OSMMixinObserver {
  // Location instance
  Location location = Location();

  // Permission status
  late PermissionStatus _permissionStatus;

  // Location service boolean
  late bool _serviceEnabled;

  // OSM Map controller instance
  late MapController controller;

  // Shared preferences instance
  late SharedPreferences prefs;

  // Current bounding box
  late BoundingBox currentBoundingBox;

  // Async function, get sharedPreferences
  Future _loadSharedPreferences() async {
    // Get shared preferences instance
    prefs = await SharedPreferences.getInstance();
    // Get current bounding box, if the values equal to null return default values for each horizont
    currentBoundingBox = BoundingBox(
        north: prefs.getDouble('north') ?? 76.35189643112588,
        east: prefs.getDouble('east') ?? 63.28125,
        south: prefs.getDouble('south') ?? -76.35189643112588,
        west: prefs.getDouble('west') ?? -63.28125);
    print(currentBoundingBox);
  }

  // Async function, get current bounding box and store it in shared preferences; Show SnackBar
  Future _storeCurrentBoundingBox() async {
    // Get shared preferences instance
    prefs = await SharedPreferences.getInstance();
    // Get current bounding box
    currentBoundingBox = await controller.bounds;
    // Store values in shared preferences
    prefs.setDouble('north', currentBoundingBox.north);
    prefs.setDouble('east', currentBoundingBox.east);
    prefs.setDouble('south', currentBoundingBox.south);
    prefs.setDouble('west', currentBoundingBox.west);
    print(currentBoundingBox);
    // Show SnackBar
    _showSnackBar(
        const Text('Current camera position is saved in the storage.'));
  }

  // Async function, checks user permissions, location service, enables user position and tracking
  Future _setUserLocation() async {
    // Checks if the app has permission to access location.
    _permissionStatus = await location.hasPermission();
    // Checks if the permission to use location services has not been granted.
    if (_permissionStatus != PermissionStatus.granted) {
      // Requests permission to access location.
      _permissionStatus = await location.requestPermission();
      // Checks if the permission to use location services has been denied
      if (_permissionStatus == PermissionStatus.denied) {
        // Returns
        return;
      }
      // Checks if the permission to use lcoation services has been permanently denied
      if (_permissionStatus == PermissionStatus.deniedForever) {
        // Shows SnackBar
        _showSnackBar(
            const Text('App permission denied.'),
            // SnackBar action: open application settings
            SnackBarAction(
                label: 'Settings',
                onPressed: () {
                  // Opens Application settings
                  AppSettings.openAppSettings();
                }));
        // Returns
        return;
      }
    }
    // Checks if the location service is enabled.
    _serviceEnabled = await location.serviceEnabled();
    // If location service is not enabled, then ...
    if (!_serviceEnabled) {
      // Request the activation of the location service.
      _serviceEnabled = await location.requestService();
      // If location service is not enabled, then ...
      if (!_serviceEnabled) {
        // Returns
        return;
      }
    }
    // Activate current location position
    await controller.currentLocation();
    // Enable tracking user location
    await controller.enableTracking();
  }

  // Show SnackBar function out of Build context
  void _showSnackBar(Text content, [SnackBarAction? snackBarAction]) {
    ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: content, behavior: SnackBarBehavior.floating));
  }

  // Call method mapIsReady when map is initialiazed
  @override
  Future<void> mapIsReady(bool isReady) async {
    // If the map is initialized, then ...
    if (isReady) {
      // Set the bounding box from shared preferences to a variable 'currentBoundingBox'
      await controller.zoomToBoundingBox(currentBoundingBox);
    }
  }

  @override
  void initState() {
    super.initState();
    // Load shared preferences in initial state
    _loadSharedPreferences();
    // Initial Map controller in initial state
    controller = MapController(
        // Set the user position initially
        // If false requires initPosition to be initialized
        // If true asks application permissions and tries to locate the user position
        initMapWithUserPosition: false,
        // Initial geo point position
        initPosition: GeoPoint(latitude: 0.0, longitude: 0.0),
        // Sets area limit (to avoid an error: 'Failed assertion: line 18 pos 16: 'north <= 85.0': is not true.'
        areaLimit: const BoundingBox.world());
    // Observer to implement method MapIsReady; this = OSMMixinObserver
    controller.addObserver(this);
  }

  @override
  Widget build(BuildContext context) {
    // Scaffold
    return Scaffold(
      // OSM library
      body: OSMFlutter(
        controller: controller,
      ),
      // BottomAppBar
      bottomNavigationBar: BottomAppBar(
          // Row
          child: Row(
        // MainAxisAlignment
        mainAxisAlignment: MainAxisAlignment.end,
        children: [
          IconButton(
              onPressed: _storeCurrentBoundingBox,
              icon: const Icon(Icons.location_history)),
          // User location activation and tracking
          IconButton(
              onPressed: _setUserLocation,
              icon: const Icon(Icons.location_searching)),
        ],
      )),
    );
  }
}

**Comment by blablabla123-cell** [comment]
Why is the tree put wrong? How to put it properly?

**Comment by liodali** [comment]
if you set limit it will not exceed that area on which platform you test ?

**Comment by blablabla123-cell** [comment]
> Testing on Android 10, Honor
> Minimum sdk 21
> Compile sdk 32

**Comment by blablabla123-cell** [comment]
I noticed that also zoomcontroller is not showed up when I switch to true

**Comment by liodali** [comment]
i will fix the bounding values 
yeah make your own zoom buttons

**Comment by blablabla123-cell** [comment]
Thank u, really appreciate for the help! Let's make the plugin perfect))

**Comment by blablabla123-cell** [comment]
> i will fix the bounding values yeah make your own zoom buttons
How do I update the plugin?

**Comment by liodali** [comment]
check the new version `0.34.1+6` for for being late
