### ISSUE TITLE
white screen on new version 0.37

### ISSUE THREAD

**Issue by hansmboron** [liodali/osm_flutter#293]
I updated version 0.34 to 0.37 and now it's just showing a white screen instead of the map. Besides, in both versions it is giving error several times to generate road

**Comment by liodali** [comment]
show me log error 
and small sample if it possible ?

**Comment by hansmboron** [comment]
https://ibb.co/mvgfj5C

`E/MethodChannel#flutter/platform_views(29789): Failed to handle method call
E/MethodChannel#flutter/platform_views(29789): java.lang.NullPointerException: null cannot be cast to non-null type java.util.HashMap<kotlin.String, kotlin.Any>{ kotlin.collections.TypeAliasesKt.HashMap<kotlin.String, kotlin.Any> }
E/MethodChannel#flutter/platform_views(29789): 	at hamza.dali.flutter_osm_plugin.OsmFactory.create(OsmFactory.kt:29)
E/MethodChannel#flutter/platform_views(29789): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:197)
E/MethodChannel#flutter/platform_views(29789): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/MethodChannel#flutter/platform_views(29789): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/MethodChannel#flutter/platform_views(29789): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#flutter/platform_views(29789): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter/platform_views(29789): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter/platform_views(29789): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter/platform_views(29789): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#flutter/platform_views(29789): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter/platform_views(29789): 	at android.os.Looper.loop(Looper.java:246)
E/MethodChannel#flutter/platform_views(29789): 	at android.app.ActivityThread.main(ActivityThread.java:8653)
E/MethodChannel#flutter/platform_views(29789): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(29789): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/MethodChannel#flutter/platform_views(29789): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/flutter (29789): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(error, null cannot be cast to non-null type java.util.HashMap<kotlin.String, kotlin.Any>{ kotlin.collections.TypeAliasesKt.HashMap<kotlin.String, kotlin.Any> }, null, java.lang.NullPointerException: null cannot be cast to non-null type java.util.HashMap<kotlin.String, kotlin.Any>{ kotlin.collections.TypeAliasesKt.HashMap<kotlin.String, kotlin.Any> }`
`E/flutter (29789): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (29789): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (29789): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (29789): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (29789): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (29789): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (29789): 	at android.os.Looper.loop(Looper.java:246)
E/flutter (29789): 	at android.app.ActivityThread.main(ActivityThread.java:8653)
E/flutter (29789): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (29789): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/flutter (29789): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/flutter (29789): )
E/flutter (29789): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:607
E/flutter (29789): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:167
E/flutter (29789): <asynchronous suspension>
E/flutter (29789): #2      TextureAndroidViewController._sendCreateMessage
package:flutter/…/services/platform_views.dart:1134
E/flutter (29789): <asynchronous suspension>
E/flutter (29789): #3      AndroidViewController.create
package:flutter/…/services/platform_views.dart:762
E/flutter (29789): <asynchronous suspension>
E/flutter (29789): #4      TextureAndroidViewController.setSize
package:flutter/…/services/platform_views.dart:1062
E/flutter (29789): <asynchronous suspension>
E/flutter (29789): #5      RenderAndroidView._sizePlatformView
package:flutter/…/rendering/platform_view.dart:179
E/flutter (29789): <asynchronous suspension>`

**Comment by liodali** [comment]
provide you widget setup and mapcontroller

**Comment by hansmboron** [comment]
map controller
`MapController mapController = MapController(
    initMapWithUserPosition: true,
    initPosition: GeoPoint(latitude: 0, longitude: 0),
  );

@override
  void onInit() async {
    // verificar se gps está ligado
    checkGps();
    BoundingBox bb = BoundingBox(
      north: -73.9872354804,
      east: -33.7683777809,
      south: -34.7299934555,
      west: 5.24448639569,
    );
    mapController = MapController(
        initMapWithUserPosition: true,
        initPosition: GeoPoint(
            latitude: initialGeo.value.latitude,
            longitude: initialGeo.value.longitude),
        areaLimit: bb);
    messageListener(_message);
    super.onInit();
  }

  @override
  void onClose() {
    mapController.dispose();
    super.onClose();
  }
`

Widget setup
`OSMFlutter(
              showZoomController: true,
              onMapIsReady: (value) async {
                if (value) {
                    await controller.goToUserPosition();
                }
              },
              controller: controller.mapController,
              initZoom: 14,
              minZoomLevel: 4,
              maxZoomLevel: 17,
              stepZoom: 1.0,
              onGeoPointClicked: (geo) async {
                await controller.mapController.removeMarker(geo);
              },
              userLocationMarker: UserLocationMaker(
                personMarker: const MarkerIcon(
                  icon: Icon(
                    Icons.location_history,
                    color: AppConsts.primary,
                    size: 64,
                  ),
                ),
                directionArrowMarker: const MarkerIcon(
                  icon: Icon(
                    Icons.keyboard_double_arrow_up_rounded,
                    size: 64,
                    color: Colors.black,
                  ),
                ),
              ),
              roadConfiguration: RoadConfiguration(
                startIcon: const MarkerIcon(
                  icon: Icon(
                    Icons.person,
                    size: 64,
                    color: Colors.brown,
                  ),
                ),
                roadColor: Colors.yellowAccent,
              ),
              markerOption: MarkerOption(
                defaultMarker: const MarkerIcon(
                  icon: Icon(
                    Icons.person_pin_circle,
                    color: Colors.blue,
                    size: 56,
                  ),
                ),
              ),
            ),`

**Comment by liodali** [comment]
you shouldn't set initMapWithUserPosition to true and provide initPosition also

**Comment by huzaifasaeed** [comment]
I am also facing same issue.

**Comment by liodali** [comment]
i will publish quick fix for that

**Comment by liodali** [comment]
check the new version `0.37.2`
