### ISSUE TITLE
setZoom(zoomLevel: 19) not working

### ISSUE THREAD

**Issue by mrQuidome** [liodali/osm_flutter#302]
When I set the zoomlevel to a specific number it does not zoom

The others work fine, zoomIn, zoomOut and setZoom(stepZoom: 7)

**Comment by liodali** [comment]
show me you osmflutter config

**Comment by liodali** [comment]
i will make quick fix for it

**Comment by mrQuidome** [comment]
Nice, thnxs, it works now :)
