### ISSUE TITLE
Most of the package functionality are turned off 

### ISSUE THREAD

**Issue by Mahmoudhweedy** [liodali/osm_flutter#306]
W/OsmDroid( 9664): UnknownHostException downloading MapTile: /15/19238/13514 : java.net.UnknownHostException: Unable to resolve host "c.tile.openstreetmap.org": No address associated with hostname
W/System.err( 9664): java.net.UnknownHostException: Unable to resolve host "routing.openstreetmap.de": No address associated with hostname
W/System.err( 9664): 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245)
W/System.err( 9664): 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
W/System.err( 9664): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
W/System.err( 9664): 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96)
W/System.err( 9664): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
W/System.err( 9664): 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
W/System.err( 9664): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
W/System.err( 9664): 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
W/System.err( 9664): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
W/System.err( 9664): 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
W/System.err( 9664): 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
W/System.err( 9664): 	at org.osmdroid.bonuspack.utils.HttpConnection.doGet(HttpConnection.java:68)
W/System.err( 9664): 	at org.osmdroid.bonuspack.utils.BonusPackHelper.requestStringFromUrl(BonusPackHelper.java:58)
W/System.err( 9664): 	at org.osmdroid.bonuspack.routing.OSRMRoadManager.getRoads(OSRMRoadManager.java:194)
W/System.err( 9664): 	at org.osmdroid.bonuspack.routing.OSRMRoadManager.getRoad(OSRMRoadManager.java:286)
W/System.err( 9664): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView$drawRoad$2$1.invokeSuspend(FlutterOsmView.kt:1503)
W/System.err( 9664): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err( 9664): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
W/System.err( 9664): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
W/System.err( 9664): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
W/System.err( 9664): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
W/System.err( 9664): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
W/System.err( 9664): Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
W/System.err( 9664): 	at libcore.io.Linux.android_getaddrinfo(Native Method)
W/System.err( 9664): 	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
W/System.err( 9664): 	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:202)
W/System.err( 9664): 	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
W/System.err( 9664): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
W/System.err( 9664): 	... 31 more
E/BONUSPACK( 9664): OSRMRoadManager::getRoad: request failed.

**Comment by liodali** [comment]
can you provide more information  ? 
maybe the routing server is down for moment you can try now 
i have nothing to do with routing because i'm using free service base on osm api
