### ISSUE TITLE
How to limit the search of the map just in france

### ISSUE THREAD

**Issue by h1amza** [liodali/osm_flutter#308]
How to limit the search of the map just in france (Paris) or specific zone

**Comment by liodali** [comment]
use bounding box

**Comment by liodali** [comment]
but that has limit only for android now

**Comment by liodali** [comment]
can you provide more information what you want to do exactly

**Comment by h1amza** [comment]
it's the same thing in your example/lib/src/search_example.dart.
just specify the search only in France or Paris using your addressSuggestion

**Comment by liodali** [comment]
you can search for custom api to get address in specific location 
or when you get suggestion you try to filter those address in they are in boundingbox of that location 
that can take time but you can try it
