### ISSUE TITLE
user Location Marker disappear when i called my location function

### ISSUE THREAD

**Issue by h1amza** [liodali/osm_flutter#309]
Future<void> myLocation() async {
   GeoPoint? currentPosition = await mapController.myLocation();

    debugPrint(
        "geoPoint: ${currentPosition!.latitude} || ${currentPosition!.longitude}");
  }

**Comment by liodali** [comment]
use callback `onLocationChanged` when you activate the tracking 
that method will get location and close the provider

**Comment by h1amza** [comment]
i solved by adding: widget: await mapController.currentLocation();
i will try your solution to.

**Comment by liodali** [comment]
i

**Comment by liodali** [comment]
I fixed disable of user location when calling `myLocation`
