### ISSUE TITLE
Assetmarker image is different size in iOS and android

### ISSUE THREAD

**Issue by jesussmile** [liodali/osm_flutter#315]
I have the same .png image for both iOS and android. but in IOS its a little bloated , I am using it on a real device. 

```ruby
await osmController!.setMarkerOfStaticPoint(
            id: driverKey!,
            markerIcon: MarkerIcon(
              assetMarker:
                  AssetMarker(image: AssetImage("images/images/car-ios.png")),
            ));


```
![IMG_8138](https://user-images.githubusercontent.com/11044978/182295825-fc483f5d-053b-45cf-96da-3a410e10cdd1.JPG)
![IMG_7733](https://user-images.githubusercontent.com/11044978/182295839-afa03b0d-5c85-4c7a-b1af-7fae75991781.JPG)

**Comment by liodali** [comment]
duplicated (#216) 
i will fixed soon

**Comment by liodali** [comment]
in ios i forced to make static size by default not like android 
i just convert to drawable and shown like it's

**Comment by liodali** [comment]
check the new version `0.39.0`
