### ISSUE TITLE
map can't move only zoom in or zoom out

### ISSUE THREAD

**Issue by h1amza** [liodali/osm_flutter#316]
i have 2 app using osm (client and driver) in driver it's fine but in client app the map don't move(right left up down) Both of them have the same code:

Scaffold(
  key: controller.drawerKey,
  endDrawer: const SideMenuView(),
  resizeToAvoidBottomInset: false,
  backgroundColor: Colors.white,
  body: OSMFlutter(
    controller: controller.mapController,
    trackMyPosition: true,
    androidHotReloadSupport: true,
    initZoom: 17,
    maxZoomLevel: 19,
  ),
);

**Comment by h1amza** [comment]
i didn't understand!

**Comment by liodali** [comment]
i mean maybe the parent of that widget is gestureDetector ?

**Comment by h1amza** [comment]
it's my home page, i only have scaffold widget as parent

**Comment by liodali** [comment]
it wierd do have any log error 
or more information to provide

**Comment by liodali** [comment]
are you still facing the same problem ?

**Comment by h1amza** [comment]
yes still the same problem.
and i don't have any logs for that issue.

**Comment by h1amza** [comment]
am facing this issue since your update 0.37.2+15

**Comment by liodali** [comment]
but the other app use the same version ? or not

**Comment by h1amza** [comment]
yes same version same code

**Comment by h1amza** [comment]
and when i set isPicker to true i can move the map

**Comment by liodali** [comment]
driver and client are diff app or in the same app ?

**Comment by h1amza** [comment]
yes diff app

**Comment by h1amza** [comment]
for example this code work in driver and in client don't :

/*
* Created By Mirai Devs.
* On 8/6/2022.
*/

import 'package:flutter/material.dart';
import 'package:flutter_osm_plugin/flutter_osm_plugin.dart';
import 'package:get/get.dart';
import 'package:jolitaxi_client/app/widgets/loading_animation_widget.dart';

class TestOsmWidget extends StatefulWidget {
  const TestOsmWidget({Key? key}) : super(key: key);

  @override
  State<TestOsmWidget> createState() => _TestOsmWidgetState();
}

class _TestOsmWidgetState extends State<TestOsmWidget> with OSMMixinObserver {
  late MapController mapController;

  /// mapIsReady
  RxBool mapIsReadyRx = false.obs;

  @override
  Future<void> mapIsReady(bool isReady) async {
    if (isReady) {
      mapIsReadyRx.value = true;
    }
  }

  @override
  void initState() {
    super.initState();
    mapController = MapController(
      initMapWithUserPosition: true,
    );

    mapController.addObserver(this);
  }

  @override
  void dispose() {
    mapController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      backgroundColor: Colors.white,
      body: OSMFlutter(
        controller: mapController,
        trackMyPosition: true,
        androidHotReloadSupport: true,
        isPicker: false,
        initZoom: 17,
        maxZoomLevel: 19,
        userLocationMarker: UserLocationMaker(
          personMarker: const MarkerIcon(
            icon: Icon(
              Icons.person,
              size: 64,
              color: Colors.brown,
            ),
          ),
          directionArrowMarker: const MarkerIcon(
            icon: Icon(
              Icons.person,
              size: 64,
              color: Colors.brown,
            ),
          ),
        ),
        roadConfiguration: RoadConfiguration(
          startIcon: const MarkerIcon(
            icon: Icon(
              Icons.person,
              size: 64,
              color: Colors.brown,
            ),
          ),
          // roadColor: Colors.yellowAccent,
        ),
        markerOption: MarkerOption(
          defaultMarker: const MarkerIcon(
            icon: Icon(
              Icons.person,
              size: 64,
              color: Colors.brown,
            ),
          ),
        ),
        mapIsLoading: Obx(
          () {
            if (!mapIsReadyRx.value) {
              return const LoadingAnimationWidget();
              //return const SizedBox.shrink();
            } else {
              return const SizedBox.shrink();
            }
          },
        ),
        onMapIsReady: (bool isReady) {
          if (isReady) {
            mapIsReadyRx.value = true;
          } //
          else {
            mapIsReadyRx.value = false;
          }
        },
      ),
    );
  }
}

**Comment by h1amza** [comment]
for example this code work in driver and in client don't :
`
import 'package:flutter/material.dart';
import 'package:flutter_osm_plugin/flutter_osm_plugin.dart';
import 'package:get/get.dart';
import 'package:jolitaxi_client/app/widgets/loading_animation_widget.dart';

class TestOsmWidget extends StatefulWidget {
const TestOsmWidget({Key? key}) : super(key: key);

@OverRide
State createState() => _TestOsmWidgetState();
}

class _TestOsmWidgetState extends State with OSMMixinObserver {
late MapController mapController;

/// mapIsReady
RxBool mapIsReadyRx = false.obs;

@OverRide
Future mapIsReady(bool isReady) async {
if (isReady) {
mapIsReadyRx.value = true;
}
}

@OverRide
void initState() {
super.initState();
mapController = MapController(
initMapWithUserPosition: true,
);

mapController.addObserver(this);
}

@OverRide
void dispose() {
mapController.dispose();
super.dispose();
}

@OverRide
Widget build(BuildContext context) {
return Scaffold(
resizeToAvoidBottomInset: false,
backgroundColor: Colors.white,
body: OSMFlutter(
controller: mapController,
trackMyPosition: true,
androidHotReloadSupport: true,
isPicker: false,
initZoom: 17,
maxZoomLevel: 19,
userLocationMarker: UserLocationMaker(
personMarker: const MarkerIcon(
icon: Icon(
Icons.person,
size: 64,
color: Colors.brown,
),
),
directionArrowMarker: const MarkerIcon(
icon: Icon(
Icons.person,
size: 64,
color: Colors.brown,
),
),
),
roadConfiguration: RoadConfiguration(
startIcon: const MarkerIcon(
icon: Icon(
Icons.person,
size: 64,
color: Colors.brown,
),
),
// roadColor: Colors.yellowAccent,
),
markerOption: MarkerOption(
defaultMarker: const MarkerIcon(
icon: Icon(
Icons.person,
size: 64,
color: Colors.brown,
),
),
),
mapIsLoading: Obx(
() {
if (!mapIsReadyRx.value) {
return const LoadingAnimationWidget();
//return const SizedBox.shrink();
} else {
return const SizedBox.shrink();
}
},
),
onMapIsReady: (bool isReady) {
if (isReady) {
mapIsReadyRx.value = true;
} //
else {
mapIsReadyRx.value = false;
}
},
),
);
}
}`

**Comment by h1amza** [comment]
i rewrite the code in driver app and doesn't work also

**Comment by h1amza** [comment]
i found this problem in your code to
when you set trackMyPosition to true you cannot move around the map

**Comment by liodali** [comment]
yeah because the map will follow the user location

**Comment by liodali** [comment]
before 0.37 when you move the map and track is true 
map stop follow the user location 
and i changed that maybe i need to make it less strick like that

**Comment by liodali** [comment]
i will fix that in the next version

**Comment by h1amza** [comment]
ok and thanks for your quick responding

**Comment by liodali** [comment]
check the new version `0.37.2+5`

**Comment by h1amza** [comment]
yeh it's work fine and smooth thanks.
