### ISSUE TITLE
Ability to change tile server at runtime?

### ISSUE THREAD

**Issue by malown** [liodali/osm_flutter#327]
Is it possible to change the tile server depending on the state of the widget the map is shown in after the MapController has been initialized?

For example, switch to dark tiles when the user enables dark mode

**Comment by liodali** [comment]
sorry for now that feature not implemented yet but im planned to impl soon dont worry i already want add it

**Comment by liodali** [comment]
we have added this feature now you can use any osm server 
the only limitation now is when osm server use api token in header like  bearer authentication.
 we will add that functionality later
