### ISSUE TITLE
Is there a way to get a continuous line with connected corners to draw the road? Instead of the disconnected rectangles

### ISSUE THREAD

**Issue by MasiaVittorio** [liodali/osm_flutter#338]
This is a screenshot from this plugin on flutter
![image](https://user-images.githubusercontent.com/14254644/197177800-9794c710-794e-4554-89ae-f86a22e4f9c8.png)

This is a screenshot from google maps:
![image](https://user-images.githubusercontent.com/14254644/197178329-4e8f0f92-7267-4c0f-97f7-47fa02baa46c.png)

**Comment by liodali** [comment]
the problem is google sdk use opengl to draw not like our native sdk we use osmdroid that draw polyline using canvas 
I will check if we can make continues path

**Comment by jesussmile** [comment]
we would love to see a fix to it, where excatly can i find the method you are using ? is it `google_polyline_algorithm.dart` ? I think it only decodes and encode lat lang, How would you draw the road though ?  where can I look in the source code ?

**Comment by liodali** [comment]
yeah it will fixed in +0.50.0

**Comment by liodali** [comment]
check our new version that now fix draw polylines in android
