### ISSUE TITLE
Conflicting map Zoom range between OSMFlutter(initZoom) and controller.setZoom()

### ISSUE THREAD

**Issue by T1960CT** [liodali/osm_flutter#345]
Hey all, when creating a map through the OSMFlutter widget and setting initZoom, the allowed range is (2, 19), but when setting the zoom through mapController.setZoom(zoomLevel: 19, stepZoom: 1.0), it throws an error saying the allowed range is (2, 18). 
Is this as simple as a typo fixable in a pull request? I haven't delved into PR on libraries before, but could be a first?

```dart
MapController mapController = MapController(initMapWithUserPosition: true);

// In the page's initState, if set to 19, library throws error
Future.delayed(
      const Duration(milliseconds: 100),
      () => mapController.setZoom(zoomLevel: 19, stepZoom: 1.0),
);

OSMFlutter(
      controller: mapController,
      markerOption: MarkerOption(
        defaultMarker: MarkerIcon(
          icon: Icon(
            IconData(
              appSettings.defaultPinMarkerIcon,
              fontFamily: 'MaterialIcons',
            ),
            color: Color(appSettings.defaultPinMarkerColour),
            size: appSettings.defaultPinMarkerSize.toDouble(),
          ),
        ),
      ),
      initZoom: 19, // range (2, 19)
      mapIsLoading: const Center(child: CircularProgressIndicator()),
      showZoomController: true,
      trackMyPosition: true,
    );
    ```

**Comment by T1960CT** [comment]
(further clarifications) I no longer need both the initZoom and the setZoom functions, and wouldn't use both in production, but I came across the discrepancy while transitioning after changing how settings are handled.

**Comment by T1960CT** [comment]
I also noticed the parameter name "userLocationMarker:" but the class is "UserLocationMaker" (missing the R in maRker)

**Comment by liodali** [comment]
technically i made the limitation of the setzoom because for ios 19 zoom level will make the map black but i will recheck again and fix that

**Comment by liodali** [comment]
you're getting that exception because you didn't change the default maxZoomLevel 
and also for `setZoom` you need specify one of the the values (`zoomLevel` or `stepZoom`) in `setZoom`
if  `stepZoom` specified zoomLevel will be ignored

**Comment by T1960CT** [comment]
Thanks for the reply! I'll try making those changes when I get home and will report back after :D

**Comment by T1960CT** [comment]
Hi again, sorry for taking so long! 
Setting the `maxZoomLevel` to 19 fixes that. I still can't go above 19, but I assume it's an SDK limitation so everything works as expected. Will close issue.
