### ISSUE TITLE
Black screen (logs: `payment required`)

### ISSUE THREAD

**Issue by ben-xD** [liodali/osm_flutter#346]
Thanks for the library. I built a free compass app really quickly. I would like to release it for free.

However, when running the library on iOS, I got a black map.

```
flutter: Map is ready: false # my own logs
ERROR importer.cpp:63: Unable to retrieve 'https://firebasestorage.googleapis.com/v0/b/osm-resources.appspot.com/o/osm-style.zip?alt=media&token=30e0c9fe-af0b-4994-8a73-2d31057014d4': payment required
WARNING sceneLoader.cpp:607: No source defined in the yaml scene configuration.
flutter: Map is ready: true # my own logs
```

There are 2 notable things:
- log: `payment required`
- When visiting that firebase storage link, I get a 402 error: `Quota has been exceeded for this project. Please visit the Firebase pricing page to learn more`.

**What do you suggest we do when we hit these rate limits?**

**Comment by ben-xD** [comment]
Oh I guess we should [customTile](https://pub.dev/documentation/flutter_osm_interface/0.1.28/flutter_osm_interface/CustomTile-class.html). So that leads me onto https://wiki.openstreetmap.org/wiki/Raster_tile_providers

I'll give that a go! :)

**Comment by ben-xD** [comment]
Oh, even after switching to osm tile servers, I still get this issue. This is because the URL that is rate limited is actually the "styles" file?

**Comment by jesussmile** [comment]
yea same issue today `ERROR importer.cpp:63: Unable to retrieve 'https://firebasestorage.googleapis.com/v0/b/osm-resources.appspot.com/o/osm-style.zip?alt=media&token=30e0c9fe-af0b-4994-8a73-2d31057014d4': payment required`

**Comment by jesussmile** [comment]
`  flutter_osm_plugin: ^0.37.2+2` works fine

**Comment by AlehSabadashGmail** [comment]
the same issue, @liodali

**Comment by liodali** [comment]
i will fix that sorry
i changed downloading of the styles file to firebase 
i will fix that

**Comment by AlehSabadashGmail** [comment]
thank you very much @liodali 
I am going to release my application with this package so just to confirm when will it be ready?

and one more updates here
When I used example from here https://github.com/liodali/osm_flutter/blob/master/example/lib/src/simple_example.dart I got black screen
then I tried use this code https://github.com/liodali/osm_flutter/blob/master/example/lib/src/home/home_example.dart
it still did not work
then I revert my changes to the first example and I saw the map
just to understand why the issue was fixed ?

**Comment by liodali** [comment]
check new version `0.40.3+1`

**Comment by AlehSabadashGmail** [comment]
seems it works, thanks mate
you are awesome 🥳

**Comment by AlehSabadashGmail** [comment]
@liodali hm, it still reproduces  but with another error
Task <63E184B8-E6D1-4C50-B1FA-85BE7B887089>.<1> HTTP load failed, 133/264 bytes (error code: -1005 [1:57])
Task <63E184B8-E6D1-4C50-B1FA-85BE7B887089>.<1> finished with error [-1005] Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={_kCFStreamErrorCodeKey=57, NSUnderlyingError=0x280385800 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x282e44690 [0x21985e3a0]>{length = 16, capacity = 16, bytes = 0x100201bba27d480f0000000000000000}, _kCFStreamErrorCodeKey=57, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <63E184B8-E6D1-4C50-B1FA-85BE7B887089>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <63E184B8-E6D1-4C50-B1FA-85BE7B887089>.<1>"
), NSLocalizedDescription=The network connection was lost., NSErrorFailingURLStringKey=https://dl.dropboxusercontent.com/s/25jzvtghx0ac2rk/osm-style.zip?dl=0, NSErrorFailingURLKey=https://dl.dropboxusercontent.com/s/25jzvtghx0ac2rk/osm-style.zip?dl=0, _kCFStreamErrorDomainKey=1}
ERROR importer.cpp:63: Unable to retrieve 'https://dl.dropboxusercontent.com/s/25jzvtghx0ac2rk/osm-style.zip?dl=0': The network connection was lost.
WARNING sceneLoader.cpp:607: No source defined in the yaml scene configuration.

**Comment by AlehSabadashGmail** [comment]
a little more information
if you tested on emulator you see just black box instead of map
if you tested on phone you see black box and issue is presented in flutter console

**Comment by AlehSabadashGmail** [comment]
I changed version to 0.37.2+2 and uncommented this two lines, now it works stable but it is bad solution, @liodali hope you will suggest something better, I guess there is some problem with service that you use to store zip or maybe something else, idk
hope it will help you
![Screenshot 2022-11-10 at 7 12 12 PM](https://user-images.githubusercontent.com/90776958/201148058-fe421d89-427c-4731-a531-8f2acab257b9.png)

**Comment by liodali** [comment]
i will publish new version to fix that

**Comment by AlehSabadashGmail** [comment]
thanks mate

**Comment by ben-xD** [comment]
Oh. I've tried the latest version `^0.40.3+1`, but I get:
```
flutter: Map is ready: false
ERROR importer.cpp:63: Unable to retrieve 'https://dl.dropboxusercontent.com/s/1gctumh0a4i4t21/AAAgwNlh7g4oGaw3hYxKpRJfa?dl=0': forbidden
```

When visiting that link, it says "Error (403) It seems you don't belong here! You should probably [sign in](https://www.dropbox.com/login). Check out our [Help Center](https://www.dropbox.com/help) and [forums](https://forums.dropbox.com/) for help, or head back to [home](https://www.dropbox.com/home)."

I'm not sure if anyone has faced this issue

**Comment by AlehSabadashGmail** [comment]
@ben-xD file is not large (seems 1,4 MB) but what if you need to fix or update map's styles, you will need to release new version so better to put in some storage like dropbox
just my thoughts

**Comment by liodali** [comment]
check new version `0.40.3+2`

**Comment by liodali** [comment]
it's depend where you're calling the controller
we have mapIsReady where you can place your interaction there
provide us the full example to see the problem

**Comment by liodali** [comment]
use this mixin `OSMMixinObserver`
and call `controller.addObserver(this);` in initState after initialize controller
inside this thod `mapIsReady` you will know that the map initialized by check isReady attribute is true and you can do all the after that

**Comment by ben-xD** [comment]
Thanks. However, I was already using the `onMapIsReady` callback on `OSMFlutter` instead of the mixin, because I'm using Flutter Hooks. Unfortunately, this callback is called before the `_osmBaseController` is ready. Again, this is because the package relies of `1250` milliseconds rather than waiting for the Platform  specific view to be ready.

I like this package and may use it in the future, but for now, I've switched to MapBox after exploring it.

Thanks for making this package. 🙂

**Comment by ben-xD** [comment]
Although I have switched to MapBox, I still want to help you find this issue (if it really is an issue):

I created a small app/github repo to reproduce it: https://github.com/ben-xD/osm_flutter_issue_1

Starting the app should be enough to trigger the issue shown in the screenshot: 
![error@2x](https://user-images.githubusercontent.com/24711048/201758547-1ebab00b-1a08-40d4-be75-aecf31a6f2f7.png)

**Comment by liodali** [comment]
the problem that you should put initaialization of mapcontroller in inithook not on the build because that willl to make new map controller every time build called 
but i will create new package to contain integration of controller and osm using hooks i will try to publish this new package today or tomorrow

**Comment by AlehSabadashGmail** [comment]
@liodali thank you very much, I used package all day I have not got any issue
thanks for you time

**Comment by liodali** [comment]
@ben-xD I created package extension `osm_flutter_hooks: ^1.0.0` 
for now it contain `useMapController` and `useMapIsReady`
and if you want you help  me to improve it
