### ISSUE TITLE
map will force recenter when using enableTracking on IOS only

### ISSUE THREAD

**Issue by jesussmile** [liodali/osm_flutter#347]
Hi, 
instead of posting codes I have added a video of just your plugin code from github. I have ran it in both ios and android without any changes, in Android it runs fine, and in IOS it will always force recenter. Also, see how the markerIcon are visible only when i hit the Floating button.'
I dont want it to recenter, how can i achieve that ?

https://user-images.githubusercontent.com/11044978/201838926-33af0575-6755-4dd8-bc13-02f7e4305fc4.mp4

**Comment by liodali** [comment]
yeah i will fix that in ios user location done manually so when you activate the tracking it will always recenter to user location
but in android its done differently when you move the map it will not recenter i can make both recenter but i will see i will add some api to controller that behavior

**Comment by AlehSabadashGmail** [comment]
@liodali any updates here?

**Comment by liodali** [comment]
i will add some new api for this issue  this weekend i hope it will be ready next week inshalah

**Comment by liodali** [comment]
yeah you need to set `enableStopFollow` to true because default value false

**Comment by jesussmile** [comment]
works great! thanx
