### ISSUE TITLE
CocoaPods could not find compatible versions for pod "flutter_osm_plugin"

### ISSUE THREAD

**Issue by codenashwan** [liodali/osm_flutter#351]
**pubspec.yaml**
`  flutter_osm_plugin: ^0.50.0-alpha.4`

```
[!] CocoaPods could not find compatible versions for pod "flutter_osm_plugin":
  In Podfile:
    flutter_osm_plugin (from `.symlinks/plugins/flutter_osm_plugin/ios`)

Specs satisfying the `flutter_osm_plugin (from `.symlinks/plugins/flutter_osm_plugin/ios`)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by liodali** [comment]
in terminal in ios folder
run `pod update`
or 
`flutter clean && flutter pub get`

**Comment by codenashwan** [comment]
**Same Error**

`[!] CocoaPods could not find compatible versions for pod "flutter_osm_plugin":
  In Podfile:
    flutter_osm_plugin (from `.symlinks/plugins/flutter_osm_plugin/ios`)

Specs satisfying the `flutter_osm_plugin (from `.symlinks/plugins/flutter_osm_plugin/ios`)` dependency were found, but they required a higher minimum deployment target.`

**Comment by liodali** [comment]
the min req sdk for ios is 12
