### ISSUE TITLE
Android: `Duplicate class androidx.lifecycle.ViewModelLazy found in modules `

### ISSUE THREAD

**Issue by ben-xD** [liodali/osm_flutter#353]
I've tried to install `flutter_osm_plugin: ^0.41.1`

However, the app fails to build because of the Android plugin code. Error: `Duplicate class androidx.lifecycle.ViewModelLazy found in modules `. A solution exists for android apps: https://stackoverflow.com/a/69832319/7365866: use the latest version for both Java and Kotlin extension. I think there could be a conflict with other dependencies here.

However, using Flutter dependencies, we don't have control over these dependency versions.

I've created a basic example to reproduce: https://github.com/ben-xD/osm_flutter_issue_2. The repo was created from `flutter create -t skeleton --org=uk.orth test_many_dependencies`, and only the `pubspec.yaml` was edited to **add more dependencies**.

## Error:
```
Duplicate class androidx.lifecycle.ViewModelLazy found in modules jetified-lifecycle-viewmodel-ktx-2.3.1-runtime (androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1) and lifecycle-viewmodel-2.5.1-runtime (androidx.lifecycle:lifecycle-viewmodel:2.5.1)
Duplicate class androidx.lifecycle.ViewTreeViewModelKt found in modules jetified-lifecycle-viewmodel-ktx-2.3.1-runtime (androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1) and lifecycle-viewmodel-2.5.1-runtime (androidx.lifecycle:lifecycle-viewmodel:2.5.1)

Go to the documentation to learn how to Fix dependency resolution errors.
```
---

## Side question:

Can we remove `implementation 'com.github.amitshekhariitbhu:Fast-Android-Networking:1.0.2'` from `build.gradle`? It looks like we're not using this dependency? repo: https://github.com/amitshekhariitbhu/Fast-Android-Networking. I'm not sure if it's this repo that causes the problem.

**Comment by liodali** [comment]
i will make fix for it today

**Comment by ben-xD** [comment]
🙏 thanks @liodali.

- I think we need to discover what causes the dependency conflict. We have `androidx.lifecycle:lifecycle-viewmodel-ktx` `2.3.1` and `2.5.1`. I downloaded all your dependencies manually and read their `AndroidManifest.xml` except `implementation 'com.github.amitshekhariitbhu:Fast-Android-Networking:1.0.2'`. None have a dependency on `androidx.lifecycle:lifecycle-viewmodel-ktx`. I couldn't find 1.0.2 of Fast Android Networking.

Maybe this command is useful: `./gradlew app:dependencyInsight --dependency androidx.lifecycle:lifecycle-viewmodel --configuration debugCompileClasspath`

You can also upload scan to Gradle: run `./gradlew app:dependencyInsight --dependency androidx.lifecycle:lifecycle-viewmodel --configuration debugCompileClasspath --scan`.

I've uploaded the output for the simple repo I provided: https://scans.gradle.com/s/mymjxgc6zjrei. It allows you to navigate the dependencies.

**Comment by liodali** [comment]
the problem is in preference-ktx with sdk33 make that error i will fix that

**Comment by ben-xD** [comment]
Oh okay, but there is no new update for `preference-ktx`. It's still on 1.2.0? https://developer.android.com/jetpack/androidx/releases/preference

**Comment by liodali** [comment]
no because osmdroid we need preference to store tiles and default preference in android deprecated xD

**Comment by liodali** [comment]
check the new version `0.41.2`

**Comment by ben-xD** [comment]
Thanks @liodali, it's working now 🤓🙏
