### ISSUE TITLE
General discussion on improving the map, adding features and bug fixes.

### ISSUE THREAD

**Issue by jesussmile** [liodali/osm_flutter#370]
I am checking the usage of MarkerIcon in the map but the icon appear to be of different size in these two devices

This one is on android, Icons pixel is fine

But If you see the overlay is  causing the problem, I want the text to appear on top of the car, This is android

Now, on IOS (real device), the overlay and road shape , is fine the icons appear on top of one another as it should be , however the icon image is too bloated and big, the pixel is also not clear as in android .  I understand the marker icon you are using is images, can you resize them or change the format like svg or sth such that it is not blown out.

![IMG_0005](https://user-images.githubusercontent.com/11044978/217140746-82349af8-32cb-4a76-9ba3-81ac33c370e9.jpeg)

**Comment by liodali** [comment]
for ios things are little bit complicated 
to show marker in ios we need size to be defined and we get that from your widget 
but try to set lower size for ios and tell me about the result

**Comment by jesussmile** [comment]
ok! I fixed the size but still the image is too blurry and unreadable 

Here is the code,
You can try it 
```ruby
GeoPoint pointA =
              GeoPoint(latitude: your_lat, longitude: your_lon);
          await osmController.addMarker(
            pointA,
            markerIcon: MarkerIcon(
              iconWidget: Container(
                // decoration: BoxDecoration(
                //     border: Border.all(color: Colors.black, width: 1)),
                height: 6.95.h,
                width: 48.w,
                child: Column(
                  children: [
                    Center(
                      child: Row(
                        children: [
                          Container(
                            decoration: BoxDecoration(
                              color: Colors.white,
                              border:
                                  Border.all(color: Colors.black, width: 2.0),
                            ),
                            width: 16.w,
                            //color: Colors.white,
                            child: Text(
                              "13 min ",
                              style: TextStyle(
                                color: Colors.black,
                                fontSize: 10.sp,
                              ),
                              textAlign: TextAlign.center,
                              overflow: TextOverflow.ellipsis,
                              maxLines: 1,
                            ),
                          ),
                          Container(
                            decoration: BoxDecoration(
                                color: Colors.black,
                                border: Border.all(
                                    color: Colors.black, width: 2.0)),
                            width: 31.w,
                            // color: Colors.black,
                            child: Text(
                              "Dolly House Private Limited",
                              //appData.pickUpLocation!.placeName!,
                              //  .dropOffLocation!,
                              style: TextStyle(
                                fontSize: 10.sp,
                                color: Colors.white,
                              ),
                              textAlign: TextAlign.center,
                              overflow: TextOverflow.ellipsis,
                              maxLines: 1,
                            ),
                          ),
                        ],
                      ),
                    ),
                    SvgPicture.asset(
                      "assets/pick_up.svg",
                      height: 40,
                    ),
                  ],
                ),
              ),
              //   ),
            ),
          );
```
![IMG_4383AC5D4AF8-1](https://user-images.githubusercontent.com/11044978/217487475-daeb28b4-75ed-4388-ab4c-8edc85a78653.jpeg)

**Comment by liodali** [comment]
i will add iosSize attribute for marker to then you can render the marker with bigger size in flutter before we resized again in ios side

**Comment by liodali** [comment]
for order 
i will find solution in android side since the same should be apply again in web 
but this part will be added later as improvemet for both platforms

**Comment by jesussmile** [comment]
Not a problem, I was going thru the ios side of code, may be I can check it too which sizes fits well or fomat ,

Here in `MarkerView.swift`

```
import Foundation

import MapKit

@available(iOS 11.0, *)
class MarkerView: MKMarkerAnnotationView {
    override var annotation: MKAnnotation? {
        willSet {
            // 1
            guard let point = newValue as? GeoPointMap else {
                return
            }
            canShowCallout = false
            calloutOffset = CGPoint(x: -5, y: 5)
            //rightCalloutAccessoryView = UIButton(type: .detailDisclosure)

            // 2
            if (point.marker != nil) {
                //   image = point.marker
            }

        }
    }
}

struct MarkerIconData {
    let image: UIImage?
    var size: [Int] = [48,48]
}

```
is this where you set the size ? or somehwere else ?

**Comment by jesussmile** [comment]
Okay! i went through your source code, and i think i found the reason why the images are so pixelated in Ios, Here check the result in ios now after updating the code. The problem in my opinion was in your function _capturePng you have not specified the pixelRatio, so i put `    ui.Image image = await boundary.toImage(pixelRatio: 5);` Now, the MarkerIcon is as sharp as in Android ,
![IMG_7E136B1A99AC-1](https://user-images.githubusercontent.com/11044978/217781390-4f93c38b-40ac-4694-84d7-c5b96e182ab7.jpeg)

```ruby
Future<dynamic> _capturePng(GlobalKey globalKey) async {
    if (globalKey.currentContext == null) {
      throw Exception("Error to draw you custom icon");
    }
    RenderRepaintBoundary boundary =
        globalKey.currentContext!.findRenderObject() as RenderRepaintBoundary;
    ui.Image image = await boundary.toImage(pixelRatio: 5);
    ByteData byteData =
        (await (image.toByteData(format: ui.ImageByteFormat.png)))!;
    Uint8List pngBytes = byteData.buffer.asUint8List();
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      return {
        "icon": pngBytes.convertToString(),
        "size": globalKey.currentContext != null
            ? [
                globalKey.currentContext!.size!.width.toInt(),
                globalKey.currentContext!.size!.height.toInt()
              ]
            : iosSizeIcon
      };
    }
    return pngBytes;
  }
```

**Comment by liodali** [comment]
this great you can make pr for that it will be integrate it in next version
since i finalized the alignement between the platforms we only miss some improvement

**Comment by jesussmile** [comment]
ok done! I dunno if i did it right, this is my first time with PR, anyways I want to try and hopefully fix how roads are drawn on the map in android, so far what i have understood from your code is, you use `google_polyline_algorithm: ^3.1.0` to decode and encode a polyline, if i am correct you pass a string of coordinates then draw them on the map ? for a lack of proper fix, we can get the end of the coordinates and over lap it with the second last coordinate such that the road will feel like it is streamlined and there is no gaps.  I can't find where exactly is the draw polylines on map is called ? if you could help me where to look I will try my best.

**Comment by liodali** [comment]
@jesussmile  why you delete your commet ? 
can you provide more information about your concern for roads ?

**Comment by jesussmile** [comment]
Oh okay, I thought you were busy.  I did some research on polyline that wont connect at the end , in my opinion I have found 3 possibilities to fix it.

1. I see you are using google_polyline_algorith to decode and encode coordinates to string to draw on the map,   so I added more extra geopoint such that the one polyline will overlap another at the end making the road feel smooth but it didn't work meaning it had to do with something how the lines are rendered in the map in you kotlin code 

 ```ruby
String encodePolyline(List<List<num>> coordinates, {int accuracyExponent = 5}) {
  if (accuracyExponent < 1) {
    throw ArgumentError.value(accuracyExponent, 'accuracyExponent',
        'Location accuracy exponent cannot be less than 1');
  }

  if (accuracyExponent > 9) {
    throw ArgumentError.value(accuracyExponent, 'accuracyExponent',
        'Location accuracy exponent cannot be greater than 9');
  }

  if (coordinates.isEmpty) return '';

  List<num> previousLatLng = [coordinates[0][0], coordinates[0][1]];
  String polyline = encodePoint(0, accuracyExponent: accuracyExponent) +
      encodePoint(0, accuracyExponent: accuracyExponent);

  for (var i = 1; i < coordinates.length; i++) {
    polyline += encodePoint(coordinates[i][0] - previousLatLng[0],
        accuracyExponent: accuracyExponent);
    polyline += encodePoint(coordinates[i][1] - previousLatLng[1],
        accuracyExponent: accuracyExponent);
    previousLatLng = [coordinates[i][0], coordinates[i][1]];
  }

  return polyline;
}

List<List<num>> decodePolyline(String polyline, {int accuracyExponent = 5}) {
  final accuracyMultiplier = math.pow(10, accuracyExponent);
  final List<List<num>> coordinates = [];

  int index = 0;
  int lat = 0;
  int lng = 0;
  List<num> previousLatLng = [0, 0];

  while (index < polyline.length) {
    int char;
    int shift = 0;
    int result = 0;

    int getCoordinate() {
      do {
        char = polyline.codeUnitAt(index++) - 63;

        result |= (char & 0x1f) << shift;
        shift += 5;
      } while (char >= 0x20);

      final value = result >> 1;
      final coordinateChange =
          (result & 1) != 0 ? (~BigInt.from(value)).toInt() : value;

      shift = result = 0;

      return coordinateChange;
    }

    lat += getCoordinate();
    lng += getCoordinate();

    final currentLatLng = [
      lat / accuracyMultiplier + previousLatLng[0],
      lng / accuracyMultiplier + previousLatLng[1]
    ];
    coordinates.add(currentLatLng);
    previousLatLng = currentLatLng;
  }

  return coordinates;
}
```

2. I checked you kotlin code `createRoad` and `drawRoad` and tried to add tried to look other answer also in the web and found that we can use parameters like `polyLine.setStrokeJoinType (StrokeJoin.Round) , poluyLine.setStrokeMiterLimit(10f)` etc to make the polyline smooth and increase the stroke towards the end . I tried it but couldn't apply it correctly because your polyline doesn't have those attributes like `ROUND` etc , can't debug due to version conflicts. etc... I followed this link

 https://stackoverflow.com/questions/56007702/how-to-draw-smoothlines-connected-without-any-breaks-lines-over-google-map-in

3. Also i don't know how or which `OSRMRoadManager` and PolylineEncoder you are using and from where so couldn't do more,
4. I will gather more information for now these are my points.

**Comment by liodali** [comment]
that issue already will be fixed in 0.50+ 
`google_polyline_algorithm` i used only for manuall draw  and for web
the impl of drawRoad in ios,android we use orsm the same for web that part done in separate package

**Comment by liodali** [comment]
in the code you will fine FlutterRoad or before create the road  in line https://github.com/liodali/osm_flutter/blob/4ec5d387df73a4ac4c8143d272ba1637a284d65e/android/src/main/kotlin/hamza/dali/flutter_osm_plugin/FlutterOsmView.kt#L1544

**Comment by jesussmile** [comment]
Good news! I fixed it. 
![Screenshot_20230211-184749](https://user-images.githubusercontent.com/11044978/218259516-c78e546c-2468-42a8-990f-fd22d0d8ec4d.jpg)

I will post a commit soon . Some issue with my grade and waiting to see if you will use a different method?

**Comment by liodali** [comment]
make coomit and i will see 
but like i said that issue already fixed in web 2.0 which will contain the new version but make pr and i will check it to merged

**Comment by jesussmile** [comment]
I added border to the road,  is it ok if I make a PR of it ? I don't know how to make a method call from flutter , I have never done it.  One more point.. I think it is possible to add navigation to your project. I am not as good as you but I will try.

![20230212_194841](https://user-images.githubusercontent.com/11044978/218315791-c6fbfeab-1b90-48e7-9b40-cfd9e31cee59.jpg)

**Comment by jesussmile** [comment]
Ok done! Please check out the pull request.

One question tho, I was checking leaftlet.js which uses openstreetmap and is free to use. The map is better looking than what we have now. Is it possible to integrate it in our libraries? What do you think ?

**Comment by jesussmile** [comment]
Next! I added navigation point like this on the polyline, is it any helpful? Unsure how to do it on ios. This points are clickable and will expand and close as you click on it.


![20230214_124347](https://user-images.githubusercontent.com/11044978/218662553-eff937bb-bb32-4d7b-9b7d-77067eecc1c3.jpg)
![20230214_124318](https://user-images.githubusercontent.com/11044978/218662579-72da7d68-d878-4a7a-8b27-4d50a32df49e.jpg)

**Comment by jesussmile** [comment]
Oh okay! Do you want me to make a PR  or just discard it ?

**Comment by jesussmile** [comment]
@liodali  please check this commit [https://github.com/liodali/osm_flutter/pull/375/commits/d6f80e0edbbd86df53c4d38b15ce982a99632ef0](url)

i set the commit such that the icon is right in the center of the coordinates, In ios its okay so didn't change it.
