### ISSUE TITLE
Way to know if camera is moving or not

### ISSUE THREAD

**Issue by smiesnyrobert** [liodali/osm_flutter#374]
Hi, thanks for your library and your hard work.

Can u please add methods something like **onCameraMove,onCameraIdle, or isMapAnimating**? I need to know because I have a marker that animates based on that.   

Manually swiping the screen i can workaround with:
```dart
Listener(
                  onPointerDown: (event) {
                    //moving
                   // change icon
                  },
                  onPointerUp: (event) async{
                    // not moving
                   // change icon
                    GeoPoint point = await controller.osmBaseController.getMapCenter();
                   // find address
                  },
                  child: OSMFlutter(...)
)
```
**onPointerUp** is triggered but map can still moving. 

Thank you very much.

**Comment by jesussmile** [comment]
What are you trying to do with your marker, animate and do what ?

**Comment by smiesnyrobert** [comment]
ok thank you, i will try it
