### ISSUE TITLE
Error after open maps for a second time in Flutter Web

### ISSUE THREAD

**Issue by skylastn** [liodali/osm_flutter#385]
handle 1
TypeError: Cannot read properties of null (reading 'contentWindow')
packages/flutter_osm_web/src/asset/map.js 201:65                                  setUpMap
packages/flutter_osm_web/src/controller/web_osm_controller.dart 143:35            initPositionMap
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/flutter_osm_web/src/controller/web_osm_controller.dart 139:31            initPositionMap
packages/flutter_osm_interface/src/map_controller/base_map_controller.dart 49:31  <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/flutter_osm_interface/src/map_controller/base_map_controller.dart 48:50  <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19           internalCallback

**Comment by liodali** [comment]
the flow or what exactly trying to do

**Comment by skylastn** [comment]
okay,
i want to show where the user last position in maps
i'm using Getx for state management
and this is my code

View
`import 'package:flutter/material.dart';
import 'package:flutter_osm_plugin/flutter_osm_plugin.dart';
import 'package:get/get.dart';
import '../../infrastructure/navigation/routes.dart';
import '../dashboard/controllers/dashboard.controller.dart';
import 'controllers/maps.controller.dart';

class MapsScreen extends GetView<MapsController> {
  const MapsScreen({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    Get.put(MapsController());
    return WillPopScope(
      onWillPop: () {
        if (!Get.isRegistered<DashboardController>()) {
          Get.offAllNamed(Routes.DASHBOARD);
        }
        return Future.value(true);
      },
      child: Scaffold(
        appBar: AppBar(
          title: const Text('Maps'),
          centerTitle: true,
        ),
        body: OSMFlutter(
          controller: controller.mapController,
          trackMyPosition: false,
          initZoom: 15,
          minZoomLevel: 2,
          maxZoomLevel: 17,
          stepZoom: 1.0,
          onMapIsReady: (p0) {
            print(p0);
            controller.onMapReady();
          },
          // userLocationMarker: UserLocationMaker(
          //   personMarker: const MarkerIcon(
          //     icon: Icon(
          //       Icons.location_history_rounded,
          //       color: Colors.red,
          //       size: 48,
          //     ),
          //   ),
          //   directionArrowMarker: const MarkerIcon(
          //     icon: Icon(
          //       Icons.double_arrow,
          //       size: 48,
          //     ),
          //   ),
          // ),
          roadConfiguration: const RoadOption(
            roadColor: Colors.yellowAccent,
          ),
          markerOption: MarkerOption(
              defaultMarker: const MarkerIcon(
            icon: Icon(
              Icons.person_pin_circle,
              color: Colors.blue,
              size: 56,
            ),
          )),
        ),
      ),
    );
  }
}
`

Controller 
`import 'package:flutter_osm_plugin/flutter_osm_plugin.dart';
import 'package:get/get.dart';

class MapsController extends GetxController {
  MapController mapController = MapController(
    initMapWithUserPosition: false,
    initPosition: GeoPoint(
      latitude: double.parse(Get.parameters['latitude'] ?? '0'),
      longitude: double.parse(Get.parameters['longitude'] ?? '0'),
    ),
  );

  @override
  void onInit() {
    super.onInit();
  }

  @override
  void onReady() {
    super.onReady();
  }

  @override
  void onClose() {
    super.onClose();
    print('release maps');
    mapController.dispose();
  }

  onMapReady() async {
    await mapController.addMarker(
      GeoPoint(
        latitude: double.parse(Get.parameters['latitude'] ?? '0'),
        longitude: double.parse(Get.parameters['longitude'] ?? '0'),
      ),
      // markerIcon: const MarkerIcon(
      //   icon: Icon(Icons.person, size: 60,),
      // )
    );
  }
}
`

**Comment by skylastn** [comment]
just a simple use, add marker on maps

**Comment by Ebrahimzarei103** [comment]
Hello, 
Did you get any solution to your problem?

**Comment by Ebrahimzarei103** [comment]
> just a simple use, add marker on maps
> 
> and blank page appared after open map for the second time

Hello,
Did you get any solution to your problem?

**Comment by liodali** [comment]
yeah for now we have issue with that i will try to solved 
for now in web we can only show map only as main view 
I will do my best to solve it as soon as possible

**Comment by skylastn** [comment]
thanks @liodali

**Comment by liodali** [comment]
check our new version `0.53.4`

**Comment by skylastn** [comment]
nice bro, thanks for solving the issue,
