### ISSUE TITLE
Is there any way to avoid the user icon rotation?

### ISSUE THREAD

**Issue by isaacfi** [liodali/osm_flutter#389]
How can I avoid the rotation of the user marker when is tracking it's location?

It rotates and does not make too much sense how is showing, I prefer an static horizontal image.

BR.

**Comment by liodali** [comment]
rotation based on bearing information from gps but i will add parameter to disable it

**Comment by isaacfi** [comment]
Thanks so much @liodali, your reply is appreciated.

**Comment by liodali** [comment]
check new version `0.53.0`
we added attribute `disableUserMarkerRotation` in `enableTracking` set it to true 
to disable the rotation
