### ISSUE TITLE
iOS app crash after calling MapController.setStaticPosition

### ISSUE THREAD

**Issue by bcmehdi8** [liodali/osm_flutter#392]
I added a MapSingleTapping listener on the MapController with the following code : 

```
late MapController _mapController;
final _markerId = "USER_LOCATION";

@override
void initState() {
    super.initState();

   _mapController = MapController.withPosition(
        initPosition: GeoPoint(
          latitude: 40.4
          longitude: -3.7
        ),
      );

   _mapController.listenerMapSingleTapping.addListener(advancedSelection);
}


  void advancedSelection() async {
    if (_mapController.listenerMapSingleTapping.value != null) {

      _mapController.setStaticPosition(
            [_mapController.listenerMapSingleTapping.value!], _markerId);

      _mapController
          .goToLocation(_mapController.listenerMapSingleTapping.value!);

  }
}
```

the idea of this code is whenever the user tap on the map, a marker will be inserted on that point, it works flawlessly on Android, but on iOS the app start to crash when the user tap on the map on the line of  `_mapController.setStaticPosition(.....`

There's no errors logged on debug console after the app get crashed

Tested on iPhone 14 Simulator 
Flutter Version : Flutter 3.7.6 • channel stable •
flutter_osm_plugin: ^0.51.0

**Comment by liodali** [comment]
you need to setStaticPosition need to use setMarkerOfStaticPoint before 
I recommand to use `addMarker` this api used to add marker each time user click
for setStaticPosition used to static markers such bus station/coffee/resturants/taxis staff like that

**Comment by bcmehdi8** [comment]
Thanks @liodali for your reply, I found a good workaround using addMarker and RemoveMarker, so it can remove the previous marker and add new one.
