### ISSUE TITLE
unregistered type: < plugins.dali.hamza/osmview > error with v0.54.1 and Flutter 3.10.0

### ISSUE THREAD

**Issue by Intecpsp** [liodali/osm_flutter#412]
I am getting the below error when trying to run my app with this package installed and configured. How do I correct this?

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(unregistered_view_type, A UIKitView widget is trying to create a PlatformView with an unregistered type: < plugins.dali.hamza/osmview >, If you are the author of the PlatformView, make sure `registerViewFactory` is invoked.
See: https://docs.flutter.dev/development/platform-integration/platform-views#on-the-platform-side-1 for more details.
If you are not the author of the PlatformView, make sure to call `GeneratedPluginRegistrant.register`., null)
```

**Comment by liodali** [comment]
on which platform you get this error ?

**Comment by Intecpsp** [comment]
Good question, I should've supplied that in the issue. I'm new to Flutter so I'm not sure if iOS is treated differently than macOS, but the emulator I am getting the error on is "macOS (darwin)".

**Comment by liodali** [comment]
sorry to say that but for now we still dont support macos

**Comment by annng** [comment]
is this not issue? because I also got this error in iOS simulator
