### ISSUE TITLE
Cropped icon

### ISSUE THREAD

**Issue by smiesnyrobert** [liodali/osm_flutter#420]
Hello can u please fix this?

If i add marker with angle, icon is cropped
```
MarkerIcon icon = MarkerIcon(
    assetMarker: AssetMarker(
        image: AssetImage(
          'assets/graphics/vehicle_marker.png',
        ),
        scaleAssetImage: 0.4),
  );
await controller.addMarker(newGeo, markerIcon: icon,angle: 1.18);
```
![1](https://github.com/liodali/osm_flutter/assets/33247860/f72b2884-3ad1-4502-868a-411a5a94e2a2)
![2](https://github.com/liodali/osm_flutter/assets/33247860/116c7cca-3e80-4c77-93e9-ae07de614462)

**Comment by smiesnyrobert** [comment]
android

**Comment by liodali** [comment]
i will make quick fix for it

**Comment by liodali** [comment]
yes im testing everything and i will update the docs make new version in this week inshallah

**Comment by liodali** [comment]
check our new version `0.55.2`

**Comment by smiesnyrobert** [comment]
is this angles correct? 
u have 
```
assert(angle >= -pi && angle <= pi, "angle should be between -pi and pi");
```
but everything <0 do nothing, i can only use numbers in interval 0-pi, negative numbers dont work, so icon can only rotating to right, no way to rotatate to left.
Icon can be rotaten only for 90° to right

**Comment by liodali** [comment]
ok will check the issue

**Comment by liodali** [comment]
i will made quick fix now to make angle between 0 and 2pi

**Comment by liodali** [comment]
check our new version `0.55.3`

**Comment by smiesnyrobert** [comment]
it works fine now :thumbsup:
thank u
