### ISSUE TITLE
Marker anchor

### ISSUE THREAD

**Issue by smiesnyrobert** [liodali/osm_flutter#421]
Can u please add option to set anchor of marker?  (center,bottom, bottom_center, top, top_center, etc...)

**Comment by majo482** [comment]
Or setting a anchor position, e.g. iconAnchor: [20, 40]

**Comment by liodali** [comment]
the issue that i can provide this feature only in android/web
because sdk for ios we don't anchor for marker

**Comment by liodali** [comment]
i will add anchor to marker as Optional in feature version
