### ISSUE TITLE
unable to removes number form street when use custom tiles

### ISSUE THREAD

**Issue by mohammed-najeeb** [liodali/osm_flutter#422]
hello
unable to removes numbers form street when use custom tiles 

<img width="220" alt="image" src="https://github.com/liodali/osm_flutter/assets/11240731/6b0f74b8-7cce-468d-b511-65863c5e2eb7">
<img width="353" alt="image" src="https://github.com/liodali/osm_flutter/assets/11240731/851a4c9e-2732-4d2c-9f24-489d6cd25083">

**Comment by liodali** [comment]
you cannot remove that because it's integrated 
in tiles even in svg you cannot remove them 
you need to make your own style tile and server tile

**Comment by mohammed-najeeb** [comment]
> you cannot remove that because it's integrated in tiles even in svg you cannot remove them you need to make your own style tile and server tile

شكرا 
 thank you
