### ISSUE TITLE
Map does not show up in final build

### ISSUE THREAD

**Issue by Sunclicker** [liodali/osm_flutter#427]
When I build my flutter web-app in debug mode, everything seems to work fine. But if I build my final web app and host it on a server, the map does not show up. There is only white space and these errors appear in the chrome console:

Refused to execute script from 'https://holidayplaces.pages.dev/packages/flutter_osm_web/src/asset/map.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

Uncaught TypeError: self.setUpMap is not a function
    at main.dart.js:102609:34
    at aTw.a (main.dart.js:6311:62)
    at aTw.$2 (main.dart.js:47025:14)
    at Object.t (main.dart.js:6297:10)
    at Ao.ayE (main.dart.js:102640:10)
    at Ao.yD (main.dart.js:102606:21)
    at main.dart.js:102355:14
    at aTw.a (main.dart.js:6311:62)
    at aTw.$2 (main.dart.js:47025:14)
    at Object.t (main.dart.js:6297:10)

It seems to be a problem with the minify process because in debug mode everything works as it should.
I used the newest flutter version 3.10.6 and the newest package version 0.55.3

Thanks in advance for your help!

**Comment by liodali** [comment]
sorry for that I'm aware of the issue in our code we already specify the type of the js file 
but i don't know why that's happen 
try to reseach for map.js in bundle build it and changed it manually before published to server 
are you using dart web server to publish it or ngnix ?

**Comment by Sunclicker** [comment]
thanks for your fast answer! I'm not very familiar with these stuff, because this is my first flutter app, so I don't really understand what I need to do to solve the error. I also don't own a own server. I hosted the app on cloudflare.

**Comment by Sunclicker** [comment]
> sorry for that I'm aware of the issue in our code we already specify the type of the js file but i don't know why that's happen try to reseach for map.js in bundle build it and changed it manually before published to server are you using dart web server to publish it or ngnix ?

thanks for your fast answer! I'm not very familiar with these stuff, because this is my first flutter app, so I don't really understand what I need to do to solve the error. I also don't own a own server. I hosted the app on cloudflare.

**Comment by Sunclicker** [comment]
Finally after hours of searching through the internet I found a workaround to solve the problem. If I copy the "packages" folder inside the "assets" folder into the root-directory, and then publish it on the server, everything is working perfectly fine. So I guess this is a error by the dart2js compiler which is doing something wrong with the path.

**Comment by liodali** [comment]
i will add that to readme file for other

**Comment by liodali** [comment]
I will make fix for this
by adding check if release add assets/ when loading map.js script

**Comment by funtoom** [comment]
> I will make fix for this by adding check if release add assets/ when loading map.js script

Are you sure that this fix will not break other type of hosting?
Because "build folder" by itself is correct and the problem only after deploying to firebase hosting (and maybe some other)

What about other 2 files in assets of web? Are they unused?
And what about yaml assets file of flutter_osm_plugin? I didn't check yet but is it okay without fix?

**Comment by liodali** [comment]
the fix will only affect how we load those asset in release
in debug mode, flutter take care of that but in release loading asset using the wrong path
by adding assets/ to packages/.... will fix the issue 
and you don't need to copie the packages folder in root directory at all
we can try it if everything is ok we keep else we can revert

**Comment by Olvera-Orozco-Miguel-Angel** [comment]
“Hi @funtoom , a question: did you manage to solve it?
