### ISSUE TITLE
ANDROID, mapIsLoading issue

### ISSUE THREAD

**Issue by david-hov** [liodali/osm_flutter#429]
https://github.com/liodali/osm_flutter/assets/74877723/e5610283-3de0-4fd3-81ed-22c5b1972d9c

OSMFlutter(
              showContributorBadgeForOSM: true,
              controller: controller,
              mapIsLoading: Center(child: CircularProgressIndicator()),
              initZoom: 12,
              onMapIsReady: (isReady) async {
                if (isReady)  {
                  firstController.isMapControllerInitialized.value = true;
                  await call();
                }
              })
              
when GETX(firstController) update value, map loading starts again and never ends. 
It's normal when Getx obs value changes the widget will be updated, but is there a solution to make map loading only once, and if widget is not out of widget's tree, dont do loading everytime, or if it's do loading not hang

**Comment by liodali** [comment]
what this code  do in general
```dart
firstController.isMapControllerInitialized.value = true;
await call();
```

**Comment by liodali** [comment]
can you provide me more code if possible the all page or screen

**Comment by david-hov** [comment]
> can you provide me more code if possible the all page or screen

there some keys that I can share, but top of widget just initialized controller, and other staff not related to OSMflutter, the problem is that, mapisLoadong calls everytime when state or Getx state is changed,but it need to be called only during initilize, as of my understanding

**Comment by david-hov** [comment]
> what this code do in general
> 
> ```dart
> firstController.isMapControllerInitialized.value = true;
> await call();
> ```

1-st one make sure that map is initialized and start socket connection,l.
second one started to insert static points, but without mapIsLoadong everything works, just not showing loading indicator, shows world map and after that my location

**Comment by liodali** [comment]
put OSMFlutter in external widget separated from current and pass to it `firstController`

**Comment by david-hov** [comment]
still the same

> put OSMFlutter in external widget separated from current and pass to it `firstController`

still same

**Comment by david-hov** [comment]
> put OSMFlutter in external widget separated from current and pass to it `firstController`

solved!!!, but I think it will be good to have controller.mapIsInitilized()return <bool> , property

**Comment by liodali** [comment]
you mean called only called when map is initialized ?

**Comment by david-hov** [comment]
> you mean callback called only when map is initialized ?

yeah, like when map fully initilized give callback to controller, to be available in widget.

**Comment by david-hov** [comment]
In my case it was about rebuild of widget, but maybe there can be situations that need to be updated or rebuild again, and it will be good to not hang loading view second time during rebuild.it will be good to have such a thing in your lib

**Comment by david-hov** [comment]
Also thank you for your quick responses😉

**Comment by liodali** [comment]
in general loading should be shown only once it not means that all the widget is rebuild it again 
I will try to find a solution for that
for now i will close the issue
