### ISSUE TITLE
Android/iOS drawRoad returns empty list in `route` field

### ISSUE THREAD

**Issue by Legendorik** [liodali/osm_flutter#434]
In the latest version of the plugin (0.60.1) the return value of drawRoad function is incomplete.
I am trying to use this function as follows
```
roadInfo = await _mapController.drawRoad(
    GeoPoint(latitude: 59.871803, longitude: 30.3817244),
    GeoPoint(latitude: 59.9334042, longitude: 30.278623),
    roadOption: const RoadOption(
      roadColor: Colors.blue,
      roadWidth: 10,
      zoomInto: true,
    ),
  );
```
The API response is successful, you can see it using the link from the logs      

`D/BONUSPACK(11165): OSRMRoadManager.getRoads:https://routing.openstreetmap.de/routed-car/route/v1/driving/30.3817244000,59.8718030000;30.2786230000,59.9334042000?alternatives=false&overview=full&steps=true`

But the `roadInfo` variable does not contain data about the route. The `roadInfo.route` field is empty. All other information (like `roadInfo.distance`, `roadInfo.duration`, `roadInfo.instructions`) is present.

After downgrading the plugin (v. 0.42) the `roadInfo.route` field is present and all works correctly. Can you please check what happened?

**Comment by liodali** [comment]
it's bug the route should be not null 
i will fixed

**Comment by Legendorik** [comment]
Oh yes, the road is indeed drawn, it was my code that instantly removed it when it noticed the `route` was empty
Sorry for the misinformation

**Comment by liodali** [comment]
check our new version  `0.60.2`

**Comment by Legendorik** [comment]
Yep, it's fixed
