### ISSUE TITLE
addMarker  - null cannot be cast to non-null type kotlin.ByteArray

### ISSUE THREAD

**Issue by Gabi-mg** [liodali/osm_flutter#445]
Hello,

I am trying to add a maker but I get this error:

`
E/AndroidRuntime(30811): java.lang.NullPointerException: null cannot be cast to non-null type kotlin.ByteArray
E/AndroidRuntime(30811): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView$addMarkerManually$1.invokeSuspend(FlutterOsmView.kt:855)
E/AndroidRuntime(30811): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(30811): 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
E/AndroidRuntime(30811): 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
E/AndroidRuntime(30811): 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
E/AndroidRuntime(30811): 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
E/AndroidRuntime(30811): 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
E/AndroidRuntime(30811): 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
E/AndroidRuntime(30811): 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
E/AndroidRuntime(30811): 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
E/AndroidRuntime(30811): 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
E/AndroidRuntime(30811): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView.addMarkerManually(FlutterOsmView.kt:851)
E/AndroidRuntime(30811): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView.onMethodCall(FlutterOsmView.kt:560)
E/AndroidRuntime(30811): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/AndroidRuntime(30811): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(30811): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/AndroidRuntime(30811): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(30811): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(30811): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(30811): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(30811): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(30811): 	at android.app.ActivityThread.main(ActivityThread.java:8176)
E/AndroidRuntime(30811): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30811): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(30811): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/AndroidRuntime(30811): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@13f3f60, Dispatchers.Main.immediate]
`

The version is 0.60.3

I have observed that the method addMakerManually has icon parameter obligatory, however the parameter MarkerIcon is optional
![imagen](https://github.com/liodali/osm_flutter/assets/57829369/9cbd8fff-f5ef-48a0-87ab-091c2b7c8e28)

![imagen](https://github.com/liodali/osm_flutter/assets/57829369/e84036c6-c474-4f94-bf2f-e58f15287af1)

In fact, if I add this field, the error doesn't occur.

In ios I haven't been able to test it, I don't have a mac right now. :(

Can you check it out?

Thanks a lot

Regards

**Comment by liodali** [comment]
i will fix that

**Comment by liodali** [comment]
we made new version hotfix version : `0.60.4`
