### ISSUE TITLE
DrawRoadManually "you cannot make line with same geopoint"

### ISSUE THREAD

**Issue by JobiJoba** [liodali/osm_flutter#462]
Hi, 

I'm using the method drawRoadManually and i've the following geopoint list:

`[GeoPoint{latitude: -6.158108 , longitude: 106.2888111}, GeoPoint{latitude: -6.1582128 , longitude: 106.2887803}]` 

but when calling the method it throws the following error:

 ```
if (path.first.latitude != path.last.latitude &&
        path.first.longitude != path.last.longitude &&
        path.length < 3) {
      throw Exception("you cannot make line with same geoPoint");
    }
``` 

shouldn't be this code like this instead

 ```
if (path.first.latitude == path.last.latitude &&
        path.first.longitude == path.last.longitude &&
        path.length < 3) {
      throw Exception("you cannot make line with same geoPoint");
    }
``` 

so check if they are equals instead of different?

**Comment by liodali** [comment]
Oh im so dump 
i will fix it thnx

**Comment by JobiJoba** [comment]
Don't say that :) it happens you did a great job!!!

**Comment by liodali** [comment]
check the new version `0.70.0`

**Comment by JobiJoba** [comment]
Everything working :) 

I had to do a flutter clean for Android to work (else have an issue with the build - maybe something to write on the changelog)
