### ISSUE TITLE
IOS: Expect initial value after '=' 

### ISSUE THREAD

**Issue by gjae** [liodali/osm_flutter#468]
Hello there! I found the following error while I run my app in an Ios Simulator:
Lib version: 0.70.1 and 0.70.0

flutter doctor: 
![image](https://github.com/liodali/osm_flutter/assets/28078695/06c07c2c-218e-4b94-94c7-c69bbea4d000)

Simulator IOS 13.7

error:
Expected initial value after '=' in MyMapView.swift:171:23 
![image](https://github.com/liodali/osm_flutter/assets/28078695/6dac67cc-0bc0-4a66-aecb-f63849fb73d3)

Some idea?

**Comment by liodali** [comment]
i will do quick fix for it

**Comment by liodali** [comment]
check the new version `0.70.2`

**Comment by fonmaestro2** [comment]
Hello, same problem here.
Lib version: ```flutter_osm_plugin: ^0.70.3```
Simulator: ```Simulator iPhone 14 PRO MAX - iOs 16.4```

flutter doctor
<img width="760" alt="Captura de pantalla 2023-12-15 a las 9 27 20" src="https://github.com/liodali/osm_flutter/assets/95681324/9b9616b0-5033-41e5-a7f0-3b67fe85efef">



Error
<img width="1162" alt="Captura de pantalla 2023-12-15 a las 9 24 42" src="https://github.com/liodali/osm_flutter/assets/95681324/99432891-172f-4a95-85cf-c77c39b2f9d2">

**Comment by liodali** [comment]
try to run flutter clean and flutter pub get

**Comment by fonmaestro2** [comment]
First of all, thanks for the quick answer

I tried

```
flutter clean
flutter pub get
```

and still got error.

Also I tried

**Comment by liodali** [comment]
try to go to that location deleted and run flutter pub upgrade

**Comment by fonmaestro2** [comment]
```flutter pub upgrade```  output  ```No dependencies changed in ...``` 

And still got error.

What location deleted?

**Comment by liodali** [comment]
sorry for late reply i mean in .pub-cache remove the latest version and try to get it again

**Comment by fonmaestro2** [comment]
No worries, thanks for your time

I remove ```.pub_cache``` folder.
Then ```flutter clean```, and then ```flutter pub get```

and still get the same error.

It's very weird. Anyway... thanks for your time

**Comment by fonmaestro2** [comment]
Only if its help you: I tried to remove all dart&flutter installations  and reinstall. Then i create a new empty/fresh new project and I get the same errror.

I don't know if the bug is related with my local installation. Or something related with cache folders.

**Comment by AhmedAbouelkher** [comment]
@liodali 
The issue fix is not present in the latest version `v0.7.4`.
According to this [commit](https://github.com/liodali/osm_flutter/commit/5f0141a4b9672aae68ed8d0fd009ecb672c9a4f2) and the current production version doesn't include this fix.

**Comment by liodali** [comment]
try the latest dev version : `1.0.0-dev`

**Comment by andreacona96** [comment]
Hi @liodali, I solved by replacing line 172 in MyMapView.swift
let url = if (fromAsset){
                Bundle.main.url(forAuxiliaryExecutable: dynamicOSMPath!)!
            } else {
                URL(string: urlStyle)!
            }

whit this

var url: URL {
                if (fromAsset){
                    return Bundle.main.url(forAuxiliaryExecutable: dynamicOSMPath!)!
                } else {
                    return URL(string: urlStyle)!
                }
            } 

Can you release a new version with this fix?

**Comment by liodali** [comment]
use our dev version we dont use tangram sdk for ios anymore

**Comment by andreacona96** [comment]
@liodali if I use version 1.0.0-dev I no longer have the markerOption attribute in OSMOption

**Comment by georgno** [comment]
> @liodali if I use version 1.0.0-dev I no longer have the markerOption attribute in OSMOption

any news on that? did you find a workaround?

**Comment by liodali** [comment]
i removed markerOption that contain home marker you can manage them freely in you app without need the package but maybe next version i can see how to return it if i find good way to manage it because it make things little bit complicated
trying to create more generic apis first them i can focus in some usefull use cases like home location or staff similar
