### ISSUE TITLE
drawMultipleRoad color not working properly 

### ISSUE THREAD

**Issue by AntonLie** [liodali/osm_flutter#472]
Hello, I tried to implement drawMultipleRoad with different colors. but that's not working properly 

road with colors orange not showing up.

### Code
<img width="391" alt="Screenshot 2023-11-17 at 13 58 18" src="https://github.com/liodali/osm_flutter/assets/89154283/3f359edd-1a34-4d84-858a-254e4a9247ef">

### Result
<img width="1152" alt="Screenshot 2023-11-17 at 14 01 19" src="https://github.com/liodali/osm_flutter/assets/89154283/44457227-0839-4304-883f-09dcb24b6160">

**Comment by JobiJoba** [comment]
It shows the road with the Red color instead of Orange? That's what you mean? 

Or the orange road is not drawn ? 

If you change the order and put the orange road at the end what's happening?

**Comment by AntonLie** [comment]
Sorry for not clearly description,
as you can see like this one orange and purple road colors not showing up, but road correct destination.

### Code: 
<img width="473" alt="Screenshot 2023-11-17 at 14 13 54" src="https://github.com/liodali/osm_flutter/assets/89154283/c115c5ab-caf0-4a84-a0c5-f38566e32f2c">

### Result: 
<img width="1147" alt="Screenshot 2023-11-17 at 14 14 21" src="https://github.com/liodali/osm_flutter/assets/89154283/d04e797b-7b62-4c3b-a366-1bba588adc65">

**Comment by JobiJoba** [comment]
It seems that commonRoadOption is overriding the colors of individual config


There is comment saying: 

` /// [commonRoadOption]  : (MultiRoadOption) common road config that can apply to all roads that doesn't define any inner roadOption`

On which platform do you have that? It look like web but could be tablet?

**Comment by JobiJoba** [comment]
Looking into the web code

  ```
Future<List<RoadInfo>> drawMultipleRoad(
    List<MultiRoadConfiguration> configs, {
    MultiRoadOption commonRoadOption = const MultiRoadOption.empty(),
  }) async {
    List<Future<RoadInfo>> futureRoads = [];
    configs.forEach((config) {
      futureRoads.add(
        drawRoad(
          config.startPoint,
          config.destinationPoint,
          interestPoints: config.intersectPoints,
          roadOption: commonRoadOption,
        ),
      );
    });
    final infos = await Future.wait(futureRoads);
    infos.forEach((roadInfo) {
      roadsWebCache[roadInfo.key] = roadInfo;
    });
    return infos;
  }
```

roadOption is overriden with commonRoad options, that's why it happens :)

**Comment by AntonLie** [comment]
I see, I develop on the web, but @JobiJoba if I remove commonRoadOption,

The road turns to green color.

### Screenshot
<img width="1148" alt="Screenshot 2023-11-17 at 14 24 34" src="https://github.com/liodali/osm_flutter/assets/89154283/7f0e0083-3e5b-4454-9f22-6f0fc3bc6dba">

**Comment by JobiJoba** [comment]
it will take the default roadConfiguration  which is 
```

 const MultiRoadOption.empty()
      : this.roadType = RoadType.car,
        super(
          roadColor: Colors.green,
          zoomInto: false,
        );
```

green by default

**Comment by JobiJoba** [comment]
you can try to point the package on the PR #473

**Comment by AntonLie** [comment]
ok let me check bro

Thanks a lot bro

**Comment by AntonLie** [comment]
btw how to try to point to your PR ?

**Comment by liodali** [comment]
yeah tonight i will check everything and release new version

**Comment by JobiJoba** [comment]
hehe sorry I don't know how to point to the PR directly :) the module have different package :) But let liodali review first, I might get wrong somewhere

**Comment by AntonLie** [comment]
hahaha

Thanks, guys really appreciate it!

**Comment by AntonLie** [comment]
Hello @liodali any update for version?

**Comment by liodali** [comment]
check version 0.70.2

**Comment by AntonLie** [comment]
cool thanks bro
