### ISSUE TITLE
Icon Widget in Marker Icon not showing up

### ISSUE THREAD

**Issue by AntonLie** [liodali/osm_flutter#474]
Hello, I have a question about implementing IconWidget.

I tried like this but the marker not showing up.

### Code
<img width="457" alt="Screenshot 2023-11-17 at 16 00 49" src="https://github.com/liodali/osm_flutter/assets/89154283/be348ac9-3e27-45ac-8e01-7d64f0288df6">

**Comment by liodali** [comment]
for now avoid putting text with icon 
I will add way to show text with iconMarker

**Comment by AntonLie** [comment]
any update @liodali ?

**Comment by liodali** [comment]
you can put that column in sizedbox i think will work but not properly
for now im trying to fix some issues for ios
if you want make your icon marker small where it cann fit icon + text

**Comment by AntonLie** [comment]
Ok Thanks @liodali ,

Sizedbox is working 👍🏻
