### ISSUE TITLE
How to Disabled scroll or pointer-events: none with overlay?

### ISSUE THREAD

**Issue by AntonLie** [liodali/osm_flutter#475]
Hello,
I have an overlay widget but OSMFlutter still can drag maps.

how to disable drag?

btw I using Stack with Positioned, and i already tried use IgnorePointer but still not working.

Thanks 

### Screenshot
<img width="1155" alt="Screenshot 2023-11-18 at 12 54 38" src="https://github.com/liodali/osm_flutter/assets/89154283/fedc0824-269a-45a6-871d-74e0683a5a45">

**Comment by liodali** [comment]
you mean disable drag in the Map when you show that overlay ?

**Comment by AntonLie** [comment]
Yes @liodali

**Comment by liodali** [comment]
check this : https://github.com/flutter/flutter/issues/72273
