### ISSUE TITLE
Possible to add arrow in road ?

### ISSUE THREAD

**Issue by AntonLie** [liodali/osm_flutter#476]
Hello @liodali,
it's possible to add arrows at the end road? 

### Example
<img width="604" alt="Screenshot 2023-11-18 at 15 26 14" src="https://github.com/liodali/osm_flutter/assets/89154283/bdead57c-5a49-466b-90e1-8773669d3b97">

### Existing 
<img width="1148" alt="Screenshot 2023-11-18 at 15 26 50" src="https://github.com/liodali/osm_flutter/assets/89154283/defb39b9-10d6-4410-826f-a5efb28f3d4b">

**Comment by liodali** [comment]
currently no 
but i will see how we can do this as feature for draw custom shape

**Comment by AntonLie** [comment]
any update bro @liodali with the custom shape?

**Comment by AntonLie** [comment]
reference: https://github.com/slutske22/leaflet-arrowheads

**Comment by liodali** [comment]
i will check your link and see how to integrated
give me sometime sorry

**Comment by dilipharish** [comment]
arrows is really interesting feature bro, please make it , May god give u Strength to do that

**Comment by liodali** [comment]
I have a question you want just the arrow or curved line like you showed me in the screenshot ?
