### ISSUE TITLE
It's Possible to add Popover/ Tooltip in Road when Hover / Click ?

### ISSUE THREAD

**Issue by AntonLie** [liodali/osm_flutter#479]
Hello @liodali ,

it's possible to add popover in road when event hover / click ? 

<img width="473" alt="Screenshot 2023-11-21 at 08 21 54" src="https://github.com/liodali/osm_flutter/assets/89154283/d1581941-695f-44e0-9d88-d06b7bd8b9ce">

Thanks

**Comment by liodali** [comment]
for now no
it little complicated to do it
but it will be nice feature to add 
sorry for that

**Comment by AntonLie** [comment]
all right thanks @liodali

**Comment by AntonLie** [comment]
btw @liodali 
how to implement onRoadTap ?

![Screenshot 2023-11-21 at 21 39 17](https://github.com/liodali/osm_flutter/assets/89154283/080a8434-b1d4-469b-a322-e3016e4ed68b)

**Comment by liodali** [comment]
add 
`with OSMMixinObserver`  to your widget
and call any method you want
for mapController
in initstate 
call 
`controller.addObserver(this)`

**Comment by AntonLie** [comment]
btw can we use onRoadTap to get the specific road we click?

**Comment by liodali** [comment]
yeah sure you get the information of that road 
start point last distance 
some other also

**Comment by AntonLie** [comment]
let's say I clicked on Purple road 

why I get different hex color like "#66bbe"

<img width="532" alt="Screenshot 2023-11-21 at 22 08 13" src="https://github.com/liodali/osm_flutter/assets/89154283/9e18a3d2-3b77-4728-b48e-be69efd09450">

**Comment by liodali** [comment]
thats the identifier of  the road has nothing to with the color just used uniquekey from flutter to keep track of it

**Comment by liodali** [comment]
thats happen internally from our api 
when you call drawMultiRoad before return roadInfor for each road we associete to it key
maybe I will add name for it at least you can used also as link for it

**Comment by AntonLie** [comment]
sure bro @liodali pls add ✌🏻 
really appreciate it!
