### ISSUE TITLE
Custom Layer Not Working Properly

### ISSUE THREAD

**Issue by AntonLie** [liodali/osm_flutter#480]
Hello, I tried to add a custom layer but seems not working.

### Code
<img width="437" alt="Screenshot 2023-11-22 at 19 45 31" src="https://github.com/liodali/osm_flutter/assets/89154283/979e37d7-8868-456d-8773-e619b37ffe6a">

### Result
![Screenshot 2023-11-22 at 19 46 21](https://github.com/liodali/osm_flutter/assets/89154283/ae0842a3-f80b-4a29-aeae-f5b4b3881997)

### Expectation
https://tile.opentopomap.org/#map=9/50.2244/17.0178

**Comment by liodali** [comment]
you should change the url to this

`https://tile.opentopomap.org/{z}/{x}/{y}`

you can check details 
on wiki.openstreetmap.org/wiki/OpenTopoMap

**Comment by AntonLie** [comment]
sorry, nothing change after i change url to `https://tile.opentopomap.org/{z}/{x}/{y}`

**Comment by liodali** [comment]
sorry try this : 
```
CustomTile(
        sourceName: "opentopomap",
        tileExtension: ".png",
        minZoomLevel: 2,
        maxZoomLevel: 19,
        urlsServers: [
          "https://a.tile.opentopomap.org/",
          "https://b.tile.opentopomap.org/",
          "https://c.tile.opentopomap.org/",
        ],
        tileSize: 256,
      )

```

**Comment by AntonLie** [comment]
Hello @liodali ,
I tried but still not working 

cannot use only string because libs have  type

<img width="584" alt="Screenshot 2023-11-25 at 17 23 55" src="https://github.com/liodali/osm_flutter/assets/89154283/f4ad54ad-98e8-4842-af0b-aceb70ab5c8c">

**Comment by liodali** [comment]
dont add /{z}/{x}/{y}.png to the url

**Comment by AntonLie** [comment]
ok done but still not working

here's my url

https://maps.geoapify.com/v1/tile/klokantech-basic?apiKey=

**Comment by AntonLie** [comment]
<img width="533" alt="Screenshot 2023-11-25 at 17 40 15" src="https://github.com/liodali/osm_flutter/assets/89154283/7da296ce-c2b2-4f43-8729-ab3e595873d9">

**Comment by liodali** [comment]
> ok done but still not working
> 
> here's my url
> 
> https://maps.geoapify.com/v1/tile/klokantech-basic?apiKey=

that url doesnt contain z,x,y
do you have any docs link that i can check to help you more

**Comment by AntonLie** [comment]
this one bro @liodali 
https://apidocs.geoapify.com/

so need z,x,y right?

**Comment by liodali** [comment]
```
CustomTile(
        sourceName: "geoapify",
        tileExtension: ".png",
        minZoomLevel: 2,
        maxZoomLevel: 19,
        urlsServers: [
          TileURLs(
            url: "https://maps.geoapify.com/v1/tile/osm-carto/",
          )
        ],
        tileSize: 256,
        keyApi: MapEntry(
          "apiKey",
         YOURKEY,
        ),
      )

```

**Comment by AntonLie** [comment]
Still not changed bro 

<img width="403" alt="Screenshot 2023-11-26 at 00 02 29" src="https://github.com/liodali/osm_flutter/assets/89154283/bc708336-9998-480f-ac4a-7dfac327b357">

**Comment by liodali** [comment]
i will do a quick fix to night sorry for being late to fix it

**Comment by AntonLie** [comment]
Sorry For Late Reply


<img width="1022" alt="Screenshot 2023-11-29 at 12 26 12" src="https://github.com/liodali/osm_flutter/assets/89154283/b81aecba-d868-4c68-ae42-5a88c925f04a">

here's my Map Controller Code : 

<img width="539" alt="Screenshot 2023-11-29 at 12 27 24" src="https://github.com/liodali/osm_flutter/assets/89154283/cb6a67c8-aaa3-42e3-bac5-3494f6b1a016">

**Comment by liodali** [comment]
but maybe that raster is the same as default 
did you try another raster type as you can see in my screenshot i used /osm-liberty/..
