### ISSUE TITLE
Map showing grey screen in release web

### ISSUE THREAD

**Issue by AntonLie** [liodali/osm_flutter#487]
Hello @liodali ,
i got error grey screen in release web.

is anything i can do to fix this error? 

thanks.

### Screenshot
![image](https://github.com/liodali/osm_flutter/assets/89154283/db922a9a-72e5-4e16-8dc9-bb2c81d936ed)

**Comment by liodali** [comment]
any logs ?

**Comment by AntonLie** [comment]
@liodali here's 

![image](https://github.com/liodali/osm_flutter/assets/89154283/dd6e76c0-c82d-41a6-9b3d-9edecd356609)

**Comment by liodali** [comment]
are you using local tile server or anything can you share any code simple ?

**Comment by AntonLie** [comment]
Yes is working fine in debug mode, but in release mode got error 

### Code
<img width="956" alt="Screenshot 2023-12-09 at 07 25 58" src="https://github.com/liodali/osm_flutter/assets/89154283/432fc51b-dab9-4431-8f88-183594da8529">

**Comment by liodali** [comment]
try to configure https for your deployed server if possible

**Comment by AntonLie** [comment]
hmm did you mean need https to deploy this libs?

it's not working if no https?

**Comment by AntonLie** [comment]
btw @liodali , i tried to deploy in nginx local 

it's working well

### Screenshot
![image](https://github.com/liodali/osm_flutter/assets/89154283/a8e70949-7af7-4aa8-bd9f-598d0d69ec65)

**Comment by liodali** [comment]
in you image log can you expand the uncaught error to see more what it says
and also in general browser is smart enough to differentiate between localhost and deployed
for ssl certificate try to use letsencrypt it can used easly with ngnix
