### ISSUE TITLE
No pointer on showSimplePickerLocation()

### ISSUE THREAD

**Issue by Alisofin** [liodali/osm_flutter#492]
Hello, I found a new issue on the simple picker: the pointer (icon) at location initPosition is not showing up. It doesn't work on iOS and Android. My code is:
// Show the map and await for a click
    var newLocation = await showSimplePickerLocation(
        context: context,
        isDismissible: true,
        title: "Set bird feeder location",
        textConfirmPicker: "Confirm",
        initPosition: _cameraLocation,
        zoomOption: ZoomOption(initZoom: 10),
        radius: 8);

**Comment by Alisofin** [comment]
As a follow up of my previous comment, the confirm button doesn't work either.

**Comment by liodali** [comment]
yeah that widget i will update with new API because 
for some reason i dont need to built native Ui for it 
so I changed it to be able to add custom flutter where you can add animated picker marker

**Comment by Alisofin** [comment]
So the fix will be included in your next release or will you have a dev version before ?

**Comment by liodali** [comment]
i will update the widget in dev version before here we can test it together
i will try to do update today or tomorrow

**Comment by liodali** [comment]
check our latest version `1.0.0-dev.4`
we improved the picker dialog
we added custom widget where you can put any picker or you can use our existing widget
you see the example for more details

**Comment by Alisofin** [comment]
Works fine, thanks again for your reactivity.
