### ISSUE TITLE
delay in get picklocation

### ISSUE THREAD

**Issue by ahmadsajadi** [liodali/osm_flutter#5]
when i use below code  for select a postion not work correctly.

 GeoPoint point= await osmKey.currentState.selectPosition();
          print(point);

**Comment by liodali** [comment]
for selectPosition, i make longPress

**Comment by ahmadsajadi** [comment]
Which part can I see?

**Comment by ahmadsajadi** [comment]
i have some errors when running again

D/OpenGLRenderer(19607):   HWUI Binary is  disabled
E/flutter (19607): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:flutter/src/rendering/proxy_box.dart': Failed assertion: line 2961 pos 12: '!debugNeedsPaint': is not true.
E/flutter (19607): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
E/flutter (19607): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
E/flutter (19607): #2      RenderRepaintBoundary.toImage (package:flutter/src/rendering/proxy_box.dart:2961:12)
E/flutter (19607): #3      _OsmController._capturePng (package:flutter_osm_plugin/src/osm_flutter.dart:423:37)
E/flutter (19607): #4      _OsmController.customMarker (package:flutter_osm_plugin/src/osm_flutter.dart:394:28)
E/flutter (19607): #5      OSMFlutterState.changeIconMarker (package:flutter_osm_plugin/src/osm_flutter.dart:180:31)
E/flutter (19607): #6      OSMFlutterState.initState.<anonymous closure> (package:flutter_osm_plugin/src/osm_flutter.dart:121:15)
E/flutter (19607): #7      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (19607): #8      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (19607): #9      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter (19607): #10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter (19607): #11     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter (19607): #12     Future._completeWithValue (dart:async/future_impl.dart:526:5)

**Comment by liodali** [comment]
ah i see the error in markerIcon, can you provide me part of the code to reproduce the error ,
and for selectPosition, i will remove longPress and i will make it with simple click ,sorry because i didn't mention in docs

**Comment by ahmadsajadi** [comment]
Yes, Sure

**Comment by ahmadsajadi** [comment]
import 'package:flutter/material.dart';
import '../config_services.dart';
//HomePage_Show_Services



class HomePage_Show_Services extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
  static startIntent(BuildContext context) {
    Navigator.push(
      context,
      MaterialPageRoute(builder: (context) => HomePage_Show_Services()),
    );
  }
}

class _MyAppState extends State<HomePage_Show_Services> {
  GlobalKey<OSMFlutterState> osmKey;
  GlobalKey<ScaffoldState> scaffoldKey;

  @override
  void initState() {
    super.initState();
    osmKey = GlobalKey<OSMFlutterState>();
    scaffoldKey = GlobalKey<ScaffoldState>();
    Future.delayed(const Duration(milliseconds: 500), () {
      setState(() {
        osmKey.currentState.changeLocation(GeoPoint(latitude: 36.304541, longitude: 59.527368));
      });

    });
  }

  @override
  Widget build(BuildContext loncontext) {
    return MaterialApp(
      home: Scaffold(
        key: scaffoldKey,
        appBar: AppBar(
          title: const Text('OSM Plugin app'),
          actions: <Widget>[
            IconButton(
              onPressed: () async {
                try {
                  await osmKey.currentState.drawRoad(
                    GeoPoint(latitude: 36.301000, longitude: 59.527374),
                    GeoPoint(latitude: 36.300000, longitude: 59.527374),);
                } on RoadException catch (e) {
                  scaffoldKey.currentState.showSnackBar(
                    SnackBar(
                      content: Text(
                        "${e.errorMessage()}",
                      ),
                    ),
                  );
                }
              },
              icon: Icon(Icons.map),
            ),
            IconButton(
              onPressed: () async {
                GeoPoint p = await osmKey.currentState.selectPosition();
                scaffoldKey.currentState.showSnackBar(
                  SnackBar(
                    content: Text(
                      "the picked position:lat ${p.latitude},lon ${p.longitude}",
                    ),
                  ),
                );
              },
              icon: Icon(Icons.search),
            ),
            IconButton(
              icon: Icon(Icons.refresh),
              onPressed: () async {
                await osmKey.currentState.setStaticPosition([
                  GeoPoint(latitude: 36.304541, longitude: 59.527368),
                  GeoPoint(latitude: 36.301000, longitude: 59.527374),
                  GeoPoint(latitude: 36.300000, longitude: 59.527374),

                ], "static");
                scaffoldKey.currentState.showSnackBar(SnackBar(
                  content: Text("static point changed"),
                  duration: Duration(seconds: 10),
                ));
              },
            )
          ],
        ),
        body: Container(
          child: OSMFlutter(
            key: osmKey,
            currentLocation: false,
            onGeoPointClicked: (geoPoint) {
              scaffoldKey.currentState.showSnackBar(
                SnackBar(
                  content: Text(
                    "lat:${geoPoint.latitude},lon${geoPoint.longitude}",
                  ),
                  action: SnackBarAction(
                    onPressed: () =>
                        scaffoldKey.currentState.hideCurrentSnackBar(),
                    label: "hide",
                  ),
                ),
              );
            },
            staticPoints: [
              StaticPositionGeoPoint(
                "static",
                MarkerIcon(
                  icon: Icon(
                    Icons.train,
                    color: Colors.green,
                    size: 48,
                  ),
                ),
                [
                  GeoPoint(latitude: 47.4333594, longitude: 8.4680184),
                  GeoPoint(latitude: 47.4317782, longitude: 8.4716146),
                ],
              ),
            ],
            road: Road(
                startIcon: MarkerIcon(
                  icon: Icon(
                    Icons.person,
                    size: 64,
                    color: Colors.brown,
                  ),
                ),
                roadColor: Colors.yellowAccent),
            markerIcon: MarkerIcon(
              icon: Icon(
                Icons.person_pin_circle,
                color: Colors.blue,
                size: 56,
              ),
            ),
            trackMyPosition: false,
            initPosition: GeoPoint(latitude: 47.4358055, longitude: 8.4737324),
            useSecureURL: false,
          ),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () async {
            GeoPoint p=   await osmKey.currentState.selectPosition();
            scaffoldKey.currentState.showSnackBar(
              SnackBar(
                content: Text(
                  "lat:"+p.toString(),
                ),
                action: SnackBarAction(
                  onPressed: () =>
                      scaffoldKey.currentState.hideCurrentSnackBar(),
                  label: "hide",
                ),
              ),
            );
          },

          child: Icon(Icons.my_location),
        ),
        floatingActionButtonLocation: FloatingActionButtonLocation.startTop,
      ),
    );
  }
  @override
  void dispose() {
    // Never called
    osmKey.currentState.dispose();
    print("Disposing first route");
    super.dispose();
  }
}

**Comment by ahmadsajadi** [comment]
`
import 'package:flutter/material.dart';
import '../config_services.dart';
//HomePage_Show_Services



class HomePage_Show_Services extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
  static startIntent(BuildContext context) {
    Navigator.push(
      context,
      MaterialPageRoute(builder: (context) => HomePage_Show_Services()),
    );
  }
}

class _MyAppState extends State<HomePage_Show_Services> {
  GlobalKey<OSMFlutterState> osmKey;
  GlobalKey<ScaffoldState> scaffoldKey;

  @override
  void initState() {
    super.initState();
    osmKey = GlobalKey<OSMFlutterState>();
    scaffoldKey = GlobalKey<ScaffoldState>();
    Future.delayed(const Duration(milliseconds: 500), () {
      setState(() {
        osmKey.currentState.changeLocation(GeoPoint(latitude: 36.304541, longitude: 59.527368));
      });

    });
  }

  @override
  Widget build(BuildContext loncontext) {
    return MaterialApp(
      home: Scaffold(
        key: scaffoldKey,
        appBar: AppBar(
          title: const Text('OSM Plugin app'),
          actions: <Widget>[
            IconButton(
              onPressed: () async {
                try {
                  await osmKey.currentState.drawRoad(
                    GeoPoint(latitude: 36.301000, longitude: 59.527374),
                    GeoPoint(latitude: 36.300000, longitude: 59.527374),);
                } on RoadException catch (e) {
                  scaffoldKey.currentState.showSnackBar(
                    SnackBar(
                      content: Text(
                        "${e.errorMessage()}",
                      ),
                    ),
                  );
                }
              },
              icon: Icon(Icons.map),
            ),
            IconButton(
              onPressed: () async {
                GeoPoint p = await osmKey.currentState.selectPosition();
                scaffoldKey.currentState.showSnackBar(
                  SnackBar(
                    content: Text(
                      "the picked position:lat ${p.latitude},lon ${p.longitude}",
                    ),
                  ),
                );
              },
              icon: Icon(Icons.search),
            ),
            IconButton(
              icon: Icon(Icons.refresh),
              onPressed: () async {
                await osmKey.currentState.setStaticPosition([
                  GeoPoint(latitude: 36.304541, longitude: 59.527368),
                  GeoPoint(latitude: 36.301000, longitude: 59.527374),
                  GeoPoint(latitude: 36.300000, longitude: 59.527374),

                ], "static");
                scaffoldKey.currentState.showSnackBar(SnackBar(
                  content: Text("static point changed"),
                  duration: Duration(seconds: 10),
                ));
              },
            )
          ],
        ),
        body: Container(
          child: OSMFlutter(
            key: osmKey,
            currentLocation: false,
            onGeoPointClicked: (geoPoint) {
              scaffoldKey.currentState.showSnackBar(
                SnackBar(
                  content: Text(
                    "lat:${geoPoint.latitude},lon${geoPoint.longitude}",
                  ),
                  action: SnackBarAction(
                    onPressed: () =>
                        scaffoldKey.currentState.hideCurrentSnackBar(),
                    label: "hide",
                  ),
                ),
              );
            },
            staticPoints: [
              StaticPositionGeoPoint(
                "static",
                MarkerIcon(
                  icon: Icon(
                    Icons.train,
                    color: Colors.green,
                    size: 48,
                  ),
                ),
                [
                  GeoPoint(latitude: 47.4333594, longitude: 8.4680184),
                  GeoPoint(latitude: 47.4317782, longitude: 8.4716146),
                ],
              ),
            ],
            road: Road(
                startIcon: MarkerIcon(
                  icon: Icon(
                    Icons.person,
                    size: 64,
                    color: Colors.brown,
                  ),
                ),
                roadColor: Colors.yellowAccent),
            markerIcon: MarkerIcon(
              icon: Icon(
                Icons.person_pin_circle,
                color: Colors.blue,
                size: 56,
              ),
            ),
            trackMyPosition: false,
            initPosition: GeoPoint(latitude: 47.4358055, longitude: 8.4737324),
            useSecureURL: false,
          ),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () async {
            GeoPoint p=   await osmKey.currentState.selectPosition();
            scaffoldKey.currentState.showSnackBar(
              SnackBar(
                content: Text(
                  "lat:"+p.toString(),
                ),
                action: SnackBarAction(
                  onPressed: () =>
                      scaffoldKey.currentState.hideCurrentSnackBar(),
                  label: "hide",
                ),
              ),
            );
          },

          child: Icon(Icons.my_location),
        ),
        floatingActionButtonLocation: FloatingActionButtonLocation.startTop,
      ),
    );
  }
  @override
  void dispose() {
    // Never called
    osmKey.currentState.dispose();
    print("Disposing first route");
    super.dispose();
  }
}

`

**Comment by ahmadsajadi** [comment]
```
import 'package:flutter/material.dart';
import '../config_services.dart';
//HomePage_Show_Services



class HomePage_Show_Services extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
  static startIntent(BuildContext context) {
    Navigator.push(
      context,
      MaterialPageRoute(builder: (context) => HomePage_Show_Services()),
    );
  }
}

class _MyAppState extends State<HomePage_Show_Services> {
  GlobalKey<OSMFlutterState> osmKey;
  GlobalKey<ScaffoldState> scaffoldKey;

  @override
  void initState() {
    super.initState();
    osmKey = GlobalKey<OSMFlutterState>();
    scaffoldKey = GlobalKey<ScaffoldState>();
    Future.delayed(const Duration(milliseconds: 500), () {
      setState(() {
        osmKey.currentState.changeLocation(GeoPoint(latitude: 36.304541, longitude: 59.527368));
      });

    });
  }

  @override
  Widget build(BuildContext loncontext) {
    return MaterialApp(
      home: Scaffold(
        key: scaffoldKey,
        appBar: AppBar(
          title: const Text('OSM Plugin app'),
          actions: <Widget>[
            IconButton(
              onPressed: () async {
                try {
                  await osmKey.currentState.drawRoad(
                    GeoPoint(latitude: 36.301000, longitude: 59.527374),
                    GeoPoint(latitude: 36.300000, longitude: 59.527374),);
                } on RoadException catch (e) {
                  scaffoldKey.currentState.showSnackBar(
                    SnackBar(
                      content: Text(
                        "${e.errorMessage()}",
                      ),
                    ),
                  );
                }
              },
              icon: Icon(Icons.map),
            ),
            IconButton(
              onPressed: () async {
                GeoPoint p = await osmKey.currentState.selectPosition();
                scaffoldKey.currentState.showSnackBar(
                  SnackBar(
                    content: Text(
                      "the picked position:lat ${p.latitude},lon ${p.longitude}",
                    ),
                  ),
                );
              },
              icon: Icon(Icons.search),
            ),
            IconButton(
              icon: Icon(Icons.refresh),
              onPressed: () async {
                await osmKey.currentState.setStaticPosition([
                  GeoPoint(latitude: 36.304541, longitude: 59.527368),
                  GeoPoint(latitude: 36.301000, longitude: 59.527374),
                  GeoPoint(latitude: 36.300000, longitude: 59.527374),

                ], "static");
                scaffoldKey.currentState.showSnackBar(SnackBar(
                  content: Text("static point changed"),
                  duration: Duration(seconds: 10),
                ));
              },
            )
          ],
        ),
        body: Container(
          child: OSMFlutter(
            key: osmKey,
            currentLocation: false,
            onGeoPointClicked: (geoPoint) {
              scaffoldKey.currentState.showSnackBar(
                SnackBar(
                  content: Text(
                    "lat:${geoPoint.latitude},lon${geoPoint.longitude}",
                  ),
                  action: SnackBarAction(
                    onPressed: () =>
                        scaffoldKey.currentState.hideCurrentSnackBar(),
                    label: "hide",
                  ),
                ),
              );
            },
            staticPoints: [
              StaticPositionGeoPoint(
                "static",
                MarkerIcon(
                  icon: Icon(
                    Icons.train,
                    color: Colors.green,
                    size: 48,
                  ),
                ),
                [
                  GeoPoint(latitude: 47.4333594, longitude: 8.4680184),
                  GeoPoint(latitude: 47.4317782, longitude: 8.4716146),
                ],
              ),
            ],
            road: Road(
                startIcon: MarkerIcon(
                  icon: Icon(
                    Icons.person,
                    size: 64,
                    color: Colors.brown,
                  ),
                ),
                roadColor: Colors.yellowAccent),
            markerIcon: MarkerIcon(
              icon: Icon(
                Icons.person_pin_circle,
                color: Colors.blue,
                size: 56,
              ),
            ),
            trackMyPosition: false,
            initPosition: GeoPoint(latitude: 47.4358055, longitude: 8.4737324),
            useSecureURL: false,
          ),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () async {
            GeoPoint p=   await osmKey.currentState.selectPosition();
            scaffoldKey.currentState.showSnackBar(
              SnackBar(
                content: Text(
                  "lat:"+p.toString(),
                ),
                action: SnackBarAction(
                  onPressed: () =>
                      scaffoldKey.currentState.hideCurrentSnackBar(),
                  label: "hide",
                ),
              ),
            );
          },

          child: Icon(Icons.my_location),
        ),
        floatingActionButtonLocation: FloatingActionButtonLocation.startTop,
      ),
    );
  }
  @override
  void dispose() {
    // Never called
    osmKey.currentState.dispose();
    print("Disposing first route");
    super.dispose();
  }
}
```

**Comment by ahmadsajadi** [comment]
What method should I use to select the geopoint?

**Comment by ahmadsajadi** [comment]
The following code does not work, and it has an error.

```
 @override
  void dispose() {
    // Never called
    osmKey.currentState.dispose();
    print("Disposing first route");
    super.dispose();
  }  
```



error ............
The method 'dispose' was called on null.
Receiver: null
Tried calling: dispose()

**Comment by liodali** [comment]
i will make update to fix some error
answer of  you  questions
1) for example ,in your app ,you want to give user possibility to create road, you need 2 position start position and end position,with selectPosition you can give user posibility to select position in map
2) for dispose,don't use it,flutter will make dispose when widget no longer available

**Comment by ahmadsajadi** [comment]
ok thanks a lot

**Comment by liodali** [comment]
i already make an update,check it,
if error persist, tell me

**Comment by ahmadsajadi** [comment]
The bug was fixed
but selectPosition() Nothing comes back

**Comment by ahmadsajadi** [comment]
This method returns nothing
```
  Future<GeoPoint> pickLocation() async {
    try {
      Map<String, dynamic> map =
          await _channel.invokeMapMethod("user#pickPosition", null);
      return GeoPoint(latitude: map["lat"], longitude: map["lon"]);
    } on PlatformException catch (e) {
      throw GeoPointException(msg: e.message);
    }
  }
```

**Comment by liodali** [comment]
when you make selectPosition, you need to click on screen, then you will see new marker on position that you clicked on
after that you will receive geopoint

**Comment by ahmadsajadi** [comment]
Yes, I didn't use it properly

**Comment by ahmadsajadi** [comment]
thanks brother

**Comment by ahmadsajadi** [comment]
good luck

**Comment by ahmadsajadi** [comment]
Will this possibility be added for ios as well?

**Comment by liodali** [comment]
unfortunately,for iOS is more complicated,but i already working on it, it will  be available soon

**Comment by ahmadsajadi** [comment]
ok thank you 

i should working on it for ios.
