### ISSUE TITLE
onGeoPointClicked doesn't work on iOS

### ISSUE THREAD

**Issue by tmp78** [liodali/osm_flutter#510]
In 1.0.0-rc.5 and 1.0.0-rc.6 onGeoPointClicked method doesn't work as expected on iOS. I'm not sure about earlier release candidate versions, but it definitely worked in the stable version.
Sample code:
```dart
return OSMFlutter(
      onGeoPointClicked: (geoPoint) {

        print(geoPoint);

      },
      //the rest of the code
      );
```
The result on an Android device:
```
GeoPoint{latitude: 52.2319058 , longitude: 19.3633781}
```
The result on an iOS device after clicking on the same geopoint:
```
GeoPoint{latitude: 0.00046920719304921477 , longitude: 0.0001739441850183654}
```

**Comment by liodali** [comment]
i will do quick fix

**Comment by liodali** [comment]
in ios folder,open terminal and run pod update 
then the issue will be fixed
I update the our ios framework used in our plugin

**Comment by tmp78** [comment]
@liodali, thanks for your help.
It works now.
