### ISSUE TITLE
Custom Tile Layer removes Map attribution on Web

### ISSUE THREAD

**Issue by derklaro** [liodali/osm_flutter#514]
Probably due to https://github.com/liodali/osm_flutter/blob/07800ad85222ed7335c125cae683dae49cb36952/flutter_osm_web/lib/src/asset/map.html#L156-L163

Not sure why the attribution was disabled there, but it would be really nice to get control if the attributation should still be enabled :)

Currenctly running version 1.0.0-rc.6:
![image](https://github.com/liodali/osm_flutter/assets/40468651/defab3e6-406a-42aa-8f6f-3252ae7cda20)

**Comment by liodali** [comment]
you're right i will fix that

**Comment by liodali** [comment]
I fixed in our new version `1.0.0`
