### ISSUE TITLE
Fix the bug in the drawRoadManually function.

### ISSUE THREAD

**Issue by spaiki007** [liodali/osm_flutter#518]
When you call this function without roadBorderWidth.

``` 
-- Flutter
await controller.drawRoadManually(
  road, 
  RoadOption(
    roadWidth: 10,
    //roadBorderWidth: 0.1,
    roadColor: roadColor,
    zoomInto: false,
  ),
);
```

then in the function

```
-- Kotlin
 private fun drawRoadManually(call: MethodCall, result: MethodChannel.Result) {

        ...

        // args["roadBorderWidth"] == null // true
        val roadBorderWidth = (args["roadBorderWidth"] as Double).toFloat()

        ...

```

**Please make roadBorderWidth either mandatory or provide a default value. flutter_osm_plugin: ^1.0.0**

The same applies to roadBorderColor: please make it either mandatory or provide a default value.

**Comment by liodali** [comment]
oh my bad! i will do quick fix

**Comment by liodali** [comment]
check our new version `1.0.1`

**Comment by spaiki007** [comment]
Yes, everything works great, but please do the same for **roadBorderColor**.
