### ISSUE TITLE
connect to offline server map

### ISSUE THREAD

**Issue by masdercoder** [liodali/osm_flutter#524]
I made the offline tiles with the QGIS software and I have several folders with different tiles, but I don't know how and with what address to connect to it.

**Comment by liodali** [comment]
you mean you create your own server tile or you want to have offline tile on  our map ?

**Comment by masdercoder** [comment]
I create my server tile.
My server is also running in Windows as xampp.
I also have the tiles file .mbtiles and folders as shown in the photo below

![Screenshot 2024-04-28 175145](https://github.com/liodali/osm_flutter/assets/21294206/403d1d32-08c2-428b-9a87-abc779a677f2)

**Comment by masdercoder** [comment]
These folders are located at this address
![Screenshot 2024-04-28 175734](https://github.com/liodali/osm_flutter/assets/21294206/0eb96774-ff04-4721-85e1-984e19683170)

And this is the address I put in the code :  "http://localhost/train_media/map/masder/{z}/{x}/{y}.png"

I know this is my mistake, but I don't know the right way to connect to my server

**Comment by masdercoder** [comment]
error in flutter: 
W/OsmDroid( 2787): Problem downloading MapTile: /13/5453/3208 HTTP response: Not Found

![Uploading Screenshot 2024-04-29 000233.png…]()

**Comment by masdercoder** [comment]
error flutter: 
W/OsmDroid( 2787): Problem downloading MapTile: /5/21/12 HTTP response: Not Found

![Screenshot 2024-04-29 000233](https://github.com/liodali/osm_flutter/assets/21294206/4ac91fd9-6a9f-4440-b38a-d7c9a3af00ba)

**Comment by masdercoder** [comment]
error flutter:
W/OsmDroid( 2787): Problem downloading MapTile: /13/5453/3208 HTTP response: Not Found

![Screenshot 2024-04-29 000233](https://github.com/liodali/osm_flutter/assets/21294206/2831a3f3-ebd1-4e70-8d25-46e7e08e6ae9)

**Comment by masdercoder** [comment]
I tested with the flutter_map package. It worked correctly with this package and showed the tiles!!

**Comment by liodali** [comment]
just to understand the issue only in that part its shown some tile or nothing is shown ? black view ?

**Comment by liodali** [comment]
show me the mapcontroller configuration

**Comment by masdercoder** [comment]
mapcontroller = MapController(
      initPosition: GeoPoint(latitude: 36.304242, longitude: 59.6241052),
    );

**Comment by masdercoder** [comment]
osmOption = OSMOption(
      zoomOption: const ZoomOption(maxZoomLevel: 16, minZoomLevel: 5),
      staticPoints: staticPoints,
    );

**Comment by masdercoder** [comment]
> just to understand the issue only in that part its shown some tile or nothing is shown ? black view ?


![Screenshot 2024-04-29 144247](https://github.com/liodali/osm_flutter/assets/21294206/137ebe62-8fdb-49d3-b012-5b03d10e601d)

**Comment by liodali** [comment]
for customtile you need to force in mapController
how did you force to take
your offline you mean you have inner server in phone or another setup
how did you do the integration for offline side ? 
i need more information about you setup and offline server

**Comment by masdercoder** [comment]
I have a Windows server to which Android boxes are connected via LAN. In the photo above, I showed that I started my server with xampp.
Everything works fine online, but when I enter the network address of my server to use with offline server tiles, it cannot load them.

**Comment by masdercoder** [comment]
mapcontroller = MapController.customLayer(
      initPosition: GeoPoint(
        latitude: 47.4358055,
        longitude: 8.4737324,
      ),
      customTile: CustomTile(
        sourceName: "masder",
        tileExtension: ".png",
        minZoomLevel: 5,
        maxZoomLevel: 16,
        urlsServers: [
          TileURLs(
            url: "http://192.168.2.10/train_media/map/masder/{z}/{x}/{y}.png",
          )
        ],
        tileSize: 256,
      ),
    );

**Comment by liodali** [comment]
now I can help you:
just fix customTile like this 
```dart
mapcontroller = MapController.customLayer(
          initPosition: GeoPoint(
          latitude: 47.4358055,
          longitude: 8.4737324,
          ),
          customTile: CustomTile(
          sourceName: "masder",
                  tileExtension: ".png",
                  minZoomLevel: 5,
                  maxZoomLevel: 16,
                  urlsServers: [
                  TileURLs(
                        url: "http://192.168.2.10/train_media/map/masder/",
                  )
          ],
          tileSize: 256,
        ),
);

```
small note 
make use in the manifest.xml you have this : android:usesCleartextTraffic="true" put it in application like this:
```xml
<application
       ...
        android:usesCleartextTraffic="true">...</application

```

**Comment by masdercoder** [comment]
Thankful. fixed!!!!!!!
My only mistake was that I had the wrong address

**Comment by liodali** [comment]
yep just added /z/x/y.png that handle it internally because raster server works like that but i will add a check to url that if z/x/y  will correct it and accep it internally

**Comment by masdercoder** [comment]
Thankful. It was great
