### ISSUE TITLE
Map location always starts in USA- Washington then it moves to the location that I initialize with   

### ISSUE THREAD

**Issue by medalawi** [liodali/osm_flutter#532]
Map location always starts in USA- Washington then it moves to the location that I initialize with   
For Example :
```
 MapController   controller =
  MapController.withPosition(initPosition:GeoPoint(latitude:51.1638175, longitude: 10.4478313),
  );
```

**Comment by medalawi** [comment]
android

**Comment by liodali** [comment]
can you record small video to see it ?

**Comment by liodali** [comment]
@medalawi

**Comment by misterprog-dev** [comment]
@medalawi I think that, this occurs when you work on emulator. For real device, the maps show your current position.
