### ISSUE TITLE
flutter_osm_web >=1.0.0-rc.3 depends on web ^0.5.1

### ISSUE THREAD

**Issue by Lakipaul** [liodali/osm_flutter#536]
adding the dependency with version 1.0.0 or higher, im facing this issue
Because every version of flutter_localizations from sdk depends on web 0.3.0 and flutter_osm_web >=1.0.0-rc.3 depends on web ^0.5.1, flutter_localizations from sdk is incompatible with flutter_osm_web >=1.0.0-rc.3.
And because flutter_osm_plugin >=1.0.5 depends on flutter_osm_web >=1.0.3 <1.0.4, flutter_localizations from sdk is incompatible with flutter_osm_plugin >=1.0.5.
and im using it for mobile app only. 
Flutter 3.16.5

**Comment by liodali** [comment]
did try to override the web package  to latest version ?

**Comment by Lakipaul** [comment]
thank you for you effort and responding,
im not even using web package, i have flutter_localizations which apparently using web 0.3.0

**Comment by liodali** [comment]
override the version will solve the issue
```yaml

dependency_overrides:
      web:0.5.1

```
