### ISSUE TITLE
Tile provider with reversed coordinates

### ISSUE THREAD

**Issue by stephanefarges** [liodali/osm_flutter#537]
Hi,

I'm trying to make this plugin work with a CustomTile for a tile provider using reversed X Y coordinates : /tile/{Z}/{Y}/{X}
I tried putting the /{Z}/{Y}/{X} in the url of the CustomTile but it doesn't seem to work.
Is there a way to do this ?

**Comment by liodali** [comment]
is your server support that format ?

**Comment by stephanefarges** [comment]
Hi,

The tile server I want to use respond to inverted coordinates, for example
https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/11/711/997.png
compared to 
https://b.tile.openstreetmap.fr/osmfr/11/997/711.png

I know for example leafletjs allow to use placeholders in the url like so 'https://{s}.somedomain.com/blabla/{z}/{x}/{y}{r}.png'
I was wondering if there was something of the sort in osm_flutter

Thanks for your help.

**Comment by liodali** [comment]
i will check that why not working as expected
and will do fix for it
maybe i will need more collaboration with you to test it correctly

**Comment by liodali** [comment]
for this matter it by default  z/x/y 
i will add some api that we can customize it 
its easy for ios/web but android its not because how osmdroid do it tile source 
but i start do some implementation hope will be done this weekend

**Comment by liodali** [comment]
check the new version `1.1.0`
now you can use full path in customTile you can put like this 
`https://{s}.somedomain.com/blabla/{z}/{y}/{x}` without extension

**Comment by stephanefarges** [comment]
It works great ! Thanks a lot for your help.
