### ISSUE TITLE
Disable OSMFLUTTER tap/drag

### ISSUE THREAD

**Issue by natig3** [liodali/osm_flutter#538]
I would like to disable touch and drag on the map, as I only use it as a viewer, and I am having a problem showing dialogs in front of the map, as the focus remains on the map and not on the dialogs so I can click on their buttons, if you can help me Help me resolve this, I'd be grateful! 

I've used many things to disable the touch on the map, but I wasn't successful, I used GestureDetector to capture the touches and disable it, I used Positioned to position the dialog on the map, I used IgnorePointer, Listener, Positioned.fill...

Example of my code:

Container(
                                                      height: 300,
                                                      margin: EdgeInsets.only(top: 20),
                                                      width: MediaQuery.of(context).size.width - 40,
                                                      child: Stack(
                                                        children: <StatefulWidget>[
                                                          OSMFlutter(
                                                            controller: Controller.to.mapController,
                                                            osmOption: OSMOption(
                                                              enableRotationByGesture: false,
                                                              zoomOption: ZoomOption(
                                                                initZoom: 14,
                                                                maxZoomLevel: 19,
                                                              ),
                                                              staticPoints: Controller.to.staticPoints,
                                                            ),
                                                          ),
                                                        ],
                                                      ),
                                                    )

-------------
flutter doctor -v 

[√] Flutter (Channel stable, 3.22.2
    • Flutter version 3.22.2 
    • Dart version 3.4.3
    • DevTools version 2.34.3

 flutter_osm_plugin: ^1.0.5
![Captura de tela 2024-07-04 095650](https://github.com/liodali/osm_flutter/assets/60522071/46425348-eb84-4c3e-afc7-7c5284d542d2)
![b92500e0-8ff9-4b68-889c-fc94023bfe98](https://github.com/liodali/osm_flutter/assets/60522071/1e70ebef-1a86-4ce5-b5d7-b486afaf88b8)

**Comment by liodali** [comment]
i will add that feature soon

**Comment by natig3** [comment]
If it's not too much to ask, can you tell me how long this option will be available?

I'm waiting for this issue...

**Comment by liodali** [comment]
i will work on small feature for custom tile and this one 
it should not  be so difficult so
probably this weekend or beginning of next week

**Comment by natig3** [comment]
Excellent, I look forward to hearing from you, thank you!!

**Comment by liodali** [comment]
sorry for being late 
the new version will published today or tomorrow at maximum

**Comment by liodali** [comment]
the release will up in one hour
preparing just the docs 
I created new map widget called as you can see in this example 
you should use with that widget `SimpleMapController`
```dart
       OSMViewer(
             controller: SimpleMapController(
               initPosition: GeoPoint(
                 latitude: 47.4358055,
                 longitude: 8.4737324,
                ),
                  markerHome: const MarkerIcon(
                    icon: Icon(Icons.home),
                  ),
                ),
                zoomOption: const ZoomOption(
                  initZoom: 16,
                  minZoomLevel: 11,
                ),
              )

```

**Comment by natig3** [comment]
Thank you for your help Liodali!!

It really helped me to block the map touch, it was static. 

However, regarding the dialogs, the map continues to overlap them, this is a problem, as I need to click on their buttons and I am unsuccessful, my buttons seem to be disabled due to the map... 

![chrome_tQCj1aOIam](https://github.com/user-attachments/assets/54d7f347-eefa-4495-a815-4905282aec47)

See my code sample:

Dart version 3.4.3
Flutter version 3.22.2
flutter_osm_plugin: 1.2.0


Container(
                                                      height: 300,
                                                      margin: EdgeInsets.only(top: 20),
                                                      width: MediaQuery.of(context).size.width - 40,
                                                      child: OSMFlutter(
                                                            controller: Controller.to.mapController,
                                                            osmOption: OSMOption(
                                                              enableRotationByGesture: false,
                                                              zoomOption: ZoomOption(
                                                                initZoom: 16,
                                                                maxZoomLevel: 19,
                                                              ),
                                                              staticPoints: Controller.to.staticPoints,
                                                            ),
                                                          ),
                                                    )



-----------

 Get.defaultDialog(
                  title: "Salvar",
                  middleText: "Você possuí alterações, deseja salvar?",
                  backgroundColor: Colors.white,
                  titleStyle: TextStyle(color: Color(0xff01243a), fontWeight: FontWeight.bold),
                  middleTextStyle: TextStyle(color: Color(0xff424242)),
                  textConfirm: "Salvar",
                  textCancel: "Não Salvar",
                  cancelTextColor: Color(0xff424242),
                  confirmTextColor: Colors.white,
                  buttonColor: Color(0xff01243a),
                  onConfirm: () async { },
                  onCancel: () async {},);

**Comment by liodali** [comment]
is your app running on web?

**Comment by natig3** [comment]
yes

**Comment by liodali** [comment]
add this package to pubspec 
 ` pointer_interceptor: ^0.9.3+3 `

and put your button under the pointerInterceptor widget it will work as expected thats issue related to iframe in flutter
