### ISSUE TITLE
Flutter launching in iOS emulator : No such module 'OSMFlutterFramework'

### ISSUE THREAD

**Issue by misterprog-dev** [liodali/osm_flutter#545]
Hi, when I run my flutter project, I got error bellow : 

Failed to build iOS app
Swift Compiler Error (Xcode): No such module 'OSMFlutterFramework'

**Comment by liodali** [comment]
did you try to open ios folder and run pod install or pod update ?

**Comment by misterprog-dev** [comment]
Yes, I did that.
Also, I run flutter clean, delete my .pub-cached content and rerun all. But I got this error.

**Comment by misterprog-dev** [comment]
@liodali I have this error in the  Extension.swift

<img width="733" alt="Capture d’écran 2024-07-26 à 20 08 57" src="https://github.com/user-attachments/assets/dead9f7a-47e6-44a0-8d47-b300b9ccf00a">

**Comment by liodali** [comment]
remove pod.lock and run again pod install and share the terminal log

**Comment by misterprog-dev** [comment]
<img width="1129" alt="Capture d’écran 2024-07-26 à 20 30 22" src="https://github.com/user-attachments/assets/cb7403d2-17c0-433f-83ef-ec32afc6c57b">

<img width="1129" alt="Capture d’écran 2024-07-26 à 20 33 15" src="https://github.com/user-attachments/assets/9268c448-9715-4689-9c1b-f43e403775c3">

**Comment by liodali** [comment]
update our plugin to 1.2.0

**Comment by misterprog-dev** [comment]
I got same issue

**Comment by misterprog-dev** [comment]
@liodali  is the plugin only valid for a certain version of ios?

**Comment by liodali** [comment]
what min ios that your app support ?

**Comment by misterprog-dev** [comment]
<key>MinimumOSVersion</key>
  <string>12.0</string>

**Comment by liodali** [comment]
min in out sdk in 13 change it to 13 will hurt that much and it will work

**Comment by misterprog-dev** [comment]
Is there a forcing command to perform? Because I have the same error with min sdk 13

**Comment by liodali** [comment]
did you tried to run again pod install in ios folder ?

**Comment by misterprog-dev** [comment]
yes, I run pod install in ios folder

**Comment by liodali** [comment]
run flutter clean and remove build file from ios folder and podfile and podfile.lock and run flutter pub get 
 then run this command `pod install --clean-install`

**Comment by misterprog-dev** [comment]
I got this error in my console

Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "flutter_osm_plugin":
  In Podfile:
    flutter_osm_plugin (from `.symlinks/plugins/flutter_osm_plugin/ios`)

Specs satisfying the `flutter_osm_plugin (from `.symlinks/plugins/flutter_osm_plugin/ios`)` dependency were found, but they required a higher minimum deployment target.

[!] Automatically assigning platform `iOS` with version `12.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by liodali** [comment]
you need to change required minimum target for ios to 13 
open xcode and change to this 
![image](https://github.com/user-attachments/assets/d69e234d-0de3-40b0-8b27-306cbf57976c)

**Comment by misterprog-dev** [comment]
Sorry for my late answers,

I always have the same issue:

Failed to build iOS app
Swift Compiler Error (Xcode): No such module 'OSMFlutterFramework'
xxxxxxx/.pub-cache/hosted/pub.dev/flutter_osm_plugin-1.2.0/ios/Classes/map_view/osm_map.swift:8:7

Encountered error while building for device.

**Comment by misterprog-dev** [comment]
@liodali this is my test repo.I just added the OSM plugin and didn't do anything else.: https://github.com/misterprog-dev/osm_test

**Comment by liodali** [comment]
bad news that when i build that repo it works fine
try to reset dart package cache and cocoapod as well

**Comment by liodali** [comment]
also update to news version as well using `pod update`

**Comment by misterprog-dev** [comment]
@liodali  Maybe the problem is with my MacBook, I have an M1 chip

**Comment by misterprog-dev** [comment]
@liodali Can you do a pull request for your change in local on the sample project I sent? I want to know a difference if you make some changes.

**Comment by liodali** [comment]
I didnt change anything just buiild it 
try to clear cocoapod cache and dart cache

**Comment by misterprog-dev** [comment]
Hello, @liodali . I fixed the problem.Sorry I didn't feedback. The problem was pod install didn't download OSMPluginFramework. I was only a readme file in his folder.
