### ISSUE TITLE
Is there a way to make drawn single or multi road dotted line?

### ISSUE THREAD

**Issue by Djakh** [liodali/osm_flutter#547]

**Comment by liodali** [comment]
im planning to add that feature as well soon

**Comment by Djakh** [comment]
Oh really?, would be good, i will wait till then, approximately in what
time are you going to add it? If you need any help i am ready to help with
anything

чт, 1 авг. 2024 г., 17:40 hamza mohamed ali ***@***.***>:

**Comment by liodali** [comment]
dotted polyline is done for mobile
still facing some issue for web side i hope to finish the web in this week i will publish new version

**Comment by Djakh** [comment]
no, it's about time, thank you for considering my request

**Comment by liodali** [comment]
this feature now on dev branch.
more tests and we will publish new version

**Comment by liodali** [comment]
I didnt add dotted to multi road because im planning to remove it 
since im working on dart_routing_client which will be used in the near future instead of having native implementation for each platform. thats will lead to fast draw lines and more control from dart side

**Comment by Djakh** [comment]
okey, dart_routing_client will be released in version 1.4.0?

**Comment by liodali** [comment]
currently we are using dart_routing_client in web side only but maybe we will remove all routing request in native and pass that part to developer and we keep drawing only the routes with more custom way 
 because thats can remove complexity and add more freedom to developers who own custom routing server

**Comment by Djakh** [comment]
Hi lioadli, is not there any news about dotted polyline on multi road?

**Comment by Djakh** [comment]
okey thanks
