### ISSUE TITLE
iOS: osm_flutter version 1.2.0 throws an error: Value of type 'OSMView' has no member 'disableTouch'

### ISSUE THREAD

**Issue by romanost** [liodali/osm_flutter#552]
Failed to build iOS app
Swift Compiler Error (Xcode): Value of type 'OSMView' has no member 'disableTouch'
/Users/.........../.pub-cache/hosted/pub.dev/flutter_osm_plugin-1.2.0/ios/Classes/map_view/osm_map.swift:82:24

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.

Flutter version 3.22.0
Dart version 3.4.0
Xcode 15.4

podfile:
platform :ios, '13.0'
...

**Comment by liodali** [comment]
in folder ios run pod update

**Comment by romanost** [comment]
works now, thanks
