### ISSUE TITLE
floatingActionButton not working on web build

### ISSUE THREAD

**Issue by lvenier** [liodali/osm_flutter#556]
| Flutter osm version|
| --- |
| 1.2.0 |

## Actual Behavior

I have created a

as per the code below : 

![image](https://github.com/user-attachments/assets/3fbab12e-250d-48ec-bc14-e6fa2dd3b054)

I get the following screen : 

![image](https://github.com/user-attachments/assets/b4787f60-4153-4764-932e-1fd1ba7e15a0)

floatingActionButton on IOS and ANDROID is working fine. On the web it looks like the elevation or z-index is not working.
On browser if I click on button I am moving the OSM widget.

## Desired Behavior

The floatingActionButton should work on the web as it is working on android and ios.

Many thanks for your help

**Comment by liodali** [comment]
use pointer_detector package and make it parent for floatingactionbutton

**Comment by liodali** [comment]
thnx i appriciate you feedback and your sponsor me really happy to other devs using our plugin
