### ISSUE TITLE
removeAllCircle() and removeCircle() not working

### ISSUE THREAD

**Issue by delanceronline** [liodali/osm_flutter#557]
removeAllCircle() and removeCircle() methods are not working in version 1.2.0, while Rect one working fine. It happens on both Android and iOS.

**Comment by liodali** [comment]
i will fix that

**Comment by liodali** [comment]
the issue fixed on ios
and now we are fixing android side

**Comment by liodali** [comment]
check our new version `1.3.0`

**Comment by delanceronline** [comment]
ERROR:/.gradle/caches/transforms-3/33591479d3b0fd046d0e99ae9ae03915/transformed/appcompat-1.7.0-runtime.jar: D8: java.lang.NullPointerException
ERROR:/.gradle/caches/transforms-3/33591479d3b0fd046d0e99ae9ae03915/transformed/appcompat-1.7.0-runtime.jar: D8: java.lang.NullPointerException
ERROR:/.gradle/caches/transforms-3/cc3ea36e429952645a681a11c442670c/transformed/jetified-appcompat-resources-1.7.0-runtime.jar: D8: java.lang.NullPointerException

Seems 1.3.0 not compatible with my existing project. 1.2.0 works fine. Any clues? Thanks.

**Comment by liodali** [comment]
try to run flutter clean and flutter pub get

**Comment by delanceronline** [comment]
> try to run flutter clean and flutter pub get

Yes I did, also cleaning all gradle cache and recompiled as well. Maybe some dependencies in my project having conflicts with your new version, I will try to figure it out. Thanks!

**Comment by liodali** [comment]
try to clear gradle cache ? or upgrade gradle version in you app
