### ISSUE TITLE
marker get smaller 

### ISSUE THREAD

**Issue by lvenier** [liodali/osm_flutter#560]
Hello,

I am encountering an issue in the usage of the plugin.
I have a map where I have added a marker : 

![image](https://github.com/user-attachments/assets/d64ba51c-b769-4918-a4ef-70c3493a73eb)

Im my app if I change the marker color and add a circle with the following functions : 
await controller.setMarkerIcon(geopoint, blackIcon);
await controller.drawCircle(CircleOSM(
                    key: "BlackPoint",
                    centerPoint: geopoint,
                    radius: 30.0,
                    color: Colors.white.withOpacity(0.5),
                    borderColor: Colors.white,
                    strokeWidth: 0,
                  ));

I have may Marker size being changed (looks like divided by 2) : 

![image](https://github.com/user-attachments/assets/3a5705ae-bf62-4e3d-b66e-ced94d5023fd)

Anything I should do ?
Many thanks for your help.

**Comment by lvenier** [comment]
> on which platform you faced the issue ?

no issue on android. not tested on apple.
web only.

**Comment by liodali** [comment]
* is the issue happen when you draw the circle or when you set the marker icon ?

* another unrelated question are you happy with result from osrm because im working on adding other services like valhala or openroute ?

**Comment by lvenier** [comment]
> * is the issue happen when you draw the circle or when you set the marker icon ?
if i change a markerIcon with no circle it is working. It looks it is adding the circle that create the image reduction.
> * another unrelated question are you happy with result from osrm because im working on adding other services like valhala or openroute ?
I have to say osrm is not the greatest but it is enough for our usage.

**Comment by liodali** [comment]
thnx for your feedback
i will make fix for the bug
and for routing like i said im working on adding more routing api in our routing client

**Comment by liodali** [comment]
new version has being published `1.3.1`

**Comment by lvenier** [comment]
Thanks for your fix.

I was not able to test as I get the following error when upgrading to 1.3.0 : 

![image](https://github.com/user-attachments/assets/d252f470-cec7-4f37-989b-ff8c5932ff1e)

I have also the same issue in 1.3.1

**Comment by liodali** [comment]
iwill back home soon i will check it and do fix
sorry for that

**Comment by liodali** [comment]
technically no i need to fix migration to web package the issue that response from js not what we expect so i will setup https for localhost that i can test getcurrentposition correctly

**Comment by liodali** [comment]
new version has been published `1.3.2`

**Comment by liodali** [comment]
can you show me more of error trace ?

**Comment by liodali** [comment]
new version is already published `1.3.3`

**Comment by lvenier** [comment]
> new version is already published `1.3.3`

I will test it today. Many thanks

**Comment by lvenier** [comment]
All good ! It is working and no more issues.
