### ISSUE TITLE
UpdateMarker iOS crash

### ISSUE THREAD

**Issue by lvenier** [liodali/osm_flutter#565]
Hello,

I am drawing marker on the map.
I am changing the color of the marker with the following function: 
```
await controller.setMarkerIcon(
                      myGeoPointLocation, colorcon);
```
On IOS when I change the color 2 times I got a crash with the following trace:
```
update#Marker
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSFrozenArrayM objectAtIndex:]: index 9 beyond bounds [0 .. 7]'
*** First throw call stack:
(0x18e73908c 0x18ba3b2e4 0x18e7104a0 0x18cd217cc 0x104204994 0x104205fa0 0x103651bd0 0x103647ca0 0x103644924 0x103644a00 0x107c1b210 0x10769cd88 0x103de8a30 0x103dea71c 0x103dfade8 0x103dfa9a4 0x18e70bf64 0x18e709188 0x18e7085b8 0x1da19e1c4 0x19125e5f0 0x19130d10c 0x191639e50 0x102aac988 0x102aac900 0x102aaca04 0x1b3edbd34)
libc++abi: terminating due to uncaught exception of type NSException
```

The issue is only on IOS. I have not that issue on web and android.

**Comment by sijangurung** [comment]
did you check if the map is loaded or not, on onMapIsReady.
I tried but cannot reproduce the error.

```
  final colorIcon = const MarkerIcon(
    icon: Icon(Icons.person_pin_circle, color: Colors.red, size: 60),
  );

  final greenColorIcon = const MarkerIcon(
    icon: Icon(Icons.pin_drop, color: Colors.green, size: 60),
  );

      await mapController.setMarkerIcon(kingsPalacePoint, colorIcon);
      await Future.delayed(const Duration(seconds: 3));
      await mapController.setMarkerIcon(kingsPalacePoint, greenColorIcon);
```

**Comment by liodali** [comment]
@lvenier if you can provide more code to check the cause because as @sijangurung  comment
I tested it seems to work as expected

**Comment by liodali** [comment]
also it seem that you execute some staff before setMarkerIcon that leads to out of range ( like deleteMarker without await maybe )
internally we search for marker object in our cache then we update ther marker and we store the new marker information

**Comment by lvenier** [comment]
I dont see anywhere any await missing.
What I dont understand is why is it working for web  and android and not ios.

As an information Im doing this : 
```
      await mapController.setMarkerIcon(kingsPalacePoint, colorIcon);
...
      await removeCircle() on the same point as the marker. Any connection/collision possible in IOS?
...
      await mapController.setMarkerIcon(kingsPalacePoint, greenColorIcon);
```

**Comment by liodali** [comment]
is crash happen after remove circle or before ?

**Comment by liodali** [comment]
when setMarkerIcon first and them remove does the marker change the icon and circle get removed and the crash happen or from the beginning
is that code running inside loop ?

**Comment by lvenier** [comment]
this code is not in a loop. I will make some tests to see if I can provide more inputs.

**Comment by fanshan** [comment]
> is the crash happen after remove circle or before ?

Hello, the crash happen after the remove circle

```
remove#circle
update#Marker
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSFrozenArrayM objectAtIndex:]: index 7 beyond bounds [0 .. 6]'
*** First throw call stack:
(0x18e73908c 0x18ba3b2e4 0x18e7104a0 0x18cd217cc 0x105db0994 0x105db1fa0 0x1051e5bd0 0x1051dbca0 0x1051d8924 0x1051d8a00 0x1097c7210 0x109248d88 0x1059f0a30 0x1059f271c 0x105a02de8 0x105a029a4 0x18e70bf64 0x18e709188 0x18e7085b8 0x1da19e1c4 0x19125e5f0 0x19130d10c 0x191639e50 0x104548988 0x104548900 0x104548a04 0x1b3edbd34)
libc++abi: terminating due to uncaught exception of type NSException
```

**Comment by liodali** [comment]
ok thnx i will try to reproduce the issue and check our internal layer manager

**Comment by liodali** [comment]
we fixed the issue in our iOS sdk if you can just go ios folder and run pod update

**Comment by lvenier** [comment]
We will test and let you know...

**Comment by fanshan** [comment]
Hello @liodali It's seem fixed. Thank you very much :-)
