### ISSUE TITLE
Unhandled Exception: FormatException: Unexpected character (at character 1)

### ISSUE THREAD

**Issue by Joesta** [liodali/osm_flutter#570]
OSM is throwing  FormatException when I land into the MAP view page where I have implmeneted the search and pick location. 
Please see the below exception. 

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected character (at character 1)
E/flutter (19448): <html>
E/flutter (19448): ^
E/flutter (19448): 
E/flutter (19448): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1465:5)
E/flutter (19448): #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1332:9)
E/flutter (19448): #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:933:22)
E/flutter (19448): #3      _parseJson (dart:convert-patch/convert_patch.dart:36:10)
E/flutter (19448): #4      JsonDecoder.convert (dart:convert/json.dart:610:36)
E/flutter (19448): #5      JsonCodec.decode (dart:convert/json.dart:216:41)
E/flutter (19448): #6      jsonDecode (dart:convert/json.dart:155:10)
E/flutter (19448): #7      _OpenStreetMapSearchAndPickState.setNameCurrentPosAtInit (package:open_street_map_search_and_pick/open_street_map_search_and_pick.dart:129:9)
E/flutter (19448): <asynchronous suspension>

OSM plugin version used =   flutter_osm_plugin: ^1.3.5. 

Please assist.

**Comment by liodali** [comment]
I dont think related to the map issue since in your log error 
Its json parsing issue. 
without example from your code I cannot help to solve the issue.
provide us more information

**Comment by Joesta** [comment]
> I dont think related to the map issue since in your log error Its json parsing issue. without example from your code I cannot help to solve the issue. provide us more information

Hi Liodali, 

Please see the code snipped below

  Widget _getIncidentmap(IncidentState state) {
    return OpenStreetMapSearchAndPick(
      buttonTextStyle: white16MediumTextStyle,
      buttonColor: // state is! InitiatingReportingState ? ThemeColors.transparent :
          ThemeColors.secondaryColor,
      buttonText: 'Capture Incident at Location',
      locationPinIconColor: ThemeColors.primaryColor,
      locationPinText: "",
      locationPinIcon: Icons.location_pin,
      locationPinTextStyle: orange12NnormalTextStyle,
      onPicked: (pickedData) {
        print("lati"+pickedData.latLong.latitude.toString());
        print(pickedData.latLong.longitude);
        print(pickedData.address);
        print(pickedData.addressName);
        _onGetRouteSectionPressed(
            pickedData.latLong.latitude, pickedData.latLong.longitude);
      },
    );
  }

  void _onGetRouteSectionPressed(double latitude, double longitude) {
    showLoaderDialog(context);
    BlocProvider.of<IncidentBloc>(context).add(
      InitiateRouteSectionPointEvent(latitude, longitude),
    );
  }

**Comment by liodali** [comment]
from where you get `OpenStreetMapSearchAndPick ` we dont have that widget in our plugin
which package do you use for that ?

**Comment by Joesta** [comment]
> _getIncidentmap

It's comding from this package: 'package:open_street_map_search_and_pick/open_street_map_search_and_pick.dart'

**Comment by liodali** [comment]
you're in the wrong github repo
