### ISSUE TITLE
iOS support 

### ISSUE THREAD

**Issue by liodali** [liodali/osm_flutter#60]
I will add iOS support for osm

**Comment by liodali** [comment]
for ios support, i have 2 weeks that i changed code used from  mapkit to tangram es [https://github.com/tangrams/tangram-es](link)
i will do my best to at least this month i publish  alpha version

**Comment by liodali** [comment]
A new version was published  `0.8.0-alpha.0` that support ios for now it contain
  * visualisation of the map in ios 
  * show static position
  * support select position (custom marker, not network image will not work) 
  * support track user location

**Comment by liodali** [comment]
and now i will start support for other feature in the map :
i will prioritize  : 
    1) draw road
    2) select marker 
    3) advanced selection position

**Comment by liodali** [comment]
I found bug in ios version i will fix now

**Comment by liodali** [comment]
new version was publied `0.8.0-alpha.1`

**Comment by liodali** [comment]
good news that drawRoad now is implemented 
need to make more test and it will be shipped to night or tomorrow

**Comment by liodali** [comment]
the ios support reach beta stage soon will be stable
i would be happy to give it a try

**Comment by Romowski** [comment]
Hi! 
how can I try  version on ios? 
Added `flutter_osm_plugin: ^0.11.0-beta.4` and `pod install` 
Here is output:

`[!] CocoaPods could not find compatible versions for pod "flutter_osm_plugin":
  In Podfile:
    flutter_osm_plugin (from `.symlinks/plugins/flutter_osm_plugin/ios`)

Specs satisfying the `flutter_osm_plugin (from `.symlinks/plugins/flutter_osm_plugin/ios`)` dependency were found, but they required a higher minimum deployment target.`

**Comment by liodali** [comment]
the minimun ios dev supported is 13 you should change  deployment target to 13 with xcode info.plist

**Comment by Romowski** [comment]
> the minimun ios dev supported is 13 you should change deployment target in ` info.plist` to 13 with xcode

yes, `info.plist` is fine, but I forgot about Podfile's `global platform` parameter:

`platform :ios, '10.0'`

Thank you for quick reply

**Comment by liodali** [comment]
* I publish stable version of ios support  `0.11.0` that contain all most the same feature with android
the only difference for now that in ios side we used vector map due to some bugs in sdk that prevent us to use raster map
* in ios side we used tangram es
* minimum ios sdk supported is 13 , so before you build in xcode you should change development req in info.plist with xcode

**Comment by blerinarexhepi** [comment]
I'm having a problem with the ios with point selection features. If you select a point the listener gets the topLeft corner of the screen as the point you selected. I'm attaching a video to show in more detail what I'm talking about.

https://user-images.githubusercontent.com/81185529/134501872-dd0a99d1-7ef6-46be-a8c0-cfe61710a502.mov

**Comment by liodali** [comment]
ok i will fix that

**Comment by liodali** [comment]
which version do you use ?

**Comment by blerinarexhepi** [comment]
0.15.0

**Comment by liodali** [comment]
try 0.16.0 or 0.21.0-rc.2
