### ISSUE TITLE
Simply add map after install dependency getting compilation error

### ISSUE THREAD

**Issue by prabhunath111** [liodali/osm_flutter#70]
e: C:\Users\prabhunt\Downloads\flutter_windows_2.0.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.6.7+3\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\FlutterInfoWindow.kt: (42, 56): Expecting an argument
e: C:\Users\prabhunt\Downloads\flutter_windows_2.0.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.6.7+3\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\FlutterOsmPlugin.kt: (92, 34): Expecting an argument
e: C:\Users\prabhunt\Downloads\flutter_windows_2.0.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.6.7+3\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\FlutterOsmPlugin.kt: (93, 19): Expecting an argument
e: C:\Users\prabhunt\Downloads\flutter_windows_2.0.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.6.7+3\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\FlutterOsmView.kt: (89, 31): Expecting a parameter declaration
e: C:\Users\prabhunt\Downloads\flutter_windows_2.0.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.6.7+3\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\FlutterRoad.kt: (12, 38): Expecting a parameter declaration
e: C:\Users\prabhunt\Downloads\flutter_windows_2.0.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.6.7+3\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\OsmFactory.kt: (19, 57): Expecting a parameter declaration
e: C:\Users\prabhunt\Downloads\flutter_windows_2.0.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.6.7+3\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\OsmFactory.kt: (24, 24): Expecting a parameter declaration
e: C:\Users\prabhunt\Downloads\flutter_windows_2.0.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.6.7+3\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\OsmFactory.kt: (33, 27): Expecting an argument
e: C:\Users\prabhunt\Downloads\flutter_windows_2.0.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.6.7+3\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\network\ApiClient.kt: (17, 39): Expecting a parameter declaration
e: C:\Users\prabhunt\Downloads\flutter_windows_2.0.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.6.7+3\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\utilities\FlutterPickerViewOverlay.kt: (10, 34): Expecting a parameter declaration

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_osm_plugin:kaptGenerateStubsDebugKotlin'.
> Compilation error. See log for more details

**Comment by liodali** [comment]
what's gradle version in your android module ?

**Comment by prabhunath111** [comment]
dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }

**Comment by liodali** [comment]
are you using flutter 2 and null safety feature

**Comment by prabhunath111** [comment]
I am using flutter 2 only not null safety feature.

**Comment by liodali** [comment]
try to remove the library and make `flutter clean` and `pub get`  after that add again the library and make `pub get`

**Comment by prabhunath111** [comment]
yeah i did but getting same error.

**Comment by liodali** [comment]
try to update the gradle version to 4.1.1 before that remove library and make `flutter clean`
rebuild and again the library

**Comment by prabhunath111** [comment]
I am just install dependency and and implement OSMFlutter. nothing else

**Comment by prabhunath111** [comment]
OK trying

**Comment by prabhunath111** [comment]
I tried but still same issue, Can you please check it once here, I have only 10 lines code in main.dart, I think it'll not be tough to understand.

https://github.com/prabhunath111/osm_map


error: Launching lib\main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...
e: C:\Users\prabhunt\Downloads\flutter_windows_2.0.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.6.7+3\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\FlutterInfoWindow.kt: (42, 56): Expecting an argument
e: C:\Users\prabhunt\Downloads\flutter_windows_2.0.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.6.7+3\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\FlutterOsmPlugin.kt: (92, 34): Expecting an argument
e: C:\Users\prabhunt\Downloads\flutter_windows_2.0.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.6.7+3\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\FlutterOsmPlugin.kt: (93, 19): Expecting an argument
e: C:\Users\prabhunt\Downloads\flutter_windows_2.0.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.6.7+3\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\FlutterOsmView.kt: (89, 31): Expecting a parameter declaration
e: C:\Users\prabhunt\Downloads\flutter_windows_2.0.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.6.7+3\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\FlutterRoad.kt: (12, 38): Expecting a parameter declaration
e: C:\Users\prabhunt\Downloads\flutter_windows_2.0.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.6.7+3\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\OsmFactory.kt: (19, 57): Expecting a parameter declaration
e: C:\Users\prabhunt\Downloads\flutter_windows_2.0.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.6.7+3\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\OsmFactory.kt: (24, 24): Expecting a parameter declaration
e: C:\Users\prabhunt\Downloads\flutter_windows_2.0.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.6.7+3\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\OsmFactory.kt: (33, 27): Expecting an argument
e: C:\Users\prabhunt\Downloads\flutter_windows_2.0.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.6.7+3\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\network\ApiClient.kt: (17, 39): Expecting a parameter declaration
e: C:\Users\prabhunt\Downloads\flutter_windows_2.0.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.6.7+3\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\utilities\FlutterPickerViewOverlay.kt: (10, 34): Expecting a parameter declaration

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_osm_plugin:kaptGenerateStubsDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by liodali** [comment]
in `android/app/build.gradle` add this dependency 
```groovy
dependencies {
....
 def multidex_version = "2.0.1"
    implementation "androidx.multidex:multidex:$multidex_version"
}
```
```groovy
android {
defaultConfig {
       ....
      // add this
        multiDexEnabled true

    }
}

```
in android/build.gradle
update kotlin_version from 1.3.50 to 1.4.30
build and it will work fine

**Comment by prabhunath111** [comment]
Yeah Thank you so much, Now it's working.
