### ISSUE TITLE
Map hidden when searching Location in textfield

### ISSUE THREAD

**Issue by prabhunath111** [liodali/osm_flutter#71]
Kindly find attachment, Hope you can understand from this image.

when i search any location after that one layer is overlapping on the map.

![image](https://user-images.githubusercontent.com/45359383/114374026-d37a1c80-9ba0-11eb-9bc2-0acf0e8b6123.png)

**Comment by liodali** [comment]
in scaffold  put `resizeToAvoidBottomInset` to false
