### ISSUE TITLE
RenderBox was not laid out

### ISSUE THREAD

**Issue by Crel-Minister** [liodali/osm_flutter#73]
Hey. Great project! 

I have implemented a very simple OSMFlutter widget, using the code below
```
  MapController mapController = MapController(
    initMapWithUserPosition: true,
  );
```

```
      body: Container(
        child: Stack(children: <Widget>[
          OSMFlutter(
            controller: mapController,
            trackMyPosition: true,
            useSecureURL: false,
            showDefaultInfoWindow: false,
            defaultZoom: 3.0,
          ),
        ]),
      )
```

I keep getting the following error:

RenderBox was not laid out: RenderStack#1b4a0 relayoutBoundary=up3 NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

When i from portrait to landscape or vice versa i get the following error:

======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/object.dart': Failed assertion: line 1711 pos 12: '!_debugDoingThisLayout': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  OSMFlutter file:///C:/flutter_projects/mobile-app/lib/RobotPage.dart:93:11
When the exception was thrown, this was the stack: 
#2      RenderObject.layout (package:flutter/src/rendering/object.dart:1711:12)
#3      RenderStack.layoutPositionedChild (package:flutter/src/rendering/stack.dart:497:11)
#4      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:610:30)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#6      ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:54:11)
...
The following RenderObject was being processed when the exception was fired: RenderStack#1ee0e relayoutBoundary=up2 NEEDS-PAINT
...  needs compositing
...  parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...  constraints: BoxConstraints(0.0<=w<=384.0, 0.0<=h<=739.7)
...  size: Size(384.0, 739.7)
...  alignment: AlignmentDirectional.topStart
...  textDirection: ltr
...  fit: loose
...  clipBehavior: none
RenderObject: RenderStack#1ee0e relayoutBoundary=up2 NEEDS-PAINT
  needs compositing
  parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(0.0<=w<=384.0, 0.0<=h<=739.7)
  size: Size(384.0, 739.7)
  alignment: AlignmentDirectional.topStart
  textDirection: ltr
  fit: loose
  clipBehavior: none
...  child 1: RenderStack#76d10 relayoutBoundary=up3
...    parentData: top=-100.0; offset=Offset(0.0, 0.0) (can use size)
...    constraints: BoxConstraints(unconstrained)
...    size: MISSING
...    alignment: AlignmentDirectional.topStart
...    textDirection: ltr
...    fit: loose
...  child 2: RenderSemanticsAnnotations#590eb relayoutBoundary=up3 NEEDS-PAINT
...    needs compositing
...    parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...    constraints: BoxConstraints(0.0<=w<=384.0, 0.0<=h<=739.7)
...    semantics node: SemanticsNode#17
...      Rect.fromLTRB(0.0, 96.2, 813.2, 368.0)
...      flags: isFocusable
...    size: Size(384.0, 739.7)
...    child: RenderAndroidView#8cc97 NEEDS-PAINT
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=384.0, 0.0<=h<=739.7)
...      layer: OffsetLayer#f305b DETACHED
...        engine layer: OffsetEngineLayer#2212b
...        offset: Offset(0.0, 96.2)
...      semantics node: SemanticsNode#18
...        Rect.fromLTRB(0.0, 0.0, 813.2, 271.8)
...        platformViewId: 0
...      semantic boundary
...      size: Size(384.0, 739.7)
====================================================================================================
D/OsmDroid(18671): TileLoader failed to load tile due to mWriter being null (map shutdown?)
I/chatty  (18671): uid=10404(com.example.flutter_app) GarbageCollecto identical 3 lines

The second error, results in no connection to the map repository, and i thus have an only grey screen.

I suspect these errors to be connected, and i have tried wrapping the OSM widget in an expanded widget and a flexible widget, but the problem persists.

My current solution is to restrict the application to portrait mode, which means i never lose the connection to the map repository, but this is not a satisfactory solution as i would like to allow landscape mode.

Does anyone have a solution, or tried similar?

UPDATE:
This does not happen, when I use the simple OSMFlutter from examples. I don't see the difference though. I am however still not able to rotate the screen, and still have the map. 

I suspect the following error is what does it:
V/ViewRootImpl( 6646): The specified message queue synchronization  barrier token has not been posted or has already been removed

**Comment by Crel-Minister** [comment]
I figured some stuff out:
If i do not include a markerIcon configuration for the OSMFlutter widget, I get the rendering issues. Maybe this is an easy bug to fix idk. I still however have problems with the screen orientation which produces the following error:

D/ViewRootImpl(23762): not support adaptive color gamut feature!
V/ViewRootImpl(23762): The specified message queue synchronization  barrier token has not been posted or has already been removed
I/OsmDroid(23762): Tile cache increased from 9 to 15
D/OsmDroid(23762): TileLoader failed to load tile due to mWriter being null (map shutdown?)
I/chatty  (23762): uid=10404(com.example.flutter_app) GarbageCollecto identical 3 lines
D/OsmDroid(23762): TileLoader failed to load tile due to mWriter being null (map shutdown?)

**Comment by liodali** [comment]
there is problem in screen orientation  and osm , even i re-create map but i still have that problem
for now try to disable screen orientation

**Comment by liodali** [comment]
for first problem, i will check that problem and i will fix

**Comment by liodali** [comment]
you can solve the first problem by adding `clipBehavior: Clip.none,` in the Stack because  in osm  i already use stack t draw icon before i send them to native views

**Comment by liodali** [comment]
try `0.7.5+1`

**Comment by Crel-Minister** [comment]
Cheers for looking into this! i Am however still not being able to rotate the map after updating to  0.7.5+2. Is this my faulty implementation?

You wrote that you re-create the map on rotation, what do you mean by this?

**Comment by Crel-Minister** [comment]
aight cheers. I will disable rotation for now

**Comment by liodali** [comment]
for ios, rotate will be working fine when i will publish new version that support ios, only for android until i found a proper solution for that
