### ISSUE TITLE
Add a way to change Picker marker

### ISSUE THREAD

**Issue by UsamaKarim** [liodali/osm_flutter#78]
Assalam O' Alaikum, Hamza

I want to change marker with image while picking a location. Can you add this feature please?

**Comment by Crel-Minister** [comment]
Also it would be cool, to be able to use more than 1 type of markers in general ;-)

**Comment by liodali** [comment]
@Crel-Minister  can you explain more what did you mean by use more than 1 type

**Comment by liodali** [comment]
@UsamaKarim ok i will add this feature

**Comment by Crel-Minister** [comment]
> @Crel-Minister can you explain more what did you mean by use more than 1 type

I mean, that one has to state what icon to use to for the marker when creating the map. It would be nice, if it is possible to change this on the go, or state it for each selectPosition() call.  Maybe i have just overlooked something? :-)

**Comment by Crel-Minister** [comment]
An idea, would be to have a default marker, and then having the ability to chose a specific one for the each selectPosition :-)

**Comment by liodali** [comment]
ok i will added to my list to do. just i need to finish some bug in ios. and i will start implement those features in this weekend

**Comment by Crel-Minister** [comment]
Cheers mate

**Comment by UsamaKarim** [comment]
It will also be helpful if we get the address of the location (not only GeoPoint) if we select the marker while picking the location. I know that it can be achieved without any service and some Packages like [GeoCoding](https://pub.dev/packages/geocoding) have the feature to get the address from Platform's own services. But the users of your package will be mostly from the countries like China where Google Play Services do not work

**Comment by liodali** [comment]
if you can add this as new feature request to be implemented

**Comment by liodali** [comment]
the first request is done
I replaced `markerIcon` wither `markerOption` that you cant set  the default marker icon and ther picker marker

**Comment by liodali** [comment]
now i will start look how i will make set marker dynamic in runtime

**Comment by liodali** [comment]
I added dynamic marker for `selectionPosition`
you can put flutter icon or asset image or image from network
i will publish new version `0.7.8`
