### ISSUE TITLE
Build failed errors

### ISSUE THREAD

**Issue by jesussmile** [liodali/osm_flutter#85]
Hi, I followed the steps for the plugin, updated Kotlin and Flutter, However, I run into errors. Any help please,  sorry if its a beginner question.
` e: C:\Users\pannam\Desktop\flutter_windows_2.0.6-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.7.6+1\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\FlutterInfoWindow.kt: (42, 56): Expecting an argument
e: C:\Users\pannam\Desktop\flutter_windows_2.0.6-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.7.6+1\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\FlutterOsmPlugin.kt: (60, 53): Expecting an argument
e: C:\Users\pannam\Desktop\flutter_windows_2.0.6-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.7.6+1\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\FlutterOsmPlugin.kt: (61, 23): Expecting an argument
e: C:\Users\pannam\Desktop\flutter_windows_2.0.6-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.7.6+1\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\FlutterOsmPlugin.kt: (91, 34): Expecting an argument
e: C:\Users\pannam\Desktop\flutter_windows_2.0.6-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.7.6+1\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\FlutterOsmPlugin.kt: (92, 19): Expecting an argument
e: C:\Users\pannam\Desktop\flutter_windows_2.0.6-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.7.6+1\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\FlutterOsmView.kt: (92, 31): Expecting a parameter declaration
e: C:\Users\pannam\Desktop\flutter_windows_2.0.6-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.7.6+1\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\FlutterOsmView.kt: (418, 41): Expecting an argument
e: C:\Users\pannam\Desktop\flutter_windows_2.0.6-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.7.6+1\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\FlutterOsmView.kt: (946, 52): Expecting an argument
e: C:\Users\pannam\Desktop\flutter_windows_2.0.6-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.7.6+1\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\FlutterRoad.kt: (12, 38): Expecting a parameter declaration
e: C:\Users\pannam\Desktop\flutter_windows_2.0.6-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.7.6+1\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\OsmFactory.kt: (18, 41): Expecting a parameter declaration
e: C:\Users\pannam\Desktop\flutter_windows_2.0.6-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.7.6+1\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\OsmFactory.kt: (23, 24): Expecting a parameter declaration
e: C:\Users\pannam\Desktop\flutter_windows_2.0.6-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.7.6+1\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\OsmFactory.kt: (31, 27): Expecting an argument
e: C:\Users\pannam\Desktop\flutter_windows_2.0.6-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.7.6+1\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\network\ApiClient.kt: (17, 39): Expecting a parameter declaration
e: C:\Users\pannam\Desktop\flutter_windows_2.0.6-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_osm_plugin-0.7.6+1\android\src\main\kotlin\hamza\dali\flutter_osm_plugin\utilities\FlutterPickerViewOverlay.kt: (11, 47): Expecting a parameter declaration

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_osm_plugin:kaptGenerateStubsDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Exception: Gradle task assembleDebug failed with exit code 1
`

**Comment by liodali** [comment]
Hi,
follow this step

 1.  remove flutter_osm_plugin from pubspec, after that pub get
 2. open android module in android studio ( right click in name of project -> flutter-> open android module in android studio)
 3. update gradle version to 4.1.1 ( IDE will show popup to make update)
 4. update kotlin version to 1.4.21 & re-build the project
 5. re-add flutter_osm_plugin in pubspec , pub get ( or flutter clean & pub get )
 
and you need also to supoort multidex in your project
see this link https://github.com/liodali/osm_flutter/issues/70#issuecomment-816638884

**Comment by jesussmile** [comment]
> Hi,
> follow this step
> 
> 1. remove flutter_osm_plugin from pubspec, after that pub get
> 2. open android module in android studio ( right click in name of project -> flutter-> open android module in android studio)
> 3. update gradle version to 4.1.1 ( IDE will show popup to make update)
> 4. update kotlin version to 1.4.21 & re-build the project
> 5. re-add flutter_osm_plugin in pubspec , pub get ( or flutter clean & pub get )
> 
> and you need also to supoort multidex in your project
> see this link [#70 (comment)](https://github.com/liodali/osm_flutter/issues/70#issuecomment-816638884)

yes! its working now.  had to add
 `   multiDexEnabled true`
