### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by jesussmile** [liodali/osm_flutter#98]
Hi! Just started to use your newer plugin `flutter_osm_plugin: ^0.7.8`, with the same code structure, that didn't give any errors, I get 
`Null check operator used on a null value ` 
I updated my usage of  widget `OSMFlutter(....)`  to include Road and markerIcon as per your setup, The error is on `class OSMFlutter`  on line 215 ` (widget.markerOption!.defaultMarker != null))` I suppose it is because of using null safety? If I remove the line it works okay, Any workaround? I don't want to mess with your core files. I don't use null safety and have very little idea about it. probably my error is because Widget.markerOption hasn't been initialized?

**Comment by liodali** [comment]
Hi,
i will fix the problem

**Comment by liodali** [comment]
it my fault i should make chekc `markerOption` and  deprecated att `markerIcon` but i didn't know that I checked in the wrong way, thanks for you report
